### ISSUE TITLE
[Sourcing] Some platform table issues

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10134]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

There are some differences between platform table and sample table from UI5. 

**Issue 1:**

In multi-selection mode, when all columns are non-visible, there should be no checkboxes present and user should not be able to select/deselect any checkbox:

https://github.com/SAP/fundamental-ngx/assets/22842279/b58564be-1c47-46f7-a37b-6217cecae9d1

**Issue 2:**

In multi-selection mode, when table is empty, the header checkbox should be disabled.

https://github.com/SAP/fundamental-ngx/assets/22842279/5cfa0a03-a005-4086-95cc-d145f91b55be

**Issue 3:**

For p13 sorting dialog, when all paramaters are displayed, these add buttons should be disabled or disappeared:

https://github.com/SAP/fundamental-ngx/assets/22842279/c363090f-7b6a-462a-a524-0b012440621d

**Issue 4:**

Filter style looks not aligned correctly:

<img width="272" alt="Screenshot 2023-07-11 at 10 13 07 PM" src="https://github.com/SAP/fundamental-ngx/assets/22842279/d7b36f95-26da-4248-9e96-7373836ba1ae">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest or previous

#### If this is a bug, please provide steps for reproducing it.

Please refer to the link below:

#### Please provide relevant source code if applicable.

https://ui5.sap.com//#/entity/sap.ui.comp.smarttable.SmartTable

**Comment by fkolar** [comment]
@CSENoni, instead of providing a link to SAPUI5, which is good, we should always have a link to the original UX specs to understand how this should work:

**Issue 1**
 * Here you try to say when we hide all the columns it does not make sense to keep rendering the rows ?  Which kind of makes sense.

**Issue 2**
 * If **Issue1** is fixed, then it does not make much sense to have checkAll  - as there is nothing to check

**Issue 3**
 * You want to table (dialog - sort) to be more intelligent right? When you end up having all columns in there it does not make sense to allow user to add additional ones and duplicate. you can't set Name to be sorted ASC and DESC at the same time? Is this what you meant? 
 
**Issue 4** 
 - Makes sense.

**Comment by CSENoni** [comment]
@fkolar I will take note for next time (if any)

**Issue 1:** Yes. 
**Issue 2:** I think it depends much on user. In our application, old table (Ariba core UI table) has it disabled when there is no data visible. And our QA also get confused when testing new tables in this scenario.
**Issue 3:** Originally I just thought that when all columns are set there, we should not add a new dropdown. Because even when we can add a new dropdown here, there is no items inside.

**Comment by CSENoni** [comment]
1,3,4 are fixed.
2 is only working if module is imported at root. Not working in child module (checkbox is not disabled). Also I found another issue. We will raise another issue, but feel free to correct and close if I do something wrong. Thanks!
