### ISSUE TITLE
[Sourcing] Single selection does not clear selected value in pageScrolling

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10130]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In table with `pageScrolling` = true, if we have a value already selected in any other page (not current page) and we select a new value in current page, it does not deselect a the old value:

https://github.com/SAP/fundamental-ngx/assets/22842279/ef7a7a0b-31a7-4a8e-ad2b-f0c1fc05b62a

Also the event emitter does not trigger the removed value. It can be worked around, but it should work correctly even with non-visible page(s).

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

Have a table in single mode with already selected row in page which is not first page then select a new row in a current page.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-s5ofpz?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,package.json

**Comment by CSENoni** [comment]
Also for multiple selection, somewhat similar when we have some rows are already selected but not visible since it is in different page, having new row(s) checked will not emit in `added` array.

**Comment by mikerodonnell89** [comment]
I do not think there is a way for the library to handle this. This is happening because the client has not yet loaded the row that is marked as selected. You will need to implement logic that deselects the item on your datasource since it is marked as selected there. In single-select mode, when a row is loaded from the backend, if your datasource is telling the table that an item is selected, it will render that item as selected. While the table component has logic to prevent the user from selecting multiple rows on a single-selection table, this needs to be enforced by the backend as well

looking for input from my coworkers that have also worked on this component @SAP/fundamental-denoland-team

**Comment by CSENoni** [comment]
It makes sense @mikerodonnell89. This is something we can handle by ourselves. I just looked for more convenient way. This is not urgent issue. Please help us with other issues especially with virtualScroll one. Thanks
