### ISSUE TITLE
padding on the right of a spot illustration in a dialog

### ISSUE THREAD

**Issue by I539321** [SAP/fundamental-ngx#10133]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
There seems to be some padding on the right of a spot illustration in the right-side of a dialog. Hopefully this isn't a bug on our code, please confirm and let us know.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
I guess it happens on version 0.42.0 of the Fundamental library, and Angular 15.

#### If this is a bug, please provide steps for reproducing it.
Create a dialog and add a spot illustration to it.

#### Is there anything else we should know?
Attaching a screenshot of this.

<img width="1487" alt="Screenshot 2023-07-06 at 13 45 47" src="https://github.com/SAP/fundamental-ngx/assets/101869667/83fec903-9194-40f2-a2a4-f32b265f52a0">

**Comment by InnaAtanasova** [comment]
Hi @I539321 the component doesn't come with a margin right. The spacing on the right most probably happens because the Illustrated message in spot variation has a fixed width (and height). The Dialog also has some width, bigger than that of the Illustrated messages and that's why you get this spacing. Hope this helps.
