### ISSUE TITLE
[Sourcing][Sept] Perf issue with `datepicker` in `virtualScroll`

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10242]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

When using `datepicker` with `virtualScroll`, after scrolling pass the default `renderAhead` (40 I believe), there is performance issue when it causes whitespace even though I do not scroll really fast here and scrollbar cannot keep up to the position I scroll to.

https://github.com/SAP/fundamental-ngx/assets/22842279/13bb5a4e-ce35-4fa1-93fe-4aacf1db2d08

Remove `datepicker` and add another component like `fdp-combobox` which I have in the link, performance can be clearly observed.

https://github.com/SAP/fundamental-ngx/assets/22842279/5624b659-840e-49f6-ae5d-f83259ccfb6c

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.43.0

#### If this is a bug, please provide steps for reproducing it.

- Create a platform table with a lot of data (maybe around 500 or more).
- Have a `datepicker` component.
- Scroll pass a default `renderAhead`
- Keep scrolling up and down and issue can be seen.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-9jp2kz-fe9jqa?file=package.json,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

**Comment by CSENoni** [comment]
Source code link is updated. Not sure why it was removed.

**Comment by droshev** [comment]
@N1XUS we would need to downport this to `ng15`. We can discuss internally how to tackle this.

**Comment by N1XUS** [comment]
Hello @CSENoni. Thank you for your ticket.
After the investigation of this issue, the result is following:
Virtual scroll tries to utilize already rendered rows and their contents, and pass new row data to it to remove the bottlenecks with destroying previous rows and inner components and initializing new ones.
This approach has some advantages comparing with standard "render all at once":
- Instead of having 1000+ component instances living in browser, Virtual scroll reduces this amount to a 100+ value (10x less instances to keep track by the browser);
- More smooth frame-rate due to less elements to render and calculate it's styling.

Yet, virtual scroll has some pitfalls too, mainly how it renders the content:
- Since components are being updated on scroll, when user scrolls, components receive new data, which may cause inner calculations inside the component that may lead to performance degradation. The difference with the standard "render all at once" is that in standard approach the lag will happen only once when the data being loaded, yet, it may take a long time to process whole data and render it appropriately, and for the Virtual Scroll approach this calculation will happen almost everytime user scrolls.

Taking all of the items into consideration, I would suggest checking the possibility to render simpler row content (text for example), and on the user demand switch to the more complex one (date picker for example). This way, performance will be great during simple row content rendering, and when it's needed, it will switch to a complex one. And after user makes some changes it will go back to the simple state, preserving the performance.

**Comment by CSENoni** [comment]
Hi @N1XUS, thank you for the clarification. For the last point, we came up with something similar to get over this issue when user could access the component in different way instead of having all rendered in cell when scrolling. This way for sure will improve perf but also requires more actions from users to access these components. We also proposed this idea to one of our big customers and they did not like it especially when the table haves a lot of these inline components.

I understand that when we use `virtualScroll`, the experience will be different from "render all at once" when scrolling pass `renderAhead` will have some delays even with just simple text. However, the delay from the `datepicker` in this issue is problematic especially there is nothing to tell user the next rows are "loading" (may be this should be enhancement but different issue). It would be great if this component can have some perf improvements (not sure about the complexity here so I don't expect it like `fdp-combobox`).

**Comment by droshev** [comment]
@CSENoni Can you provide more context to the scenario the user will do? what is the task she will be performing? Based on that we can think of a solution.

**Comment by CSENoni** [comment]
The perf is improved a lot with `0.43.5`. Thanks!

@droshev For the scenario, this is the current table they are using with pagination:
![Screenshot 2023-08-17 at 2 02 17 PM](https://github.com/SAP/fundamental-ngx/assets/22842279/1945fa8d-8523-4591-9a4f-429e7420fe5a)
As you can see here, the last 4 columns we have different types of component which includes `datepicker`, there is another table above this which they can use to add similar column. So depending user's desire, the number of columns in this table could go up to a significant numbers. And this table should also support up to 700 rows. Our user workflow is to see all these components and can add/remove values as they want.

**Comment by CSENoni** [comment]
Hi @N1XUS, through your fix, I just noticed that you put extra condition in popover body so that it loaded when we opened it. I tried a few tests with popover and saw that even when we didn't open popover, the content inside it was still loaded. Is it a bug from `fd-popover`?

**Comment by droshev** [comment]
@CSENoni if you have a requirement to render a lot of columns, I would advise you to involve some design experts before even committing to deliver that.

**Comment by CSENoni** [comment]
@droshev sure, that is valid point. Thank you for taking on the issues and suggestion.
