### ISSUE TITLE
[P3][Sourcing][Accessibility][Multi input tokens]Values are not noticeable even when read linearly with the screen reader, because they are in an unlabeled selection list (role=listbox).

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10293]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Values are not noticeable even when read linearly with the screen reader, because they are in an unlabeled selection list (role=listbox).

#### If this is a bug, please provide steps for reproducing it.
Values are not noticeable even when read linearly with the screen reader, because they are in an unlabeled selection list (role=listbox).
When reading linearly with the screen reader's virtual cursor, JAWS outputs a selection list before the empty input field, but it is unclear how the selection list relates to the input field, and the values of the selection list are also not output because output is only made in forms mode.
tested on multi input mobile mode

#### Is there anything else we should know?
reported by customer

**Comment by mikerodonnell89** [comment]
I think this is irrelevant because anyone developing a mobile application will not have users navigating the site via JAWS. And @nikolay-kolarov I am a bit confused because it looks to me like ui5 is doing the same thing we are - the tokenizer div has role="listbox", and if you start typing to open the dropdown, the dropdown list will have role="listbox" simultaneously as well. So I think we will want to close this for now but please ping me directly if I am misunderstanding something

**Comment by nikolay-kolarov** [comment]
Hi @mikerodonnell89,

It is not about the two different listboxes (one for the tokenizer and one for the suggestions).
I remember when I tested there were two elements with role listbox around the tokenizer. This is not the case now, so it is either fixed or I made a mistake when I checked it.

Nevertheless, the listbox is still unlabelled, so I encourage you to add a label to it. In Ui5 it is done via aria-labelledby like this:

![image](https://github.com/SAP/fundamental-ngx/assets/17043004/a10b6643-be1b-46cf-9ba7-3ce538867eaf)

Best Regards,
Nikolay
