### ISSUE TITLE
[Sourcing][Accessibility][Multi input tokens] After deleting a list entry, the focus is placed in the input field instead of remaining in the list

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10296]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
After deleting a list entry, the focus is placed in the input field instead of last token remaining in the list

#### If this is a bug, please provide steps for reproducing it.
After deleting a list entry, the focus is placed in the input field instead of remaining in the list
Tested in multi input mobile mode example 
1) delete a token 
2) observe the focus moves to search field / input typing area

#### Is there anything else we should know?
reported by customer

**Comment by droshev** [comment]
![multi-input](https://github.com/SAP/fundamental-ngx/assets/4380815/686959c8-11a1-4611-b842-f11734a52686)
not reproducible

**Comment by I543348** [comment]
Needs to be documented for customer

**Comment by I543348** [comment]
ATL Re-verification needed

**Comment by sagar7259** [comment]
Hello,

There are 2 behaviours and 2 observations here:

1)  Deleting a token using Backspace key: Focus remains on the previous token which is the right behavior.
2)  Deleting a token using Delete key: The focus is placed on the input field instead of last token remaining in the list.

Has there are 2 behaviours either this needs to be fixed or this needs to be documented correctly to the customers about the usage of different keys and behaviour on activating them.

@rvamudha please reopen this ticket.

Regards,
Sagar

**Comment by droshev** [comment]
https://github.com/SAP/fundamental-ngx/issues/10296#issuecomment-1682842598
