### ISSUE TITLE
[P3.2][Sourcing][Accessibility][ATL Testing][Table]: Column 1 , Column 1 of 3 , is read twice in table

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10617]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Column 1 , Column 1 of 3 , is read twice in table

<img width="734" alt="access8" src="https://github.com/SAP/fundamental-ngx/assets/88182358/80020af3-af2d-41ab-8d47-f80ab9905036">

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
platform multi-select tree Table

**Comment by nikolay-kolarov** [comment]
Hi Team,

In this case the screen reader announces the rows and columns information.
So I think you can remove the additional announcement about the Row and Column done with this live region:
![image](https://github.com/SAP/fundamental-ngx/assets/17043004/c2f3b87e-b0d2-4bc0-921d-c6e36e1a93cc)

PS: If this is used in a shared manned for other table variants as well, please check if it is still needed there before removing.

@droshev - FYI

Best Regards,
Nikolay

**Comment by sagar7259** [comment]
Hi Team,

After discussion with seniors testers from my team, we conclude this has a correct behaviour and not an issue.

Because on changing the row/Column, first this change is being read separately and follow by the cell placement and this could help screen reader users with better understanding of the change is behaviour of the table and also ease the navigation within the table.
Hence this ticket can be closed.

Thanks and Regards,
Sagar

**Comment by skaquib123** [comment]
Thanks @sagar7259 for your Input. @I543348 Hope It's clear now.  I am closing this issue.
