### ISSUE TITLE
[P3.1][Sourcing][Accessibility][ATL testing][Table]: Search icon button / sync button labels are not read in JAWS VPC mode on

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10614]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When JAWS VPC mode is on , and focus is on search icon button or sync icon button , then JAWS has to read the label for these both buttons accordingly

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) Turn on JAWS VPC Mode on
2) Move the focus using keyboard to search field and next to search icon
3) Notice that if search icon label is read then sync icon button label is not read and vice versa.

#### Please provide relevant source code (if applicable).
replicable on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic 

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes this is raised by ATL team itself

**Comment by nikolay-kolarov** [comment]
Hi Team,

Those buttons are expected to be hidden on desktop by the screen reader (with aria-hidden and with tabindex="-1" e.g. <div role="button" aria-hidden="true" tabindex="-1" ..... >.
So, it is ok that they are not read with VPC, but they also do not have to be focusable (which is the case in the current implementation).
On mobile, you need to remove the aria-hidden attribute (because they can be reached by explore by touch and needs to be announced).

Best regards,
Nikolay

**Comment by mikerodonnell89** [comment]
fixed by https://github.com/SAP/fundamental-ngx/pull/10881/files
