### ISSUE TITLE
docs: anchor tags are blue in unwanted areas

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#1062]
#### Is this a bug, enhancement, or feature request?
Bug

Some recent PR (not sure which) makes anchor tags blue, see combobox on latest.

**Comment by JKMarkowski** [comment]
Hi @MattL75 

It's caused by https://github.com/SAP/fundamental-ngx/pull/1005 PR. We can solve this issue in both ways. 
1. Change examples, by putting put `fd-menu-item` into `anchor` tag instead of `li`
2. Revert detecting if there is any anchor child and put `fd-menu__item` class on it, instead of putting it on host.
