### ISSUE TITLE
[P3.2][Sourcing][Accessibility][ATL testing] Unnecessary chrome tab name is read on focus of dialog

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10698]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
On open of value help dialog https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/value-help-dialog, when the focus is at the first interactive element inside dialog, the browser tab name is being read unnecessarily.

Expectation: The browser's tab name should not be read when focus is inside value help dialog as its out of context for users

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
core/ platform: 0.43.9

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) open link https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/value-help-dialog
2) access any example
3) turn on JAWS
4) trigger the value help button
5) hit enter to open dialog
6) notice the jaws speech history reading "Fundamental Library for Angular -Google chrome dialog"
![MicrosoftTeams-image (5)](https://github.com/SAP/fundamental-ngx/assets/88182358/7dcf405d-0213-4e63-b492-761071b16912)

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes as it is reported by ATL team. the issue is discussed with experts and reported here.

**Comment by droshev** [comment]
@I543348 This is nothing to do with the application. The documentation is not meant to be fully validated against your expectation

**Comment by I543348** [comment]
Hi @droshev , Its not only happening in NGX website, but also in guided sourcing.
We would not raise any such issues which are not happening in our Guided sourcing application.
Could you pls reopen? 
This issue is tested and reported in Guided sourcing first by ATL team , after cross checking the same in NGX website , I have reported the issue.

Thanks.
cc: @sagar7259, @nikolay-kolarov

**Comment by droshev** [comment]
@I543348 you need to inspect and see where that string is coming from.

**Comment by sagar7259** [comment]
Hi Team,

When i analyzed this using forms mode and reading mode of JAWS, I got different results.

In reading mode:
The parent screen title "Fundamental library for angular - google chrome" is being read as an additional information. along with the dialog title.

![image](https://github.com/SAP/fundamental-ngx/assets/143692208/bc4c0801-9a3e-4870-9513-d5fa05167616)

In forms mode:
There is no dialog header or the parent screen title as additional information is read on opening the value help.
Here just the first UI within the dialog which has the keyboard focus is being read.
![image](https://github.com/SAP/fundamental-ngx/assets/143692208/d3e9c40d-050f-41cf-9552-b955fe50ff12)

And this issue is not only related to the value help dialog, instead its common for any dialog of any NGX component.
Kindly look into it.

CC: @I543348 
Regards,
Sagar

**Comment by droshev** [comment]
@I543348 this is Fundamental Library documentation page.

**Comment by nikolay-kolarov** [comment]
Hi Colleagues,

In the current example the dialog does not have an aria-labelledby attribute pointing to the title and I think that if it this is added, then the announcement of the page title will be gone (I tried it with another example).

@droshev - Is this supposed to be done internally for the Value Help Dialog or it needs to be set explicitly via API?

Thanks,
Nikolay

**Comment by I543348** [comment]
Hi @droshev , I couldnt find any string that starts from browser tab name when i inspect ,
I think the fact that screenreader is able to read dynamic browser tab name , it wont be hardcoded as such anywhere.
This might be happening somewhere from programatically due to some id reference.

Could you pls suggest what else can be done?
Thanks.
cc: @nikolay-kolarov , @sagar7259
