### ISSUE TITLE
[P2][Sourcing][Tree table]: Need an html property indicating row index in sequence for parent and child nodes in sequence

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10900]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Describe your proposal.
This is an enhancement for all tr tags in a tree table.
Currently there is no html property exposed when we inspect table row (parent or child) in a tree table for indicating row index.
Hence, pls generate and expose a property called row-id which is generated in seqeuence for parent and child rows.

For eg:
We can do something like below , say we have a data in row 2 which is a parent node with 3 children.
so parent row 2 will have row-id = "row_002"
and followed by its all 3 children will have row id something like 
child 1 -> row-id = "row_0021"
child 2 -> row-id = "row_0022"
child 3 -> row-id = "row_0023"

This will be helpful for bringing back focus on particular element after lazy loading the child rows after API call.
Currently we do not have any proper or generic sequence in which we can apply focus login from application side.

#### Can you handle that on the application side
No, since row ids are not generated and exposed in html for "tr" tags

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core / platform: 0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
enhancement request

**Comment by I543348** [comment]
we discussed with @mikerodonnell89  today and explained the use case that we have.
We shall wait further to hear from Mike on this issue.
Thanks.

**Comment by mikerodonnell89** [comment]
Each cell in the table has the `aria-rowindex` attribute which, along with the expand/collapse state of the table, could be used to preserve focus after a refresh. However I could see this being expensive due to having to get the state of the table and check the focus state of potentially thousands of cells before reloading the table. I'm confused as to how assigning a generated ID to each cell would help with this problem, you'd still have to iterate over each element until you found the focused one before reloading the table. But I think what we can do is expose a (cellFocused) event from the table component that would allow the developer to more easily handle focus issues after page refresh, similar to how row expansion is handled already on the [table preserving state example here](https://fundamental-ngx.netlify.app/#/platform/table/preserved-state)

Thoughts?

**Comment by KaptaanBarbosa** [comment]
Hi @mikerodonnell89 
1.By the id which will be constant and will be calculated on the basis of row position inside the tree we will be able to grasp any element directly with elementRef.nativeElement.getElementById(<clickedrowID>).

2.So with the exposed event will the callback function gives us the clicked element or will directly focus if any of this case is happening this idea should be good for us.
