### ISSUE TITLE
[P1][Sourcing][Regression] Table : Table is not rendering rows after updating datasource

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#11057]
#### Is this a bug, enhancement, or feature request?
Bug - Regression

#### Describe your proposal.
After rebinding the datasource, table in UI shows no data found.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Fundamental Library - v0.43.18
Angular - v15

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Use stackblitz - [click here](https://stackblitz.com/edit/angular-9qxxca-mpyvnk?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,src%2Fapp%2Fapp.module.ts)
2. Click on test data button
3. Notice that table becomes empty in the UI even though datasource is having data.

https://github.com/SAP/fundamental-ngx/assets/71999626/28bfedce-d7ea-45ea-a2fe-f88642d21bc9

#### Please provide relevant source code (if applicable).
Refer above stackblitz link.

#### Is there anything else we should know?
May be the fix for this issue https://github.com/SAP/fundamental-ngx/issues/11002 is causing this regression.

**Comment by I543348** [comment]
Hi team , we have many such issues where we need to refresh the datatable source, for example after adding a new row in a table that is depending on an API call , getting input from parent component and feeding to child component that has table and so on..
hence this is a big regression for sourcing tables. pls help.
Thanks much

**Comment by I543348** [comment]
Hi @N1XUS , This issue is working fine however the issue https://github.com/SAP/fundamental-ngx/issues/11002 is again replicable , pls find the stackblitz [link](https://stackblitz.com/edit/angular-9qxxca-nwzrms?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) 

Here pls follow below steps to reproduce the issue
1) Use above stackbliz
2) Click on filter results button
3) notice table has only one record 
4) Now click on undo filter table button where we are again binding all 60 rows in table
5) Notice that only 2nd page records starting from 30 to 59 are getting binded in the table.

The table is not showing first page records at all.
Please help as this was a customer issue which was fixed.
Thanks.

**Comment by I543348** [comment]
attaching recording for reference from stackblitz

https://github.com/SAP/fundamental-ngx/assets/88182358/069b7449-5024-486d-981c-4a933425944a

**Comment by I543348** [comment]
Hi @N1XUS , Could you please confirm once the new version is available for the reopened issue?
Thanks.
