### ISSUE TITLE
[P2][Sourcing]Not able to get dynamically selected row data correctly in NGX Table

### ISSUE THREAD

**Issue by KaptaanBarbosa** [SAP/fundamental-ngx#11130]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Hierarchical table in NGX( <fdp-table/> ) does not provide way to check which all rows are selected if we want to  perform some operations on that data

#### Can you handle that on the application side
Have tried not happening via onRowSelectionChange method

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 15  NGX 0.43.21

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Issue is intermittent if you want get the selcted row data from table to show it in some other componnet it is not happening since if you select parent sometimes it selects child also and sometimes not 

#### Did you check the documentation and the API?
yeah didnot get much info on this issue 

#### Did you search for similar issues?
yeah no luck !

**Comment by KaptaanBarbosa** [comment]
We have tried using  rowSelectionChange callback but here if you select and unselect check box once or twice in the event parameter event.selection it takes children of of unselected items also

**Comment by mikerodonnell89** [comment]
I'm a bit confused as to what this issue is asking for. Are you looking for a function on the table component that returns the selected rows from the table? The client should be handling the selection state of each item by catching the selection change event and updating the datasource as necessary. So any other component should be able to see if an item is selected by checking that same datasource

**Comment by KaptaanBarbosa** [comment]
> I'm a bit confused as to what this issue is asking for. Are you looking for a function on the table component that returns the selected rows from the table? The client should be handling the selection state of each item by catching the selection change event and updating the datasource as necessary. So any other component should be able to see if an item is selection by checking that same datasource

That event  object have selected property coming from NGX which is having wrong data in some cases for example when u select and unselect the row and if it possess child object event.selection property have child also as part of it

**Comment by mikerodonnell89** [comment]
@KaptaanBarbosa it is still unclear what exactly the problem is and what you are hoping to see. The `selection` property of that event returns every selected option in the datasource, including children. All of this appears to be working fine in this example: https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#tree

If you could provide to us a stackblitz example and a list of steps to recreate the issue that would be helpful

**Comment by KaptaanBarbosa** [comment]
Thanks Mike closing the ticket since issue we cant see in any other example for now but only in our application
