### ISSUE TITLE
[P2][Sourcing][Multi input]: "open" property not working from 2nd time onwards for multi-input

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11229]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When using [open]=true or false for closing or opening popover in multi-input , the open property doesnt work properly from 2nd time onwards.
It works only for first time during select or unselect values from popover.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15 
core / platform: 0.43.24

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) use the [link](https://stackblitz.com/edit/angular-9qxxca-a1uumb?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json)
2) The popover will open by default
3) try to select some value or de select 
4) notice that the popover closes
5) now open popover and try to select or de select some value
6) notice that in method selectedChange, even though we are setting open to false manually , the popover do not get closed.

https://github.com/SAP/fundamental-ngx/assets/88182358/9a361808-555e-4347-83ad-d0b01cc953e6

Pls help to fix this issue as its blocking the feature.

#### Please provide relevant source code (if applicable).
pls refer above link

#### Please provide stackblitz example(s).
pls refer above link

**Comment by N1XUS** [comment]
@I543348 You need to use two-way binding:
https://stackblitz.com/edit/angular-9qxxca-gapjuj?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,src%2Fapp%2Fapp.module.ts

The issue is with detecting the changes for the input value. In your original example, isOpenPopover never changed from false to true when user opened the popover, thus, no changes were detected to pass to the fd-multi-input component.
