### ISSUE TITLE
[P1][Sourcing]Expand all in a fdp table with advance technique is not expanding all the nodes till utmost leave node

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11428]
#### Is this a bug, enhancement, or feature request?
Yes, it  a bug

#### Describe your proposal.
We should have all the nodes to be expanded when expand all it clicked.

#### Can you handle that on the application side
No, this has to be handled from NGX when infinite scrolling is implemented in fdp table.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15 and NGX 0.43.26

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
step 1: create table with level 5 items and load only first page data.
step 2: Do expand all and observe only first level of children. 

Expectation is to expand till all the leaf nodes.

**Comment by mikerodonnell89** [comment]
I do not think this is possible from the library side, because on the application side, the data will often be fetched from an API when a new "page" is scrolled to. And then, further API calls may be necessary to get data for the children of the to-be-expanded parent nodes. What you can do from the application side is listen to the `allRowsExpanded` event in your component and store that locally, then whenever you fetch new data on a new page scroll, you can also do whatever you need to programmatically expand the parent nodes.

**Comment by sahanaN123** [comment]
we are actually able to expand the data that we get after API call. But the concern now we have is with the data already been sent to NGX.
