### ISSUE TITLE
[P1][Sourcing] Not able to view complete data at the last line when Scrolling to the bottom of  fdp-table

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11449]
#### Is this a bug, enhancement, or feature request?
This is a BUG

#### Describe your proposal.
We should be able to view last row data as well.

#### Can you handle that on the application side
No we cannot handle, as its an issue replicable on NGX site as well.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
NGX 0.43.27

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
we are using fdp-table and here is the recording of the replicable on stackblitz

https://github.com/SAP/fundamental-ngx/assets/110370099/bae9a306-221d-43a7-bf99-0893fea1ba8c

#### Please provide stackblitz example(s).
[click here](https://stackblitz.com/edit/angular-mexm86?file=src%2Fapp%2Fadvanced-scrolling-example.component.html)

**Comment by Sayandeep-123** [comment]
Stackblitz link  - [click here](https://stackblitz.com/edit/angular-mexm86?file=src%2Fapp%2Fadvanced-scrolling-example.component.html)

**Comment by N1XUS** [comment]
@sahanaN123 Virtual scroll is not designed to work with the rows that have dynamic height. You could use `[rowHeight]` input property to set a custom row height, but from what I see, some of your rows are 56px, some 104, some 100. So for this particular case removing virtual scroll should fix the issue. Closing this task since we do not support having dynamic heights for vistually scrolled rows.

Here's an example of custom row height with virtual scroll for reference: https://stackblitz.com/edit/angular-mexm86-ne9hnk?file=src%2Fapp%2Fadvanced-scrolling-example.component.html
