### ISSUE TITLE
[P2] fdp-table scrolling updates

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#11491]
The table scrolling behavior must be reworked to more closely match that of the ui5 grid table: https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Basic

Notable differences are:

- All rows must have a matching fixed height. The table cannot display partial rows.
- In UI5, when a scroll event is performed, rather than scrolling the table container by 1px as is typical when performing a scroll, the scroll event is caught and prevented, the `<tr>` elements are fixed in place, and the data from each row is moved up or down to the previous or next row(s) depending on the scroll direction. This provides a snappier feel from a UX perspective and also eliminates some edge case problems such as #11443 because there is no way to have the table only showing a partial row (also due to the fixed height of rows)
- If a cell is focused, and the user scrolls, the focused cell position stays the same, effectively making a different cell focused:

https://github.com/SAP/fundamental-ngx/assets/2471874/6495c774-6840-4d3c-b8c9-2cba0f6b799b

This is tricky to explain, because from the developer's perspective, it's the same `<td>` that is focused. But from the user's perspective, the focus has changed cells.

- If a table cell has some child element that is actionable by the user such as a text input, a scroll event on the table should be considered as a "submit" action by the user

This will be released as a significant breaking change to the existing virtual scrolling functionality of the platform table. If these changes are downported to a previous version of fundamental-ngx, it will need to be released as a separate feature, so as to not break the existing functionality for users on fundamental-ngx using ng15 etc

**Comment by CSENoni** [comment]
I used to raise this issue before: https://github.com/SAP/fundamental-ngx/issues/10036. In UI5, assuming the table is using `virtualScroll`: https://ui5.sap.com//#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Basic

https://github.com/SAP/fundamental-ngx/assets/22842279/bb432ec7-5424-4ffd-bd4a-851cf75c954d

It looks like focus is still moving along and but sticks to the same cell when scrolling but not jumping from cell to cell. 

- One note about this behavior is that it is not consistent because for platform table, this focus scrolling behavior really "kicks in" when we scroll pass some first number of table rows. If you put the focus on any cell of the first row of table (for example, Laptops 0 from your record) and scroll, the focus will not move along.

- Another note is that if you have any **inline component** in platform table and it is focused, scrolling will keep focus staying on that inline component.

https://github.com/SAP/fundamental-ngx/assets/22842279/f11b1f95-7152-419d-b558-ed5c89e83ade

- While in UI5, it will switch the focus onto cell:

https://github.com/SAP/fundamental-ngx/assets/22842279/27f84e80-28ca-4987-a846-0a422e237127

- Final note is about event listener for those scrolling behavior in current platform table with `virtualScroll`, virtually it looks like focus is moved to another element but those `focus` or `onBlur` emitters is not triggered when I tested it with native element. I haven't tested these emitters in UI5 table when they switched focus back to cell from component while scrolling.

I just want to give more context on this when you address this issue.

**Comment by mikerodonnell89** [comment]
@CSENoni thank you for this comment. I noticed that for ui5 web components, the focused cell does not follow the user's scroll, like it does in your video for ui5 table (not the web component version). Also in your video you'll note that scrolling snaps to each element - the user cannot scroll the table such that only part of a row is visible. How we handle the focused cell changing is dependent on the scrolling behavior, by pixel or by entire row. I've reached out to the designers asking which functionality is preferred

**Comment by mikerodonnell89** [comment]
After speaking with the designers, we've learned that the focus should remain in the same position, changing cells, as the user scrolls. However we should be scrolling entire rows with one movement of the mousewheel such that partial rows are never displayed.

**Comment by mikerodonnell89** [comment]
Also, moving focus from the input to the wrapper cell on scroll should not happen

**Comment by droshev** [comment]
@mikerodonnell89 what happened to that issue?

**Comment by mikerodonnell89** [comment]
Deleted some comments to consolidate the needed changes into the original post

**Comment by mikerodonnell89** [comment]
Leaving this open for now, until when we decide to port the changes from the ng-15-downport branch to main

**Comment by droshev** [comment]
not requested for now
