### ISSUE TITLE
[Sourcing][P2][Value help dialog platform] Even if we change the label of "Selected items and conditions" is being read on focus of token input

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#12017]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
We have a custom label for token field and still screenreader is reading default label "selected items and conditions" when focus is on input field of token input holder.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
platform: 0.43.34

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

1) Change the token field name as shown in below screenshot
2) Open JAWS or voiceover
3) Move the focus to input field  as shown in below screenshot and observe the reading.

Expectation is: Screenreader should read "Selected suppliers (6)" in this case.
<img width="956" alt="Screenshot 2024-06-19 at 4 43 52 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/d76e4730-e378-498a-acde-9f48586471dc">

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/value-help-dialog#token-display

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Reported by ATL team after accessibility test

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
Need to provide a conditional template to override the provided `platformVHD.selectedAndConditionLabel`

**Comment by sagar7259** [comment]
Hello Colleagues,

1) On forward navigation the label 'Selected suppliers' is read, but with backward navigation this issue still exists.  Once user navigate backward from 'Close' button to top, here only "Edit blank type is text" is read and label "selected suppliers" is not read.

Either on forward/backward navigation the speech results should be same and should not vary.

2) Even though if keyboard focus is provided for the whole input field, the focus within the input on the blank space is still visible. This results in double keyboard focus which should be avoided.

All UI elements should receive only single keyboard focus and multiple focuses should be avoided.

please reopen this ticket as the issue is still not fixed.

Regards,
Sagar

**Comment by I543348** [comment]
Thanks @sagar7259 for testing 
Hi @mikerodonnell89 , 
The screenreader is not reading the label when we are doing "SHIFT + TAB" backward tabbing over the input field.
Can you please check and reopen ?

Thanks much

**Comment by droshev** [comment]
@mikerodonnell89 Can you check that?

**Comment by mikerodonnell89** [comment]
It's the same label whether or not i am tabbing forwards or backwards:
https://github.com/user-attachments/assets/c9bb6867-9113-4626-8ffc-31803f9cac01

Are you changing the text by using fdPatchLanguage on `platformVHD.selectedAndConditionLabel` ?
