### ISSUE TITLE
closeButtonCallback not working for messageBox

### ISSUE THREAD

**Issue by Nyoote** [SAP/fundamental-ngx#12072]
#### Is this a bug, enhancement, or feature request?
Bug 

#### Describe your proposal.

I would like to implement a button on the upper-hand-right-side of the messageBox component to close it. I first checked in Dialog > Object Based Dialog (as an example to reproduce onto messageBox component), and it worked thanks to `closeButtonCallback`.

Then I checked the code for the messageBox and `closeButtonCallback` is also available but doesnt seems to work.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular : 17.3.0
Fundamental : v0.50.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Fundamental documentation > MessageBox > Semantic Types

#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
Yes

**Comment by InnaAtanasova** [comment]
Hi @Nyoote ,
the closeButtonCallback is not working because, by design, the message box component is not supposed to have a close (dismiss) button. You can still find it, because internally Message Box is extending the Dialog functionality. 
For customization, although not recommended, we provide an option that you can find in the last example of our documentation (Complex template) https://fundamental-ngx.netlify.app/#/core/message-box

Here's an example of how you can achieve a dismiss button in your header:

![Screenshot 2024-07-04 at 2 34 09 PM](https://github.com/SAP/fundamental-ngx/assets/39598672/1f5a2d44-4180-42dc-a259-4c06fd16911c)


The only issue is that when types are applied, the button icon also receives the type color:

![Screenshot 2024-07-04 at 2 40 21 PM](https://github.com/SAP/fundamental-ngx/assets/39598672/54f22874-a1f8-41d7-b6fa-1009b1196dda)

I will fix this and then you should be able to use it with no issues. 
Could you please try this approach and let me know if it works for you and if you face any issues. Thank you!

**Comment by InnaAtanasova** [comment]
I added a solution for the button color and extra spacing in fund-styles: https://github.com/SAP/fundamental-styles/pull/5477

**Comment by Nyoote** [comment]
Hello, thank you for your quick reply and for taking the time to reply. I'll explain to the product why it's not recommended, but I'll keep this solution in the back of my mind.
Thank you !
