### ISSUE TITLE
[BUG] Performance issues for Table fundamental-ngx component

### ISSUE THREAD

**Issue by karolgromacki** [SAP/fundamental-ngx#12263]
Is this a bug, enhancement, or feature request?
Bug

Describe your proposal.
In the [attached example](https://stackblitz.com/edit/sjxljz-u5wgpm), the performance of the table decreases more and more after loading over 700 elements, especially when opening the dialog with the action button. It takes several seconds to load more elements or to open and close the dialog.

Can you handle that on the application side
No

Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Fundamental: v0.51
Angular: 18.0.3

If this is a bug, please provide steps for reproducing it; the exact components you are using;

Steps to reproduce:

1. Open attached example of table.
3. Click the growing button until over 900 elements are loaded.
4. Click the delete icon on any of the items to open dialog.
5. Observe how long it takes to open the dialog.

Expected behavior: 
Items load faster when the growing button is used, and the dialogs open immediately with a large number of items in the table.

Please provide stackblitz example(s).
https://stackblitz.com/edit/sjxljz-u5wgpm

Did you check the documentation and the API?
Yes

Did you search for similar issues?
Yes

**Comment by mikerodonnell89** [comment]
On our end - we need to make `virtualScroll` cooperate with `showGrowingButton`, it seems buggy at the moment

**Comment by mikerodonnell89** [comment]
@karolgromacki Would it be possible for you to use the `[virtualScroll]` and `[bodyHeight]` inputs on the `fdp-table`? And, going off your example, you'd want to remove `cdkScrollable` from the parent `<fd-dynamic-page-content>`. You'll see significant performance improvements this way. However, virtualScrolling does not cooperate with `[fdpTableColumnResponsive]` and "popping" columns. From your example, the popping columns will need to be set to `hidden` rather than `popping` for small screens, which I know is unfortunate. We can look in to what needs to be done to get popping columns cooperating with virtual scroll. Here's a link containing my changes to your stackblitz that demonstrate all I've suggested here, hope it is helpful: https://stackblitz.com/edit/sjxljz-pwjwqr?file=src%2Fapp%2Ftable-custom-pagination-example.component.html
