### ISSUE TITLE
Change Detection issue when performing a http request within a Dialog

### ISSUE THREAD

**Issue by pauljanns** [SAP/fundamental-ngx#12262]
#### Is this a bug, enhancement, or feature request?
Bug

When doing a http request in a component-based dialog the result is not shown until I manually trigger a change detection cycle (e.g. through a click). I was only able to reproduce this within a Dialog. The component does use the default ChangeDetectionStrategy. I've attached a simple stackblitz to show the issue. As a workaround I could trigger the change detection with .detectChanges(), but for me this feels odd. 

#### Can you handle that on the application side
I don't think so

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular v18 (17 doesn't seem to be affected)
fundamentals 0.51.2

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/pltejz?file=package.json

#### Did you check the documentation and the API?
yes

#### Did you search for similar issues?
yes

**Comment by droshev** [comment]
@alexhristov14 do you think you can check this out?

**Comment by alexhristov14** [comment]
@pauljanns Just to be clear about your stackblitz example, you want the data from the http request to directly render on the dialog without the need of the 'get' button.

**Comment by pauljanns** [comment]
@alexhristov14 yes the issue is that I need to manually click anywhere on the screen (or trigger a CD cycle a different way) to show the result of the http request. This was different before we updated to angular version 18

**Comment by alexhristov14** [comment]
@pauljanns I've done some tests and there is a couple of solutions on the application side you can do apart from using the detectChanges (or markForChecks) method. 

- You can use data$ as an Observable and rendering using the async pipe as follows:
`data$: Observable<any>;`
`this.data$ = this.httpClient.get('https://catfact.ninja/fact');`
`{{ (data$ | async)?.fact }}`

- Similarly, with BehaviorSubject:
`dataSubject = new BehaviorSubject<any>({});`
`data$ = this.dataSubject.asObservable();`
`this.dataSubject.next(data);`

- Since you are using ng18, you can use the new signals which are optimized for change detection for asynchronous data:
`data: WritableSignal<string> = signal('');`
`this.data.set(data?.fact);`
`{{ data() }}`

The reason why it works on ng17 and not 18 might be related to the new Change Detection mechanism but I'd say for more flexibility, use one of the solution described above instead.
