### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-269.1] IconTabBar No mechanism is available for group skipping or 'Skip to main content link' not provided.

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12494]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
component having issue: Icon Tab Bar
There is no mechanism available for group skipping of elements within the application or 'skip to main content link' not provided.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All versions.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Use multiple Tab, We don't have any mechanism to skip first tab and go inside second Tab content

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
Creating new defect since previous was closed without fix: https://github.com/SAP/fundamental-ngx/issues/11302

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
Tab

**Comment by MeghanaVernekar** [comment]
Hello Colleagues,

Please find the attached video of the 'groups kipping' mechanism available in Ui5 technology with the Key F6.

Uploading Group skipping video oin Ui5.mp4…

For Different technologies, different mechanisms are available for group skipping like concur applications uses 'Skip links' and SAP GUI application uses 'Ctrl +tab' combination. Likewise, we expect a similar behavior is available with respect to ACC 269 requirement.

Please let me know if you need any more details.

Regards,
Meghana.

**Comment by droshev** [comment]
there is no video attached in your message

**Comment by MeghanaVernekar** [comment]
Hello @droshev 

Please find the attached video of the 'groups kipping' mechanism available in Ui5 technology with the Key F6.

https://github.com/user-attachments/assets/256f8959-edd4-4a0d-acde-44b1e9c236ea

**Comment by mikerodonnell89** [comment]
@MeghanaVernekar @divyamalhotra488 We recognize the need for this feature, however I think it would be better for the application developer to implement it, rather than having it built in to the fundamental-ngx library, as the developer would have more control over what exactly receives focus after pressing F6. The library could listen to keyboard events on the icon tab bar, and focus the first focusable element under the icon tab bar, but I can think of some examples when that may not be the best option and a different element would be preferable. Also you may want to capture an F6 keypress from anywhere on the page, not just from the icon tab bar. Is there a reason you want to see this come from fundamental-ngx rather than implementing it in your application?
