### ISSUE TITLE
illustrated message doesn't work with dot and spot types

### ISSUE THREAD

**Issue by robertIsaac** [SAP/fundamental-ngx#12835]
#### Describe your proposal.
using the example from the doc
https://stackblitz.com/edit/fb8evawb?file=src%2Fapp%2Fillustrated-message-example.component.html
when you change the type to dot or spot, it doesn't work

#### Can you handle that on the application side
no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 18.2.12
Fundamental 0.54.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
go to 
https://stackblitz.com/run?file=src%2Fapp%2Fillustrated-message-example.component.html
change type to dot

**Comment by robertIsaac** [comment]
FYI the problem is in the example, it's missing `assets/images/sapIllus-Spot-NoMail.svg` file
but I'm not sure why when I update the example to use `assets/images/sapIllus-Dialog-NoMail.svg` is still doesn't work
it'd be helpful to fix the example

**Comment by droshev** [comment]
@robertIsaac the issue comes from the size of the svg. I have used a smaller svg in your example and it works. [Updated example](https://stackblitz.com/edit/fb8evawb-26py1kar?file=src%2Fapp%2Fillustrated-message-example.component.html,src%2Fapp%2Fillustrated-message-example.component.ts,src%2Fassets%2Fimages%2FsapIllus-Dot.svg)
