### ISSUE TITLE
support multiple versions of documentation

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1533]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
At the moment the documentation website is showing the latest released version. The proposal is to support older versions(in parallel to the latest) as well.

**Comment by sebastienbarbier** [comment]
I keep struggling because of missing documentation for oldest version. Updating to latest is not always possible this would really help 🙌.
Suggestion : What about deploying documentation to static object storage within a folder named with the related version number to keep track of previous documentation ? This sounds like an easy fix.
