### ISSUE TITLE
Modal close button's x is not displayed

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-ngx#1584]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
I updated to the recent version of fundamental-ngx, `"@fundamental-ngx/core": "^0.12.0",` and now the modal close button is invisible, because the 'x' is not displayed:
![image](https://user-images.githubusercontent.com/7091280/68765118-58fc4480-061c-11ea-9fbd-aeee2eeb4afb.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 8.2.13
Fundamental NGX 0.12.0

#### If this is a bug, please provide steps for reproducing it.
I've got a minimal working example over on stackblitz:
https://stackblitz.com/edit/angular-jwtvtc
https://angular-jwtvtc.stackblitz.io/

#### Is there anything else we should know?
If there's a known work-around, I'm happy with that for now, but the underlying issue isn't obvious to me.

**Comment by JKMarkowski** [comment]
Hi @JenniferStamm, it will be fixed in next version (so far it's already in RC). I encourage you to use latest RC, prerelease version.
In 0.12.0, we still had style encapsulation on modal components. So if you don't want to switch versions, the only one workaround is to add some styling into the general css file [like here](stackblitz.com/edit/angular-omg4tt).

**Comment by JenniferStamm** [comment]
Thank you. The added styling helped!
