### ISSUE TITLE
Default placeholder for DatePicker should change base on date format

### ISSUE THREAD

**Issue by vin-chen** [SAP/fundamental-ngx#2135]
#### 
Now the placeholder for DatePicker is by defaut use 'mm/dd/yyyy', even if the user set `format` for it, it won't change. This would confuse the user.
eg. placeholder: `mm/dd/yyyy`, but actual format is `yyyy/dd/mm`

https://github.com/SAP/fundamental-ngx/blob/8877b24ea7173fde8c4ec4af062534c13991c933/libs/core/src/lib/date-picker/date-picker.component.ts#L76

**Comment by mikerodonnell89** [comment]
Due to how custom formatting is handled via the DateFormatParser and DateTimeFormatParser abstract classes, where the application developer must implement their own format and parse functions, I believe setting the placeholder is best left to the application developer as it can not be safely assumed by the component.  I think we should leave the current placeholder as-is because it matches the current default format, however I will make this more clear in the documentation
