### ISSUE TITLE
Form inputs with states - height is taller than fundamental-styles

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#2262]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Compare the error state form input from fundamental ngx:
![Screen Shot 2020-04-03 at 3 58 13 PM](https://user-images.githubusercontent.com/2471874/78408499-8d20d380-75c4-11ea-9d26-2177ad687563.png)

To the one from styles
![Screen Shot 2020-04-03 at 3 58 00 PM](https://user-images.githubusercontent.com/2471874/78408482-8003e480-75c4-11ea-9a12-fe072f861fa6.png)

The one from ngx is 4 pixels taller than the one from styles.  Toggling the is-error state on each shows that the border is inset on the one from styles but not for ngx.

**Comment by JKMarkowski** [comment]
Hello @mikerodonnell89 I think it has been fixed in `0.16.0`
Semantic Input in NGX:
![image](https://user-images.githubusercontent.com/26483208/79455522-48962e80-7fed-11ea-8ecb-341d8df1511e.png)

Semantic Input in Styles:
![image](https://user-images.githubusercontent.com/26483208/79455565-5946a480-7fed-11ea-868f-c6364f9eb711.png)

Could you check if the issue still exist on your os/browser?

**Comment by mikerodonnell89** [comment]
It's fixed
