### ISSUE TITLE
Defect hunting 10.04 for 0.16.0v

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#2304]
Issues from defect hunting on 10.04.

**Comment by mikerodonnell89** [comment]
Tokenizer RTL mode - broken padding, need to figure out which side to align "more" text on, maybe provide option for the dev to decide?
![Screen Shot 2020-04-10 at 8 39 35 AM](https://user-images.githubusercontent.com/2471874/78999389-bc28cf00-7b07-11ea-9a3b-0992e6bda9d2.png)

**Comment by mikerodonnell89** [comment]
Last menu item has an extra bit of space before the bottom of the popover
![Screen Shot 2020-04-10 at 9 00 48 AM](https://user-images.githubusercontent.com/2471874/79000437-debbe780-7b09-11ea-9eb0-c9df38c60e52.png)

**Comment by mikerodonnell89** [comment]
Should probably add some padding here
![Screen Shot 2020-04-10 at 9 05 07 AM](https://user-images.githubusercontent.com/2471874/79000729-673a8800-7b0a-11ea-973b-197557d4e77e.png)

**Comment by mikerodonnell89** [comment]
Calendar - I think we should only display the week counter specifically on the week counter example.  It is a strange feature that I think will usually do more to confuse than anything.
![Screen Shot 2020-04-10 at 9 14 04 AM](https://user-images.githubusercontent.com/2471874/79001434-b634ed00-7b0b-11ea-936f-d45f85684b75.png)

**Comment by JKMarkowski** [comment]
Calendar Keyboard support should consider RTL mode as well.

**Comment by salarenko** [comment]
- No arrows navigation and spacebar as select support in calendar | IE11
- Dialog is not centered because of `flexbox` + `position: absolute` | IE11
- Dialog Body has rounded top corners hen header is visible | IE11
- Dialog cannot be dismissed by Esc key | IE11
- Dropdown links have visited native styling | IE11
![image](https://user-images.githubusercontent.com/17496353/79002205-3e3ce600-7b50-11ea-8cc7-c5243b807141.png)
- Input number spinner broken buttons | IE11
![image](https://user-images.githubusercontent.com/17496353/79002369-9b389c00-7b50-11ea-850f-40ac4b1bf7fa.png)
- Should these look like that? | Cross browser
![image](https://user-images.githubusercontent.com/17496353/79002500-e8b50900-7b50-11ea-859a-e86556c30e5a.png)
- Broken styles for menu examples, broken kyboard navigation | IE11
![image](https://user-images.githubusercontent.com/17496353/79002722-595c2580-7b51-11ea-96f8-071ccf64a9e0.png)
- Missing padding in RTL Simple Multi Input | Cross Browser
![image](https://user-images.githubusercontent.com/17496353/79002782-7b55a800-7b51-11ea-9417-345ec66c874e.png)
- Cannot check multi input because of padding | Cross Browser
![cannot-check-multi-input](https://user-images.githubusercontent.com/17496353/79003339-adb3d500-7b52-11ea-9af4-207d7fde1395.gif)
- Small misalignment inside Inverted Object Status example | IE11
![image](https://user-images.githubusercontent.com/17496353/79003539-1602b680-7b53-11ea-8b5f-cdd0898528f4.png)
- Broken styles in Popover Placement example | Cross Browser
![image](https://user-images.githubusercontent.com/17496353/79003638-477b8200-7b53-11ea-995d-ec8e56a29b5a.png)
- Broken Radio Buttons in Reactive example | Cross Browser
![image](https://user-images.githubusercontent.com/17496353/79003869-cf618c00-7b53-11ea-9eaf-4e9985613ae8.png)
- Broken input addon in Select | IE11
![Uploading image.png…]()

**Comment by mikerodonnell89** [comment]
Table with checkboxes, select all doesn't work

![Screen Shot 2020-04-10 at 9 58 43 AM](https://user-images.githubusercontent.com/2471874/79004413-f0a18880-7b11-11ea-8a2b-65ce6d3c191b.png)

**Comment by JKMarkowski** [comment]
Schematics are not prepared for new `import` of styling
```json
"node_modules/fundamental-styles/dist/fonts.css",
"node_modules/fundamental-styles/dist/icon.css"
```
We should also install 
```json
    "@sap-theming/theming-base-content": "^11.1.18"
```
automatically
We can have some options to choose, or only default 
```scss
@font-face {
    ...
}
```

**Comment by mikerodonnell89** [comment]
Shellbar - hover the search input or search input button
![Screen Shot 2020-04-10 at 10 02 24 AM](https://user-images.githubusercontent.com/2471874/79004645-6a397680-7b12-11ea-96f8-0fcc179b9843.png)

**Comment by JKMarkowski** [comment]
All Issues from there has been addressed
