### ISSUE TITLE
Locale support for input-fields with type number

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2522]
#### Is this a bug, enhancement, or feature request?
not sure

#### Briefly describe your proposal.
We are using the [input-field](https://sap.github.io/fundamental-ngx/#/core/input) of fundamental-ngx core, with the type "number". By default it is showing decimal numbers (values from fromControl) with comma (2,3). But there are other locale like "en-US", where decimal numbers should be shown with a point. I'm not sure if this is already supported, but I didn't found an "locale"-attribute like in example of the the [date-picker docs](https://sap.github.io/fundamental-ngx/#/core/datePicker):
![Screen Shot 2020-05-15 at 17 19 40](https://user-images.githubusercontent.com/26272656/82066874-46002500-96d0-11ea-9b5f-8ead8a61e1ea.png).
I tried the locale attribute in the input-field, but nothing happened.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
    "@fundamental-ngx/core": "^0.15.5",
    "@angular/core": "^8.2.12",

3

**Comment by JKMarkowski** [comment]
We agreed on including some directives with separator inputs, so the separators will be added automatically. For example `<input fd-only-input [thousandSeparator]=",">`

**Comment by zaheral** [comment]
Does this mean that we need to pass the information if it is a "," or "." and this will be automatically used by the element?

**Comment by zaheral** [comment]
@JKMarkowski 
sorry for annoyance. Just want to check the current state regarding my last question

**Comment by fkolar** [comment]
I believe we should not hard code anything. cuz then you have decimalPoint separator , 1000, separator. but anuglar is already figured this out in its core, they have method that reads current locale and can format this. 

What should be the ideal solution is support number pattern, so you have freedom to add space as 1000 separator if you want to or comma, etc..

**Comment by zaheral** [comment]
Hi @fkolar ,
just want to check if there are some news here.

**Comment by zaheral** [comment]
@fkolar @JKMarkowski 
Sorry, for disturbing again. Just want to know if there are some news here

**Comment by salarenko** [comment]
Hey @zaheral. On of our features coming in v0.21 will be `StepInput` supporting localization formatting.
There is a way to use `StepButton` without Increase/Decrease buttons, so it will almost look like a `<input type="number"`. However this is not a recommended solution, because according to Fiori3 specification `StepInput` should be used always with buttons.

We will probably try to extract formatting behavior into a directive so it can be used with other standalone inputs, but that's the task for one of the future NGX Core versions.

This is still a PR, but if you are curious you can check:
- https://github.com/SAP/fundamental-ngx/pull/2782
- https://deploy-preview-2782--fundamental-ngx.netlify.app/#/core/step-input

**Comment by zaheral** [comment]
Hi @salarenko,
I checked the demo out with the StepInput
`<fd-step-input id="polish-input" [(value)]="value2" locale="pl-PL"></fd-step-input>`
This is exactly what we need for the standalone input-field.

So, that means it will not be delivered with v0.21. Are there plans to get it on v0.22?

Looking forward for this solution

**Comment by rodema** [comment]
Hello ngx-fundamental team (@salarenko , @droshev ),
this is Matthias, colleague from Zaher and part of the FSM developer team who are using ngx-fundamentals.
I checked the API for the Input control and for me it looks like that it still does not support a locale. (version 0.25.1)
In the StepInput API I could find the locale support and it works great there.
But as you mentioned, it's not recommended to use the StepInput control for a "normal" number input field.
Because for me it looks that this is still an open topic, I re-open that issue again.
Pls. let us know if this feature is still on your roadmap.
Thank you for your support.

**Comment by rodema** [comment]
Hello ngx-fundamental team (@salarenko , @droshev ),
any news regarding the Local support for the number Input control?
Thank you for your feedback and support.

**Comment by karkhile** [comment]
Hi ngx-fundamental team (@droshev, @salarenko  )
any update on the above mentioned issue , do we have a solution for the use case described in this issue.
@zaheral  : any suggestion how did you solve the issue ?

**Comment by zaheral** [comment]
Hi @karkhile and @droshev,
the problem is still not solved yet. 
Can we please reopen this item? Or do we have an solution for this issue today? Because I didn't found something in the demo pages.

**Comment by zaheral** [comment]
Created new issue for this problem: https://github.com/SAP/fundamental-ngx/issues/13404
