### ISSUE TITLE
[DatePicker] Messages are always showing up in datepicker component

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2687]
#### Is this a bug, enhancement, or feature request?
Bug/Enhancement (not sure here)

#### Briefly describe your proposal.
The [input-field component](https://sap.github.io/fundamental-ngx/#/core/input#input-states) has the feature to show messages like errors, when you for example hover over the input-field. This is possible by using the \<fd-form-input-message-group\> component. With the [datepicker component](https://sap.github.io/fundamental-ngx/#/core/datePicker#combobox-reactiveForm) I didn't saw how this can work. In the doc-examples the messages are fixed.
I created here an stackblitz example to compare between input-component and datepicker-component: https://stackblitz.com/edit/angular-k1xdos

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

- On our project we are using "@fundamental-ngx/core": "^0.17.0"
- The stackblitz example is using "@fundamental-ngx/core": "0.18.0"

#### If this is a bug, please provide steps for reproducing it.
Checkout stackblitz example

**Comment by JKMarkowski** [comment]
Hello @zaheral,

our `form-input-message-group` works only with `fd-form-control`, it's nothing more but popover wrapper. Take a look at this [example - datepicker 3](https://stackblitz.com/edit/angular-k1xdos-kjejjz?file=src/app/date-picker-form-example.component.html). There is just the popover with fd-form-message component used. I added additional popover there, it has some problems with change detection, but it can be fixed by closing body after date pick.

**Comment by zaheral** [comment]
Hi @JKMarkowski,
thank you for the solution. It works for me.
