### ISSUE TITLE
Components with icons have some alignment issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3262]
#### Is this a bug, enhancement, or feature request?
bug

### Icon related issues
It depends on fundamental-styles version 0.12.0

- [ ] Popover misaligned example
![image](https://user-images.githubusercontent.com/17496353/92379987-a9431680-f108-11ea-8f20-4896a7d6dc0d.png)

- [ ] Broken layout of select extended options example
![image](https://user-images.githubusercontent.com/17496353/92380280-32f2e400-f109-11ea-8b43-d3e8a537e2f0.png)

- [ ] Shellbar broken button styling
![image](https://user-images.githubusercontent.com/17496353/92380330-4e5def00-f109-11ea-9cd6-86c5e90ae7b7.png)

- [ ] Table with sorting broken popover layout
![image](https://user-images.githubusercontent.com/17496353/92380577-b7ddfd80-f109-11ea-8af5-eb03bbcd2b1e.png)

- [ ] Broken layout of side navigation with icons examples
![image](https://user-images.githubusercontent.com/17496353/92380396-6a619080-f109-11ea-8fbc-f9df42c30239.png)

**Comment by mikerodonnell89** [comment]
I am not seeing "Popover misaligned example" or "Shellbar broken button styling", those look fine, but for the other ones I believe the fix must come from styles as the issue is there as well

![Screen Shot 2020-09-16 at 1 27 21 PM](https://user-images.githubusercontent.com/2471874/93383076-5bbd5c80-f820-11ea-98ca-538c7466290c.png)
