### ISSUE TITLE
Bug: Input group: IE browser value help is displayed in middle (form-field with enabled options [hint] and [required] looks broken in IE11)

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3322]
Description:  IE browser value help is displayed in middle 
Windows Machine 
IE browser 
Version 11.1016.18362

Expected: Value help should be displayed in right hand side

Attached screen shot

IE browser 

![image](https://user-images.githubusercontent.com/32538291/93428575-570aae00-f8dd-11ea-9429-ac39c6ad863f.png)

Chrome and other browsers

![image](https://user-images.githubusercontent.com/32538291/93428654-79043080-f8dd-11ea-884d-b8554861e925.png)

**Comment by dimamarksman** [comment]
@puru-hk 
The issue is not connected directly to the `form-group`
It happens for anyone who uses `form-field` component with options `[hint]` and `[required]` enabled, 
for example `fdp-input`
![image](https://user-images.githubusercontent.com/3263744/93562267-61d14b80-f98e-11ea-8984-372faa0046a2.png)

Could you please change issue title to make it more precise, as 
`form-field  with enabled  options [hint] and [required] looks broken in IE11`

**Comment by puru-hk** [comment]
Tested it is working as expected.
