### ISSUE TITLE
textarea width issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3353]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
the width of the textarea gets truncated

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

If we go to textarea page directly there is no issue:
https://fundamental-ngx.netlify.app/#/platform/textarea
![platform-textarea](https://user-images.githubusercontent.com/4380815/93824892-39697b80-fc32-11ea-8fe9-40b7b8527acd.gif)

how to reproduce the issue:
1. go to https://fundamental-ngx.netlify.app/#/platform/home
2. refresh the page
3. go to combobox https://fundamental-ngx.netlify.app/#/platform/combobox
4. go to  https://fundamental-ngx.netlify.app/#/platform/textarea

![platform-textarea-issue](https://user-images.githubusercontent.com/4380815/93824908-3c646c00-fc32-11ea-8609-9290c7366ac6.gif)

**Comment by kavya-b** [comment]
My observation:
Issue is due to styles for `fd-popover-custom` getting overridden: The styles where display:inline-block is coming from fundamental-styles but it is not right so core has fixed it by having display:flex instead.

Since we are using Platform Forms which uses its own `fdp-form-input-message-group`, we are placing the fix of display:flex there as well, which is what you see striked down.

The one with fundamental-styles is getting more importance than the one internally assigned, which is causing the width to shrink. Since this .fd-popover-custom class is used across other Forms components, it is affecting the width of other components as well.


1. It is reproducible only when there is a dependency on combobox in the reproduction steps.

2.  Also, when I get the faulty width on textarea and reload the page, it goes to full width; but when I do the same on combobox, it shows the smaller width itself.

3.  I think if this  issue (https://github.com/SAP/fundamental-ngx/issues/3358) is completely addressed where Deno asks for examples with 100% width for combobox, it will solve the problem automatically for Textarea and Input.

**Comment by InnaAtanasova** [comment]
part of combobox PR
