### ISSUE TITLE
Bug: Core Fixed Card Layout - does not update layout properly

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3603]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
When layout width changes due to to some changes externally (sibling block gets hidden so fixed card layout width gets wider) the fixed card layout does not calculate new layout properly.  
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/fixed-card-layout on desktop screen.
2. See the first example with a three columns.
3. Hide Side navigation panel.
4. Fixed card area remains using three columns when it should use four columns layout.
#### Is there anything else we should know?
[screen-capture-fixed-card-resize.webm.zip](https://github.com/SAP/fundamental-ngx/files/5364981/screen-capture-fixed-card-resize.webm.zip)

**Comment by InnaAtanasova** [comment]
Some issue I found testing on mobile device:
- content is overflowing
![AAAC60E6-B508-41B1-89E2-F762A14DA935](https://user-images.githubusercontent.com/39598672/96755120-4b108100-13a0-11eb-924c-5499f0650d07.jpg)

- in landscape mode the example doesn't look good:
![792D67D6-E5CF-4A17-815B-6F0FB6BF782B](https://user-images.githubusercontent.com/39598672/96755194-654a5f00-13a0-11eb-90e9-9bee16763cbb.jpg)
![2325FBCB-7207-4A23-B9C0-5963C7EAD341](https://user-images.githubusercontent.com/39598672/96755249-75fad500-13a0-11eb-8b9a-0fd767cb867d.jpg)

- The issue created by @dimamarksman is not really fixed https://github.com/SAP/fundamental-ngx/issues/3600
when I try to scroll the content with my finger it either does not respond to the event ir starts dragging the card.

- More a technical question than a comment: when I start dragging a card and reach either the top or the bottom, the drag event does not trigger scroll. Imagine the case that is in the screenshot. Your card is at the end of the visible container but there are other cards after it. You need to scroll in order to show part of the next card so you can drop the card. What most users would expect is that when you start dragging you trigger the scroll when you reach the ends of the container.
![D7054890-6BD9-47EC-9D34-3DD40197B49B](https://user-images.githubusercontent.com/39598672/96755629-f6213a80-13a0-11eb-9c88-43c2027830f3.jpg)

- Desktop: (the container should shrink when the docs site is resized)
<img width="761" alt="Screen Shot 2020-10-21 at 1 07 25 PM" src="https://user-images.githubusercontent.com/39598672/96755943-5b752b80-13a1-11eb-858b-6848c34ac10b.png">
