### ISSUE TITLE
Formatted Text: Focus is not as per the Fiori3 for safari browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3627]
Description: When it Focus border is not as per the Fiori3 for different browser

Expected: Border should be as per the fiori3

Screenshot: for safari browser
![image](https://user-images.githubusercontent.com/32538291/95955465-7b917180-0e1a-11eb-8d46-1b8ab9da29a2.png)

Firefox browser
![image](https://user-images.githubusercontent.com/32538291/95956563-1c346100-0e1c-11eb-8da4-b259cec0b540.png)

Edge browser

![image](https://user-images.githubusercontent.com/32538291/95956681-45ed8800-0e1c-11eb-8462-403db460955f.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/95955524-949a2280-0e1a-11eb-9be4-c5865d6125d4.png)

**Comment by mykolavorobiov** [comment]
@puru-hk 
I understood your point, but it's not related to this component.
Because this component is a wrapper for embed code only.
This issue relates to the outline style and as a developer, I can add `outline-width: 10px;` to link into formatted-text, but in component, I don't know about that and can't prevent this. The developer of this app must add padding the same as the outline-width. Unfortunately, I can't prevent this issue, when users append any links with some big outline-width. It's impossible to prevent with a formatted-text component.
Also, the outline on the link is not the same as padding or margin, and don't affect other content around the link.
And if you using a formatted-text component and append some HTML to sanitize, you need to prepare styles by yourself.

I can improve docs with a description of this point to prevent this situation in the future. Does it make sense?

**Comment by puru-hk** [comment]
Assign this issue to @DeepakSap14 as he worked on link component.

**Comment by mykolavorobiov** [comment]
@puru-hk 
I think that it's not fully covered by the link component. Users can add custom styles to embed code (it's one of the goals for this component), and we can't prevent this. It's impossible.
For example, you can add `style="position: absolute; top: -999999px;"`, and you will not see link.

**Comment by puru-hk** [comment]
okay what is the solution for this?

**Comment by droshev** [comment]
I think this works as expected. It would be per fiori 3 if the right classes are used.
