### ISSUE TITLE
Carousel: Missing example for images for the thumbnail page indicators load 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3728]
Description: Missing example for images for the thumbnail page indicators load 

Expected: Should implement this example 

Screenshot

![image](https://user-images.githubusercontent.com/32538291/97952164-6f1d8a80-1dc2-11eb-9ad5-e1c376372245.png)

**Comment by DeepakSap14** [comment]
Fiori does not have styles defined for third example with thumbnail. This is out of scope.

**Comment by puru-hk** [comment]
Its a Ariba specific requirement

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by DeepakSap14** [comment]
we do not have styles for it @puru-hk.

**Comment by puru-hk** [comment]
Check with manju. And also you can check in ariba wiki

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by puru-hk** [comment]
Keny is added the visual spec. Could you implement as per visual spec https://www.figma.com/file/PrHXo4hVWfOdNgeo4WTHRi/Ariba-Component-Library-v0.5?node-id=815%3A73
https://www.figma.com/file/Qy4g1iSVR7KumwBw8oche7/Ariba-Template-Library-0.1?node-id=2035%3A239

**Comment by aberikashvili** [comment]
@puru-hk I can't access https://wiki.ariba.com/pages/viewpage.action?pageId=102734570 and there's File Not Found for https://www.figma.com/file/Qy4g1iSVR7KumwBw8oche7/Ariba-Template-Library-0.1?node-id=2035%3A239

**Comment by DeepakSap14** [comment]
@aberikashvili 
we do not have design available for this implementation currently.
this issue is an `enhancement` and can be picked later, when design is available.

<img width="270" alt="Screenshot 2021-09-03 at 8 25 33 PM" src="https://user-images.githubusercontent.com/57661487/132025833-c5b52485-a327-4604-ac73-bdef054e3455.png">

attaching current available design from fiori.
[carousel-fiori-cisual-design.pdf](https://github.com/SAP/fundamental-ngx/files/7106791/carousel-fiori-cisual-design.pdf)
