### ISSUE TITLE
Bug: Dynamic Page Layout: Key information, Global navigation, layout navigation are not aligned properly 

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3743]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

**1 Issue** 
-The key information is not aligned with the Title
![Screen Shot 2020-11-04 at 1 28 08 PM](https://user-images.githubusercontent.com/72403541/98169824-a5a7f200-1ef5-11eb-90d8-7d1cc2f7bbad.png)

**2 Issue** 
- - Global navigation should be on the same level with the layout navigation. Exceptions are for tablet less than 1280px.
![Screen Shot 2020-11-04 at 2 25 48 PM](https://user-images.githubusercontent.com/72403541/98174635-dab84280-1efd-11eb-9d87-2a49e88c1122.png)

**Comment by kavya-b** [comment]
Hi @daisy-yovcheva ,
1. This is currently according to the spec. UI5 adds some height/paddings to ensure alignment with title. On speaking with designers, they suggested we bottom-align the texts. This is something to be fixed on the fundamental-styles lib, and an issue is already open for this: https://github.com/SAP/fundamental-styles/issues/1800
2. Since the `size` attribute for this example is passed as `medium`, it takes the page padding values of a tablet and also moves the global actions above. This is as expected.
Please note again, that responsiveness is being handled by asking the user for the `size` input and not by resizing the windows and automatically applying the correct layout, as this topic needs a separate discussion, which is why issue #3473 was created to track this.

**Comment by daisy-yovcheva** [comment]
@kavya-b, Ok. Sounds good. I am a part of the Ariba UX Design team who has to review all released components. Thanks!

**Comment by kavya-b** [comment]
This has now been fixed in Styles https://github.com/SAP/fundamental-styles/pull/1924. @puru-hk please verify it [here](https://fundamental-styles.netlify.app/?path=/docs/layouts-dynamic-page--desktop)

**Comment by kavya-b** [comment]
As discussed with Puru, the underlying issue is fixed in Styles as mentioned in the previous comment and that fix will reflect automatically in ngx once Styles version 0.14 is consumed by ngx library.

**Comment by manjunathanagaraj** [comment]
Styles version 0.14 released. @daisy-yovcheva , could you please check and close it?

**Comment by daisy-yovcheva** [comment]
Hi @manjunathanagaraj, 
Now, It's aligned. I will close the ticket. Thanks!
