### ISSUE TITLE
Datetime/Picker: There is no validate datetime input field 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3905]
Description: There is no validate datetime input field 

Expected: Validation should be present for datetime input field 

Screenshot attached:

![image](https://user-images.githubusercontent.com/32538291/99790232-d02ab980-2b49-11eb-8cff-bc1fb4ee15db.png)

**Comment by kavya-b** [comment]
Hi @puru-hk there is no extra validation logic on the datetime value in platform. The same behaviour can be observed in core as well:
![image](https://user-images.githubusercontent.com/53509521/99939160-73b8db80-2d8f-11eb-945d-84e01ff07fe3.png)
hence adding the core label to this issue to get the core team's thoughts on this.

@droshev could you comment on how the validation logic on the datetime value works for datetimepicker? Currently, a value inputted like '23456' becomes a year in the picker; is this expected?

**Comment by manjunathanagaraj** [comment]
For input field in Date Picker Fiori says "The system validates the entry and provides the user with feedback. You can also show placeholder text in the field". I think we must have the validation logic. SImilar behaviour is seen in UI5 implementation.

**Comment by kavya-b** [comment]
@manjunathanagaraj The spec does not specify the exact criteria for invalid dates. Currently, ngx implementation also has validation in that if you type `02j` it is invalid, but `02` is considered valid(as a month). UI5 considers both inputs as invalid. As another example, if we type `02-2321-23` it is considered invalid because it does not follow MM-dd-YYYY and 2321 is not a month. However, entering only `2321` is considered valid as it considers it a year.
Therefore I wanted to understand what is the validation logic being followed. @dimamarksman do you have an idea on this?

**Comment by manjunathanagaraj** [comment]
here is the proposal, we can debate on this:
1) for a given locale, lets have a default corresponding format. Validation should be against this default.
2) we need to identify the list of locales and the approved/widely recognised formats. Validation logic can be written only after this.
3) Probably Fiori3 designers can share the list of locales and their default format. 

we need to route this to Fiori3 team through @droshev

**Comment by dimamarksman** [comment]
We definetly should be able to determine if entered string is a valid date or not.
DatetimeAdapter is responsible to parse a date string as well as determine if the provided date string is valid or not.
https://github.com/SAP/fundamental-ngx/blob/534e736229be79ae2bbe18c50db82b1051e8d58d/libs/core/src/lib/datetime/datetime-adapter.ts#L191-L197
https://github.com/SAP/fundamental-ngx/blob/534e736229be79ae2bbe18c50db82b1051e8d58d/libs/core/src/lib/datetime/datetime-adapter.ts#L299-L303
Datepicker has a format option it work with but **at this moment we have only FdDatetimeAdapter** which relies on native [Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) implementation and that the problem cause it is not reliable way, **it can parse only a string representing a simplification of the ISO 8601** calendar date extended format.
That's why `FdDateFormats` does not have parse format option at all (no sense due to unablity) 
https://github.com/SAP/fundamental-ngx/blob/534e736229be79ae2bbe18c50db82b1051e8d58d/libs/core/src/lib/datetime/fd-date-formats.ts#L5 

Once we have DateAdapter based on third party library we can parse and format date strings reliably as result we are able to get info when provided date string is valid or not.
For example via moment js we can do that:
![image](https://user-images.githubusercontent.com/3263744/103278053-3caf9880-49d3-11eb-9706-a216ae533eba.png)

**Comment by kavya-b** [comment]
as explained in the previous comments, this is dependent on MomentDatetimeAdapter and can be taken up once the adapter becomes available.
cc: @manjunathanagaraj @skocharian

**Comment by mikerodonnell89** [comment]
Closing as this was settled some time ago with the adapter implementation
