### ISSUE TITLE
Bug: fixed card layout (core): columns aren't reactive until extra action performed

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#3910]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Currently, columns aren't reacting correctly. They don't adjust to new width until an action is performed (btn click, click and drag)

#### If this is a bug, please provide steps for reproducing it.
resolution: 1920x1080
STR : 
- look at number of columns in the example (3)
- click to close the navigation menu in the top right of the page
- look at the number of columns in the example again (still 3, but you can see there's plenty of room for column 4)
- click on a card
- look again (4 columns)

expect: Columns should react to width changes without additional actions

![Peek 2020-11-20 18-32](https://user-images.githubusercontent.com/47522152/99825339-9369bd00-2b5f-11eb-866b-a294eaf95812.gif)

Note: was working on v23

**Comment by DeepakSap14** [comment]
for this to work correctly we need to depend on some third party library. which is documented in **Notes**.
User who is using this component can use third party lib eg. angular-resixe-event and achieve the desired behaviour. Because of restrictions in fundamental-ngx, that library can not be used in our documentation.
