### ISSUE TITLE
Bug: Object Status icons are wrong type and not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3930]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Object Status icons are wrong type and not aligned with Visual Core. Correct icons are below. On Platform and core.
![image](https://user-images.githubusercontent.com/71797052/100170597-daff8a00-2e7a-11eb-9ea0-af5c507dd654.png)
![image](https://user-images.githubusercontent.com/71797052/100170604-df2ba780-2e7a-11eb-881a-6b702bf0adda.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? 
v0.24.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/object-status
Scroll down to: Clickable Object Status; Inverted Object Status; Object Status Large design
See error below:
![image](https://user-images.githubusercontent.com/71797052/100170899-755fcd80-2e7b-11eb-9cc9-00a88451eec5.png)
![image](https://user-images.githubusercontent.com/71797052/100170906-798beb00-2e7b-11eb-9fb6-d187bbff616d.png)

**Comment by kavya-b** [comment]
Hi @pierrom this issue is currently fixed for the specified colors(in issue description) except for the `informative` state in the latest version.
However, on further analysis, I now see that the visual spec has changed even more such that the icons and other values specified in this issue description are no longer what is present in the spec. Therefore, Object Status needs to be refactored to the latest spec in Fundamental Styles, and it can probably be closed here since there is no point in fixing only the `informative` state now. Can we close this issue and create one in Fundamental Styles instead?
![image](https://user-images.githubusercontent.com/53509521/120596716-b3a8fb80-c461-11eb-80bb-9fc9eba1f6e2.png)

cc: @manjunathanagaraj @puru-hk

**Comment by pierrom** [comment]
Agree. Will close per kavya-b comments. Thanks.
