### ISSUE TITLE
<tr> in fd-table causes Firefox tab to crash

### ISSUE THREAD

**Issue by schaefermichael** [SAP/fundamental-ngx#396]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When I view the documentation for tables (https://sap.github.io/fundamental-ngx/docs/table) or create a <tr>-Element in a fd-table-body, the tab crashes in Firefox (Version 64). Restarting the browser didn't help, but it worked sometime inbetween - so it might not be fully reproducable.
Crash report: https://crash-stats.mozilla.com/report/index/a67c3529-cdae-4c55-9af1-3d01a0190107
We were not able to reproduce it with the current FF Developer Edition

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7.0.0, fundamental-ngx 0.0.26-beta

#### If this is a bug, please provide steps for reproducing it.
The crash only occured when crating a <tr>-Element in the table body (<tr> in the table-header actually worked)

**Comment by mikerodonnell89** [comment]
What do you mean by "create a -Element"?  The table seems to be working fine for me with Firefox 64 on OSX.

**Comment by SerkanSipahi** [comment]
@schaefermichael could you provide a https://stackblitz.com/ example, thanks.

**Comment by schaefermichael** [comment]
I did not manage to replicate the issue consistenly. While it also happened on my private computer, only my working laptop seems to have that issues constantly (as soon as one tr-element is in a fundamental-ngx table). At this point I believe this is some weird bug in the firefox engine or at least nothing which can be handled inside the project.
I'll therefore close the issue for the moment. If I somehow get to find the exact reason for that problem, I'll send you an update.

**Comment by schaefermichael** [comment]
Hi,
on Tuesday that topic arised again: In a sprint review, a collegue opened a prototype of our dashboard (using fundamental-ngx).
The problem is that fundamental-ngx inserts intermediate elements into the table-element (in our case fd-table-body is the problem). As soon as such an element is present and uses `display: contents`, Firefox crashes. Still no idea why this only occurs on some installations.
Relevant stackblitz: https://angular-k6cfgb.stackblitz.io
It would be great to have that one fixed, it's pretty frustrating as a user.

**Comment by jot-hub** [comment]
Hi, is anyone working on this? This is a blocker if we are to continue to use `fundamental-ngx`

here is the latest issue with this - https://sapjira.wdf.sap.corp/browse/C4H01-50 - at the moment, we are working around this with ~`fundamental-ngx`~ `fundamental` table

**Comment by mikerodonnell89** [comment]
Googling the crash reason from the crash report leads me to believe this could be caused by an add-on or graphic hardware acceleration.  I'm still unable to reproduce on Mojave and FF 65.  Try disabling add ons and hardware acceleration and let me know if it's still happening.  Also it would be helpful if everyone reporting this issue could include their operating system and firefox version.  Seems like some users seeing this error were able to get around it by updating their firefox version

**Comment by jot-hub** [comment]
Here is more info:
```
Windows 10 Enterprise 1803 Build 17134.648
FF 66.02 (64 bit)
fundamental-ngx 0.3.3
```

**Comment by MattL75** [comment]
I never managed to reproduce that issue. However, it seems to me like the problem comes from the intermediate fd-table-body, fd-table-header elements. It's also mentioned that the table from Fundamental CSS works just fine. Our table markup should ideally not place intermediate elements inside a table html, as that can lead to some weird behaviours. I propose that we remove the fd-table-body and fd-table-header, instead allowing the users increased flexibility at the cost of a bit extra markup. Thoughts @mikerodonnell89 ?
