### ISSUE TITLE
DateTime Picker: Reactive form examples not working properly 

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#3971]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.

DateTime Picker: Reactive form examples not working properly 
on submit button without focusing on the input the form submission happens post making the field Mandatory.
![image](https://user-images.githubusercontent.com/53534379/100715588-6af28600-33dd-11eb-9333-a47af8695188.png)
from the above example we could see the form data submitted with invalid status. and border of input is not as per spec.

#### If this is a bug, please provide steps for reproducing it.
Step 1:-
got to link: https://fundamental-ngx.netlify.app/#/platform/datetime-picker
Step 2:-
 move to "DateTime Picker with Reactive Forms" section 
Step 3:-
click on submit button.

**Comment by kavya-b** [comment]
@Lokanathan-k @puru-hk @manjunathanagaraj please refer to the ongoing discussion in the associated PR https://github.com/SAP/fundamental-ngx/pull/3992 . Basically, from [UX design](https://experience.sap.com/fiori-design-web/form-field-validation/#on-create-or-save) it seems form validation should be handled at the library level itself, using message popovers. Currently, we don't have the message popover component, and form submission with validation is handled only for a few components, that too at the documentation level, not at the library level.

**Comment by kavya-b** [comment]
As per Fiori guidelines, forms should validate on submission using message popovers, but as was recently discussed, this will be implemented only in phase 3 of Platform Form enhancements, and not now. Also to note that the message popover visual spec needed for styles is undergoing some design update as well. Since currently this is an inconsistent solution where some components validate on submit(at the example level and not library level) while some don't, I will be closing this issue as not it is not blocking the release.
