### ISSUE TITLE
Multiple modals should be able to be opened at once

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#414]
There are some use cases were we might need multiple modals on the screen at once.  For example, if a form modal is opened, we might want to display another confirmation modal when the user attempts to save or discard information entered in the form modal.

**Comment by MattL75** [comment]
This is already possible through wizard magic. I'll post a PR in a bit that has an example on how to do it. It's definitely not straightforward though, so we should probably discuss a better way to accomplish this.

Right now, you need to provide the ModalService in your first modal so that the modalRef to the second modal is independent from the one of the service provided in the root. You basically end up with:

Root ModalService modalRef --> FirstModal
FirstModal ModalService modalRef --> SecondModal
