### ISSUE TITLE
Bug: Object List Item not aligned with Visual Core - extra vertical padding between image and attributes and between attributes.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4180]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Object List Item not aligned with Visual Core - extra vertical padding between image and attributes and between attributes.
![image](https://user-images.githubusercontent.com/71797052/102970567-97656380-44ac-11eb-9432-66daae1c3adc.png)

See specs from Visual Core below:
![image](https://user-images.githubusercontent.com/71797052/102970596-a77d4300-44ac-11eb-982f-e51efd31f861.png)
![image](https://user-images.githubusercontent.com/71797052/102970609-acda8d80-44ac-11eb-808a-0fb46a3a4b1a.png)
![image](https://user-images.githubusercontent.com/71797052/102970618-b3690500-44ac-11eb-8ab3-831d4c27fff3.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0 - v0.26.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://fundamental-ngx.netlify.app/#/platform/object-list-item
Scroll to: All Object List Item
See: Error

**Comment by sKudum** [comment]
Hi @pierrom,

1). Avatar height and width is 3rem which is equal to, the above one height lighted class not related to avatar that is related to header, am attaching exact screen shot of avatar (which is as per Fiori3 specs) for reference.

<img width="401" alt="2020-12-24_10-59-07" src="https://user-images.githubusercontent.com/53487468/103063496-81a08d00-45d7-11eb-9d7b-32c139ef1a1d.png">


2).Gap between header details and object attribute first row is expected gap as per fiori. We can't remove it attaching for reference screen shot of specs and platform value.

**In fiori3 spec:**
<img width="562" alt="2020-12-24_11-04-54" src="https://user-images.githubusercontent.com/53487468/103063671-068ba680-45d8-11eb-9da1-07c36014a037.png">


**In Platform:**
<img width="1499" alt="2020-12-24_10-52-54" src="https://user-images.githubusercontent.com/53487468/103063537-9d0b9800-45d7-11eb-83d8-80b8612dec5d.png">


3).Vertical gap between attributes.It is fixed in master. yet to be published. Next release hopefully it is available. Attaching screen shot for reference.

<img width="530" alt="2020-12-24_11-07-53" src="https://user-images.githubusercontent.com/53487468/103063774-566a6d80-45d8-11eb-9fdc-7a1038597bd5.png">
