### ISSUE TITLE
Bug: Core Input Group secondary icon not reflecting correct colors on theme change

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#4231]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
In ` Input Group Search` example, the secondary icon(clear X) does not reflect changed color when theme is changed.

#### If this is a bug, please provide steps for reproducing it.
latest v0.26.0-rc.28
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/core/inputGroup
2. Go to example ` Input Group Search` and write in the 2nd input group such that a X icon appears next to the search icon. 
3. Change the theme to HCW/HCB/Fiori 3 Dark.
4. Observe the clear icon(X), it has not changed color.

<img width="1145" alt="Screenshot 2021-01-04 at 4 42 53 PM" src="https://user-images.githubusercontent.com/53509521/103530093-d9c77100-4eac-11eb-9113-37ce3439b240.png">

**Comment by olshansky** [comment]
@kavya-b as I mentioned [here](https://github.com/SAP/fundamental-ngx/issues/4229#issuecomment-754497073) this icon is a sort of native browser icon which we do not control. This icon appears to `input[type="search"]`, so we have a lot of options to fix this issue _(depends on requirements)_: 
- just hide this icon for `input[type="search"]`
- change styles of this icon (hide default icon and add a new one to pseudoelement) _(needs to move the issue to styles repository)_
- refactor our `InputGroupComponent` to receive multiple glyphs (one of which would be `decline` and could replace native (x) icon)
- refactor our `InputGroupComponent` to add an additional button to `input[type="search"]` and hide native (x) icon

@kavya-b @manjunathanagaraj who can help to determine the correct option depending on the requirements for the InputGroup?

**Comment by manjunathanagaraj** [comment]
@kavya-b , @olshansky , if there are no hardcoded color values and only Fiori3 theming variables are used, then we should typically report this to Fiori3 team through @droshev .

@olshansky , if you havent used any hard coded values, then I suggest you assign this to @droshev  so that we get to know the behaviour from Fioir3 team.

**Comment by kavya-b** [comment]
@olshansky I am not sure either if the Fiori3 visual spec has something to say about this- I was not able to find the spec for Input Group. Although Fundamental Styles covers this component, there is no example of this usecase. Like Manju mentioned, this is probably a question for the Fiori3 design team for this usecase.

**Comment by manjunathanagaraj** [comment]
Yes, Input Group is not a Fiori3 component. Sorry, it just didnt strike me :-(
I leave this to @olshansky  and @droshev for a suitable implementation approach.
The expected UX is clear, icons should change to white on black background...ie when hcb theme is applied.

**Comment by olshansky** [comment]
> Although Fundamental Styles covers this component, there is no example of this usecase.

@kavya-b there is no example of this usecase just because the examples have no input with the type "search".

@droshev could you please help to decide which option is right in this case?

**Comment by droshev** [comment]
@kavya-b @olshansky This component is kinda leftover and it is not the search field from Fiori 3.
I think the right approach is to introduce a proper search field in styles and the bring it in ngx

**Comment by manjunathanagaraj** [comment]
Its not affecting functionality, so we shall plan this work in one of the later sprints.

**Comment by olshansky** [comment]
We have the search field component as part of platform lib. So do we need this example in 'input group' at all? If yes, how should look it like? Unfortunately, I can't find a visual spec for this case _(Input Group with 'search' type)_.

**Comment by kavya-b** [comment]
@olshansky yeah, if search field were also in core, we could have just as well removed the search examples from Input Group. Even in Fundamental Styles Input Group, I don't see an example with search button either, so if the usecase for having it in Core no longer exists, we could remove it for now(right @droshev ?).

But I think like @droshev said [here](https://github.com/SAP/fundamental-ngx/issues/4231#issuecomment-758167778), we should probably look to bring in search field in Fundamental Styles, and then to ngx-core. Maybe a separate issue can be raised for this? 

Thoughts, @manjunathanagaraj ?

**Comment by genereg1** [comment]
I got some points about this issue

- Firstly, I don't think we should somehow support an input `[type=search]`, because Firefox doesn't support natively the clear search button. There only help a custom implementation as we did in search field component in platform.
- Secondly, we can overwrite a glyph of the native clear button in other browsers (Chrome, Safari), but the only way to do it is through `::-webkit-search-cancel-button` selector, where we can pass only `svg` icon in `background-url` property because use pseudoselectors like a `:after` and `:before` is no longer supported to overwrite the default glyph. So we can use only `svg` format of the icon and we'll need one icon for each of the themes that we support. It should work, but I don't like this solution

In general, I think we should get rid of this example in the input group component and create a separate custom implementation of the search field in core as we did in the platform. I don't know we actually need a search field in styles implementation. The input field styles will be enough.

Please let me know if it makes sense and what we are going to do with it, create a separate issue in styles and core or something else

**Comment by nickiovenko** [comment]
@droshev @InnaAtanasova Hello guys, could you please take a look at the comment from Evgeny above when you get a chance and let us know your thoughts? Thank you in advance! @genereg1
