### ISSUE TITLE
Formatted text. No extra styles should be applied to the links by default.

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4393]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Converted links have **text-decoration: none** style applied by default
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.26.0-rc.84
#### If this is a bug, please provide steps for reproducing it.
1. Open formatted text component
2. Scroll to output results. 
3. See link styles
AR: Links has **text-decoration: none** style applied by default, so the links are not underlined.
ER: Links have no extra styles applied by default. 
#### Please provide relevant source code if applicable.
<img width="1680" alt="formatted text links " src="https://user-images.githubusercontent.com/5969492/105103847-f02f1880-5ab9-11eb-9e50-230950c7efcb.png">

**Comment by mykolavorobiov** [comment]
@AntonOlkhovskyi It's not a bug.
`Formatted text` apply styles if you attach them to elements and can't reset them to default (because we don't know what's default for current element). And in this case style for link is using from parent box (docs styles).
Also any component can't replace styles with `!important` rule.
If you want to see clear component, you need to use clear sandbox without any additional styles from parent boxes.
