### ISSUE TITLE
Dynamic Page - Non-collapsible header hover style not correct

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-ngx#4495]
### Description

A non-collapsible header is set to `background: inherit` on hover, which means it's transparent.
So when the body background color is not white, one can still falsely see a kind of hover effect.

### Reproduce
1. Go to https://sap.github.io/fundamental-ngx/#/platform/dynamic-page
2. Open Example "Disable Header Collapse"
3. Via Browser console, set the body background color to something flashy
4. Hover over the dynamic page header and the header becomes transparent, thus letting through the body color.

https://user-images.githubusercontent.com/75482561/106002240-2ddf0300-60b1-11eb-8269-42cf54da700a.mov

### Expected behavior
The non-collapsible header should stay on the initial color on hover.

**Comment by puru-hk** [comment]
Teste it is working as expected.

**Comment by JKMarkowski** [comment]
Hello @mengbingguo Could you check if in your markup you have `transparent` value passed to `background` input anywhere? Otherwise there is no way that header is transparent.

**Comment by kavya-b** [comment]
Hi @JKMarkowski this is happening due to some styles that were added for non-collapsible header usecase in ngx that inherit the background value. I have removed it in #4515 and once that PR is merged, this issue should no longer occur. 
![image](https://user-images.githubusercontent.com/53509521/106595012-e9ec7200-6578-11eb-8d79-3ed55c549aaa.png)
