### ISSUE TITLE
Date/time Picker: Accessibility Issues

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4663]
Date/time picker accessibility issues 

Attached screenshot:

[Date.time.Picker.docx](https://github.com/SAP/fundamental-ngx/files/8697565/Date.time.Picker.docx)

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken status are below:


Issue1: Fixed
Issue2: Reproducible
Observed behaviour:
When accessing the data picker associated label is not read out.

Expected behaviour: 
When accessing the data picket associated label should read out.
Screenshot:
 


Issue3: Not reproducible

Issue4:
Observed behaviour:
The in-place label text does not meet the required ratio of 4.5:1

Expected behaviour:
The in-place label text should satisfy the required ratio of 4.5:1.
Screenshot:
 

Issue5: Fixed

Issue6:

Observed behaviour: 
When accessing the date picker associated label is not read out.

Expected behaviour: 
When accessing the date picker associated label should read out.
Screen shot;  
  
Issue7: fixed

Issue8:
Observed Behavior:
Ensure ARIA roles, states, and properties are valid


<button disabled="true" aria-controls="[object Object]" aria-expanded="false" tabindex="0" ng-reflect-disabled="true" ng-reflect-glyph="fob-watch" ng-reflect-compact="false" ng-reflect-fd-type="transparent" ng-reflect-type="button" class="fd-button fd-button--transparent is-disabled fd-input-group__button" fdtype="transparent" type="button" fd-button=""><div class="sap-icon--fob-watch ng-star-inserted" ng-reflect-glyph="fob-watch" role="presentation"></div></button>
This BUTTON has an aria-controls attribute value of '[object Object]', which includes one or more invalid or duplicate ids
Expected behavior:
Developers must use valid markup and follow the rules of the ARIA specification.

![Uploading image.png…]()

Issue9:Fixed
Issue10: Fixed
Issue11:Fixed
Issue12:Not reproducible
Issue13:Fixed.
Issue14: Fixed.

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken results are below.

Issue1: Fixed
Issue2: Fixed
Issue3: Fixed
Issue4: Fixed
Issue 5:
 Checkpoint: ACC-270.5
ACC-270

Observed Behaviour:
There are two tabs stop provided for the time picker element. On the first tab stop the keyboard focus is on the input field on the second tab stop the focus shifts to time picker button highlighted in red.
Screenshot:
 
![image](https://user-images.githubusercontent.com/105037808/174954305-f835fc57-d1e3-4fad-95d1-581838f76c18.png)

Expected Behaviour:
Ideally the single tab stop must be provided for the Date/time picker element and the ‘Date/Time Picker’ value help button must be activated through some keyboard shortcuts, thereby reducing the no of tab stops.
 
Issue6: Fixed
Issue7: Checkpoint: ACC-264.1
ACC-264

Observed Behaviour:
 On accessing the input field of the date time input field, the ‘Required’ and Association label Date and Passing Datetime through from object is not announced.

 
![image](https://user-images.githubusercontent.com/105037808/174954271-a321a5ca-c5b3-4ee0-9d6f-680cb3ea8d45.png)


![image](https://user-images.githubusercontent.com/105037808/174954251-28616939-5842-4817-8342-02591bc054dc.png)

 
Expected Behaviour:
Ideally, all visible content and association label, Required field should be conveyed to the user.

Issue8: Fixed

Issue9:
Checkpoint: ACC-264.1
ACC-264

Observed Behaviour:
 On accessing the input field of the date time picker, an additional information such as toggle button collapsed is announced.
Screenshot:
 
![image](https://user-images.githubusercontent.com/105037808/174954207-4759b2ac-86db-4c0d-8ed0-a09b9eb1dd11.png)



Expected Behaviour:
Ideally, such additional information must be removed and it will confuse the screen reader user.

Issue10:
Checkpoint: ACC-282.1
ACC-282

Observed Behaviour: 
 On adapting the screen to 320 pixels, the group header  (or) title is truncated.

 screenshot:
![image](https://user-images.githubusercontent.com/105037808/174954154-191dbc35-9ec0-4235-be12-6e197c8bfda3.png)

Expected Behaviour:
Ideally, the screen should get  adapted and there should be no loss of content.

Issue11: Partially fixed.
Checkpoint: ACC-282.1
ACC-282

Observed Behaviour: 
 On adapting the screen to 320 pixels, the ‘Cancel’ button is not fully visible.


Expected Behaviour:
Ideally, the ‘Cancel’ button should be fully visible to the user, the buttons should not removed when the screen adapt to the different screen mode. 

![image](https://user-images.githubusercontent.com/105037808/174954093-2a08ff9e-3acb-4868-a65f-d063934d21cb.png)

 


Issue12: Fixed

Issue13: Fixed

Issue14:Fixed

Issue15; Fixed

Issue16: Not reproducible 

Issue17: fixed

Issue 18:
 Checkpoint: ACC-264.1
ACC-264

Observed Behaviour: Screenshot
On accessing the ‘Calendar’ date the additional information such as contains Controls ; is read out.
Screenshot:
 
![image](https://user-images.githubusercontent.com/105037808/174954053-ca4b17a2-62a4-41f5-9480-d973023d7a0f.png)


Issue 19:
Checkpoint: ACC-260.2
ACC-260

Observed Behaviour:
On adapting the screen to 200% zoom, the ‘Cancel’ button is truncated to the side panel of the screen.

screenshot:
![image](https://user-images.githubusercontent.com/105037808/174953993-9c41dfb4-86c1-43b0-8356-3db607d9ca05.png)
 

Expected Behaviour:
Ideally, the UI shouldn’t get truncated, should be visible to the user.


Issue 20:
 Checkpoint: ACC-264.1
ACC-264

Observed Behaviour:
On accessing the ‘Date/Time picker’, any format of input can be entered [numerical, Alphabetic, special characters]. But there is no error indication for this
Screenshot:  
![image](https://user-images.githubusercontent.com/105037808/174953936-b258e31e-a468-471a-9f12-91e4a67d9af1.png)

Expected Behaviour:
User must be provided with a text description of the error, if input errors are detected automatically

Issue21: Fixed.

Retest environment: 
https://deploy-preview-8102--fundamental-ngx.netlify.app/#/core/datetime-picker
https://deploy-preview-8102--fundamental-ngx.netlify.app/#/platform/datetime-picker
Browser: Chrome Version 102.0.5005.115 (Official Build) (64-bit)
Screen reader: JAWS 2022.2204.20ILM

Regards,
Karthikeyan.c
