### ISSUE TITLE
Table accessibility issues

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4668]
Table accessibility issues

Attached the doc
[Table.docx](https://github.com/SAP/fundamental-ngx/files/5980083/Table.docx)

**Comment by platon-rov** [comment]
Can be relative: #5094.

**Comment by droshev** [comment]
@puru-hk Can you bring all the points from the doc here? It would help us push and process the issues further

**Comment by Sanjay-1312** [comment]
Issue 1: Fixed

Issue 2: Fixed

Issue 3: Fixed

Issue 4:
OB: The table two and count is not read on accessing the 2nd row from the field.
EB: The row and column count should be read when every table data cell is accessed.
![image](https://user-images.githubusercontent.com/78714518/126126042-88f5cd3b-2f00-4cdd-9c3d-30710624ecde.png)

Issue 5:
![image](https://user-images.githubusercontent.com/78714518/126126122-c5ac6e3b-e980-4d5a-b4d0-23f4d337d724.png)

OB: On activating the 'Sort' button, the dialog header 'Sort' is not read and the focus is available on the 'Cancel' button.
EB: The dialog name 'Sort' and the focus should be available on the first Active UI element of the dialog.
![image](https://user-images.githubusercontent.com/78714518/126126334-a0385ae4-7baf-4878-9f97-d369df69ec18.png)

issue 6: Fixed

Issue 7:
![image](https://user-images.githubusercontent.com/78714518/126126437-affccc3e-5a1b-4095-805f-4040595bc1a5.png)
![image](https://user-images.githubusercontent.com/78714518/126126469-5985a272-399c-480f-9960-7459ebebc319.png)
OB: The selected name is not read and visible label should be provided

issue 8: Fixed

Issue 9: Fixed


URL:https://deploy-preview-5692--fundamental-ngx.netlify.app/#/platform/table
JAWS 2021

**Comment by platon-rov** [comment]
@Sanjay,

Issue 4: https://github.com/SAP/fundamental-ngx/issues/3841#issuecomment-883130261

Issue 5: Relates to the dialog component. Cannot be resolved in the scope of the table component.

Issue 7: Relates to the select component. Cannot be resolved in the scope of the table component.

**Comment by Veerakarthick** [comment]
Hi Colleagues:
Retest has been taken below are the details:

Issue 4: #3841 (comment)
Issue5:Fixed
issue7:
OB: On accessing the 'Remove' and 'Add' button, the UI type is read first followed by the name of the UI element.
EB; The name of the UI and Type of the UI and Value of the UI must be read in following order
screen shot:
![image](https://user-images.githubusercontent.com/37998745/151784379-ea8c8fc3-b9da-4963-95d9-b11f9dce01ef.png)

etest Environment:
URL:https://deploy-preview-5692--fundamental-ngx.netlify.app
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
screen reader: Jaws2021,2111.13ILM.

Regards,
Karthikeyan.c

**Comment by Veerakarthick** [comment]
Hello colleague: 

below are the retest details:
3841:
Hello Colleague,

Retest has been taken below are the details.

issue1:
Description: On accessing the cells within the table as highlighted, column, row count information is not conveyed by the screen reader.

Expected: Count information shall be conveyed along with the UI information within the table.
screenshot:
![image](https://user-images.githubusercontent.com/37998745/151785772-4211ff07-2e62-477b-b966-185f07159d4f.png)

Retest Environment:
URL:https://deploy-preview-5692--fundamental-ngx.netlify.app
browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen Reader: Jaws2021.2111.13 ILM

4962:
issue3:
OB: On accessing the column row of second and remaining rows the count is not read.
EB: Ideally, the row and column count should be read to the user.
screen shot:
image

issue4:Fixed
Issue6:Fixed

Retest Environment:
URL:https://deploy-preview-5692--fundamental-ngx.netlify.app
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
screen reader: Jaws2021,2111.13ILM.

4668:
Issue 4: #3841 (comment)
Issue5:Fixed
issue7:
OB: On accessing the 'Remove' and 'Add' button, the UI type is read first followed by the name of the UI element.
EB; The name of the UI and Type of the UI and Value of the UI must be read in following order
screen shot:
image

etest Environment:
URL:https://deploy-preview-5692--fundamental-ngx.netlify.app
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
screen reader: Jaws2021,2111.13ILM.



Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken below are the test results:

issue1: Fixed

Issue2: Fixed

Issue3: Fixed

Issue4: Fixed

Issue5:
Observed behavior: when the 'Short' dialog gets open the information within the dialog is not read out.

Screenshot:
![image](https://user-images.githubusercontent.com/105037808/167601027-f26209dc-deee-4c10-ad69-3eea614a6ded.png)

Expected behavior: when the short dialog gets appear the dialog header information should read out to the user. 

issue6:
Observed behavior:
The list item within the drop down is not accessible via keyboard.

Screen shot;
![image](https://user-images.githubusercontent.com/105037808/167601266-50e21ca4-1978-408a-8873-d3da0bed4fdd.png)

Expected behavior:
The list item within the drop down should be accessible via keyboard.

Issue7;
Observed behavior:
When the drop down is accessed already selected values is not read out to the user.

Screenshot;
![image](https://user-images.githubusercontent.com/105037808/167601736-6fc9ce77-acaf-49cd-a291-f46c68381f77.png)

Expected behavior:
When the drop down get accessed information within the drop down should read out.


Retest Environment:
URL: https://deploy-preview-5692--fundamental-ngx.netlify.app/#/platform/table
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader; Jaws 2022.2204.20ILM

Regards,
Karthikeyan.c
