### ISSUE TITLE
Datetimepicker show wrong numbers with locale fa

### ISSUE THREAD

**Issue by Mohammadreza-Mohammadi** [SAP/fundamental-ngx#4860]
this is a bug.

when I change locale to fa in datetimepicker it shows wrong number in picker.but show right text in textfield.
this is a sample
https://stackblitz.com/edit/angular-nmdvup?file=src/app/calendar-i18n-example.component.ts

**Comment by aberikashvili** [comment]
@Mohammadreza-Mohammadi I checked this issue and I think provided description is not enough to understand what exactly do you consider as a bug. What I noticed, when I change locale to `fa`, it shows year `1400` instead of `2021`, which is correct (Solar Hirji year). 

Please provide more info about expected behavior

CC @droshev
