### ISSUE TITLE
Approval flow: select an approver and edit

### ISSUE THREAD

**Issue by wenyang33** [SAP/fundamental-ngx#4884]
After selecting an approver, if there is "Add button" in front and behind this approver, there should be "Add approvers before", "Add approvers after", "Add parallel approver", "Remove", and "Edit approver" in the toolbar.

In the demo, it only has: 
![image](https://user-images.githubusercontent.com/72157987/110412491-252f0480-8041-11eb-843b-cd389659af8a.png)

It should be:
![image](https://user-images.githubusercontent.com/72157987/110412512-2c561280-8041-11eb-8cc5-a614144cc912.png)

**Comment by maxym-valor** [comment]
Missed 'Edit popover' button in the toolbar. Should be 5 buttons: add before, add after, add add parallel, remove and Edit popover(missed)
![image.png](https://images.zenhubusercontent.com/60ab6fbc916bb95894fff44c/52f07356-50b3-4f13-892d-31ae3e89561d)

**Comment by platon-rov** [comment]
@wenyang33 fixed in the scope of Approval Flow Phase 3. Can be re-checked and closed.

**Comment by daisy-yovcheva** [comment]
Hi @platon-rov.

Small changes are needed:

The order of two of the buttons should be vice versa:
The fourth button should be: **Remove**
The fifth button should be "Edit approver", not only Edit.

**NGX:**
![Screen Shot 2021-06-10 at 3 35 07 PM](https://user-images.githubusercontent.com/72403541/121605925-1706d080-ca02-11eb-93c6-1089923511c7.png)

**How it should be:**
![Screen Shot 2021-06-10 at 3 40 10 PM](https://user-images.githubusercontent.com/72403541/121605947-271eb000-ca02-11eb-984c-5c59ebf30cc9.png)

Otherwise, it looks good.

Thanks,
Daisy

**Comment by puru-hk** [comment]
PR5749 is already merged. This can addressed in separate PR.

**Comment by mikerodonnell89** [comment]
- [ ] I feel like the + circles could be 1px higher
<img width="73" alt="Screen Shot 2021-08-03 at 2 21 35 PM" src="https://user-images.githubusercontent.com/2471874/128066393-86e10a4c-cf47-43e1-86ce-82522f19762b.png">

- [ ] There is too much padding here in RTL mode:
<img width="431" alt="Screen Shot 2021-08-03 at 2 22 56 PM" src="https://user-images.githubusercontent.com/2471874/128066692-7714206c-25f8-4728-97fe-a49b7a19053f.png">

- [ ] After clicking the checkbox to select someone the cursor changes from pointer to default, while still hovered over the checkbox
