### ISSUE TITLE
Accessibility: Table Phase-3 Component

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#4962]
Accessibility: Table Phase-3 Component
[Table_Platform_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6168977/Table_Platform_ARIBA.Controls.docx)
 (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:

**Comment by droshev** [comment]
Hi @Sanjay-1312, could you bring all the points as part the ticket so we can push the issues further?
Thanks

**Comment by surbhi175** [comment]
Issue 1: Fixed.
Issue 2: Fixed
Issue 3- Not Fixed
Now the Description input fields are not accessible using tab key.
Issue 4: Partially fixed
The additional information 'loading' is still read on navigating to the table.
The table name is still not read for tables within 'multiple row selection, Making row non-navigatable' headers.
Issue 5: Fixed
Issue 6: Issue still persists the same for all the tables.
Issue 7:Fixed

**Comment by Sanjay-1312** [comment]
Issue 8: Fixed

Issue 9: Fixed

Issue 10: Fixed

issue 11: Fixed

Issue 12: Issue still persists horizontal scroll bar are available.

issue 13: Fixed

Issue 14: Fixed

**Comment by Sanjay-1312** [comment]
Issue 3:
OB: On accessing the column row of second and remaining rows the count is not read.
EB: Ideally, the row and column count should be read to the user.
![image](https://user-images.githubusercontent.com/78714518/125912462-b993a7f8-0b84-4d83-982b-e4a20c1854d4.png)

Issue 4:
OB: The additional information 'loading' is still read on navigating to the table.
EB: The loading information should be removed.
![image](https://user-images.githubusercontent.com/78714518/125912595-4b217fb5-7e9e-449d-8dea-7f7b7bd32322.png)

Issue 6:
OB: The additional information 'loading' is still read on navigating to the table.
EB: The loading information should be removed.
![image](https://user-images.githubusercontent.com/78714518/125912836-5e2256df-0945-4f4b-ac8f-ee2e3add0548.png)

![image](https://user-images.githubusercontent.com/78714518/125912905-a297b20e-0fc7-47ba-b1ad-0f5605082964.png)
![image](https://user-images.githubusercontent.com/78714518/125912953-97e03e26-f6a2-4675-8710-b9de218c3a1e.png)
OB: On accessing the check box , the checkbox details should be read and on providing the extra navigation and additional information should be removed.
EB: On accessing the checkbox, the row and checkbox status and how to activate the checkbox should be read.

**Comment by platon-rov** [comment]
> Issue 3:
> OB: On accessing the column row of second and remaining rows the count is not read.
> EB: Ideally, the row and column count should be read to the user.

https://github.com/SAP/fundamental-ngx/issues/3841#issuecomment-881305660

> Issue 4:
> OB: The additional information 'loading' is still read on navigating to the table.
> EB: The loading information should be removed.

Related to the Busy Indicator component, cannot and should not be resolved in the table. Here is the issue #3112.

> Issue 6:
> OB: The additional information 'loading' is still read on navigating to the table.
> EB: The loading information should be removed.

Related to the Busy Indicator component, cannot and should not be resolved in the table. Here is the issue #3112.

> OB: On accessing the check box , the checkbox details should be read and on providing the extra navigation and additional information should be removed.
> EB: On accessing the checkbox, the row and checkbox status and how to activate the checkbox should be read.

Here is mine, multiple "not checked" text fixed.
![image](https://user-images.githubusercontent.com/20265336/125927460-de98b07e-8c42-46cc-b356-b3da468167ed.png)

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

OB: On accessing the table, the loading information is read and the on accessing the row checkboxes read as has controls.
and on pressing 'F2' button the checkbox can selected.
EB: The loading information shouldn't be read.
![image](https://user-images.githubusercontent.com/78714518/126113772-e5d7774a-69af-4eed-a191-2cc2d87326b9.png)

**Comment by platon-rov** [comment]
@Sanjay-1312 Loading isn't related to the table component but to busy-indicator. Appropriate issue created.

**Comment by Veerakarthick** [comment]
Hi Colleague,

Retest has been taken below are the test details.

issue3:
OB: On accessing the column row of second and remaining rows the count is not read.
EB: Ideally, the row and column count should be read to the user.
screen shot:
![image](https://user-images.githubusercontent.com/37998745/151783334-346333dc-c0b5-467c-bccb-963403fd4d6c.png)


issue4:Fixed
Issue6:Fixed

Retest Environment:
URL:https://deploy-preview-5692--fundamental-ngx.netlify.app
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
screen reader: Jaws2021,2111.13ILM.

Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken with the below environment results are below:

Issue1: Partially fixed.

Observed behavior:
The tale content are accessible via arrow key but the focus is trapped inside the table content user is not able to come out of it.

Screenshot:
![image](https://user-images.githubusercontent.com/105037808/167576330-0753dd5c-13bb-40d5-aefc-08dfd3ad1830.png)

Expected behavior:
The table content are accessible via keyboard keys and the user is able to come out of the table using tab key.

issue2: Fixed
Issue3: fixed
Issue4: Partially fixed.

Observed behavior:
The focus is not moving to the row selection data cell and the information within the data cell is not read out.

Screenshot:
![image](https://user-images.githubusercontent.com/105037808/167577738-49ec0730-56cd-47e5-b6ec-28f476969c2b.png)

Expected behavior:
The user is able to select the table row and the information within the table data cell should be read out.

issue5: Blocker

Observed behavior: User is not able to reach out the row row selection data cell.

screenshot:
![image](https://user-images.githubusercontent.com/105037808/167578099-32512e5f-4a84-447b-ac9d-298d183eda64.png)


Expected behavior: the user is able to reach out the row selection datacell with the help of keyboard keys.


issue6: Fixed

Issue7: Fixed

Issue8: Fixed

Issue9: Fixed

issue10: Fixed

Issue11: Not reproducible

Issue12: partially fixed.

Observed behavior: when the application is resized into 200% the content within the table is not fully visible.

Screenshot:
![image](https://user-images.githubusercontent.com/105037808/167581700-949ab77e-7a9e-49e5-9869-6a57b974a8e2.png)


Expected behavior:
When the application is resized into 200% all the content within the application should be accessible.

issue13: Fixed

Issue 14:

Observed behavior: The radio buttons are not selectable using arrow keys.

Expected behavior: The radio button within the group should be selectable (or) selectin can be change by using arrow keys.

Retest Environment:
URL:https://deploy-preview-5692--fundamental-ngx.netlify.app/#/platform/table
Component: Platform
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20ILM 

Regards,
Karthikeyan.c
