### ISSUE TITLE
Platform Dynamic Page markup needs refactoring

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#4972]
The Dynamic Page markup has been simplified and various issues had been addressed in styles. At the same time the core package released its implementation. It would be great if the platform implementation is revisited and reuse the implementation from core.

@manjunathanagaraj @kavya-b

**Comment by kavya-b** [comment]
@droshev working on this as part of Facet implementation since Facet example usage with dynamic page needs the new markup changes to also be brought in to platform dynamic page.

**Comment by droshev** [comment]
@kavya-b i think there should not be any blockers for this issue to be tackled

**Comment by kavya-b** [comment]
@droshev it would help if you could provide your thoughts on the comments in the closed PR [4997](https://github.com/SAP/fundamental-ngx/pull/4997#issuecomment-822341303).  It was marked `on hold` and WIP PR closed because we have been working on bugs for some time. Once we are done with this activity, probably this can be continued to work on again.
