### ISSUE TITLE
 Accessibility: Select

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5051]
Accessibility: Select Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Select_Platform_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6262285/Select_Platform_ARIBA.Controls.docx)

**Comment by droshev** [comment]
@Sanjay-1312 Could you update the title and detail info? I think you missed to attach the document.

**Comment by puru-hk** [comment]
issue fixed

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken results are below:

issue1:
observed behavior:
when accessing the dropdown associated label is not read out.

Expected behavior:
when accessing the drop down associated label should be provided.

Screenshot:
![image](https://user-images.githubusercontent.com/105037808/171378106-7273ce7e-44f7-48f6-b876-cb0377d09a81.png)

issue2: Fixed

issue3:  Fixed

issue4:  Fixed

issue5:  Fixed

issue6:  Fixed

issue7:  Fixed

Retest Environment:
URL:https://fundamental-ngx.netlify.app/#/platform/select
Browser: Chrome Version 102.0.5005.63 (Official Build) (64-bit)
Screen Reader: JAWs2022.2204.20ILM

Regards,
Karthikeyan.c
