### ISSUE TITLE
Develop injectors for Web Components

### ISSUE THREAD

**Issue by skocharian** [SAP/fundamental-ngx#5165]

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Isue4:
Observed Behavior:
The element type for More menu is not read precise on navigation. It is read as a button being a menu.
The speech output is:
overflow Button
To activate press spacebar.

Expected Behavior:
Ideally, the element type for all the Ui element should be read precise on navigation.
screenshot;
image

issue5:
Observed behavior: On traversing through the list, the list items are not read.
Expected behavior: The list count information should be read to the user.
screenshot:
image

issue8:
Observed Behavior:
On activating the ‘Open Notification’ ad ‘Open Notification Group’ and ‘Open from Component’ button, the dialog appears and there is no keyboard support provided for the ‘Open’ and ‘Close’ button, Once the keyboard support is provided the information about the dialog should be read.
Expected Behavior:
Ideally, all the associated functionality of an UI must be invokable using keyboard and mouse. Also, application shall be designed so end users can work with the keyboard alone, without requiring to use a mouse or a touch device.
Screenshot:
image

Issue9: Fixed.

Issue10:
Observed Behavior:
On accessing the ‘Close’ button, of the message strip information and its Type and UI information is not read for the user.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read
screenshot:

REgards,
Karthikeyan.c
