### ISSUE TITLE
Detached combobox dropdown on scroll

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#5187]
#### Is this a bug, enhancement, or feature request?
Scrolling the combobox after its dropdown is opened will detach the dropdown from the combobox.

https://user-images.githubusercontent.com/1498400/115843852-92df9600-a41f-11eb-9df5-609f5094ef18.mp4

#### Briefly describe your proposal.
I would expect the dropdown to keep its relative position to the combobox, when the combobox changes location.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@fundamental-ngx/core: 0.28.3
@angular/core: 11.1.0

#### If this is a bug, please provide steps for reproducing it.
see recording above

**Comment by Smiranin** [comment]
@desaroxx Could you provide more details? Maybe which input/output did you use or maybe did you have specific styles on parent container and so on? Because I couldn't reproduce it on v.0.28.3 and v.0.30.0. Checked it in [demo](https://sap.github.io/fundamental-ngx/#/core/combobox) and in other local project.

**Comment by dimamarksman** [comment]
@desaroxx are you using a parent container scroll, not a page scroll?
If so please try to add [cdk-scrollable](https://material.angular.io/cdk/scrolling/overview#cdkscrollable-and-scrolldispatcher) directive on this container.
