### ISSUE TITLE
form input message group: Inverter event triggers

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#5203]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
I would like to achieve:
onhover => show warning message
on "not" hover => hide warning message

In combination with opening the dropdown of a multi input the "mouseenter" "mouseleave" triggers get inverted.
So the message is showing, when it should not. And vice versa.

This unwanted behaviour can be seen here:

https://user-images.githubusercontent.com/1498400/116098269-385a6a00-a6ab-11eb-92ae-89dd42c9e6d7.mp4

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@fundamental-ngx/core: 0.28.0
@angular/core: 10.2.3

#### If this is a bug, please provide steps for reproducing it.

1. Go to example: https://stackblitz.com/edit/angular-erjb6z
2. select item from the drop down
3. deselect item
4. see that unwanted inversion happened

The folling screen capture show initial correct behaviour, then bad behaviour after executing steps describe above.

https://user-images.githubusercontent.com/1498400/116098811-a6069600-a6ab-11eb-9f33-47c38d836815.mp4

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-erjb6z

**Comment by dmitry-stepanenko** [comment]
Hi @desaroxx. We've found out that the fix that was made a while ago for your issue caused another bug. Now there's another fix https://github.com/SAP/fundamental-ngx/pull/8224, that provides an ability to configure whether specific trigger should apply both to open and close the popover or just one of them. This is not considered as a breaking change in general, but probably you will start seeing the same bug you've described above starting from v0.35. In order to fix this, you have to switch the `[triggers]="['mouseenter', 'mouseleave']" to `[triggers]="[ { trigger: 'mouseenter', openAction: true, closeAction: false }, { trigger: 'mouseleave', openAction: false, closeAction: true } ]"
