### ISSUE TITLE
Facets- Core

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5577]
Accessibility: Facets- Core  Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Facets_Core_ARIBA.Controls (1).docx](https://github.com/SAP/fundamental-ngx/files/6653752/Facets_Core_ARIBA.Controls.1.docx)

**Comment by kavya-b** [comment]
- [ ] _OB:The item count for the number of items available within the radio button is not read.
EB:Expected Behavior:
Ideally, on navigating within the items in the radio button, the item count should be read. i.e. if there are total 6 items and the focused is on the 1st item the information read should be, ‘1-star radio button  checked 1 of 6,  To change the selection press Up or Down Arrow’._
@puru-hk @Sanjay-1312  this issue is related to Rating Indicator component, please raise a separate issue for this

- [ ] _Also, the information ‘group’ is read twice._
This is expected, because the example is of all Facets in a Group, so the role `group` is applied to the rating indicator facet(since it is a group of title, subtitle, rating indicator and the dynamic text) and also to the facet group itself(since it is a group of all the facets), so it reads " `'Facet Group' group, 'Rating Indicator' group` "

- [ ] _On navigating to the contacts group, the text is read as a link and also the static text is included in the tab chain._
This is just an example for links, but I can remove the link from the name `John Miller` to make it more clear.

- [ ] _On navigating to the tabstrip available, the focus goes to each tab using tab key. i.e. once the user navigates to the tabstrips using tab key instead of navigating to the next element.
EB:
Ideally, on navigating to the tabstrip using tab key and on pressing tab again the focus should move out of the tabstrip and should not navigate to each tab within the same group. Once the focus is on the tab strip the items within the same group should be navigable using arrow keys._
Please explain this issue, I could not understand it with the screenshot. The Custom Facet example only has static content, so how is tab coming here? Also, please note, custom facet content is entirely custom and given by end-developer, there is no a11y we should be supporting here; it should ideally be handled by the end-developer. @puru-hk @Sanjay-1312

**Comment by Sanjay-1312** [comment]
Issue 1 :
The separate issue will be raised.

Issue 2:
OB: On navigating the contact information such as 'Contact name', 'Phone', 'Email' is not read and read as link.

Issue 3: 
![image](https://user-images.githubusercontent.com/78714518/122005283-12ac3000-cdd3-11eb-9716-217bc5d15e38.png)
The image facets doesn't have keyboard support and tool tip is provided.
Previous issue is not present

**Comment by kavya-b** [comment]
> Issue 1 :
> The separate issue will be raised.
> 
> Issue 2:
> OB: On navigating the contact information such as 'Contact name', 'Phone', 'Email' is not read and read as link.

Okay, associated label is missing here for the icons. Will fix.
> 
> Issue 3:
> ![image](https://user-images.githubusercontent.com/78714518/122005283-12ac3000-cdd3-11eb-9716-217bc5d15e38.png)
> The image facets doesn't have keyboard support and tool tip is provided.
> Previous issue is not present

Image Facet is dependent on Avatar component, and for tooltip https://github.com/SAP/fundamental-ngx/issues/5032 is already raised. 
For keyboard support, do you mean tab? The image facet is not interactive, so why should the facets be tabbable?

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

The issue is fixed.
Hence Closing the ticket.
Issue 1 : Separate ticket will be raised.

Issue 2 and 3 is fixed

URL:https://deploy-preview-5687--fundamental-ngx.netlify.app/#/core/facets
JAWS 2021

Thanks and Regards
Sanjay
