### ISSUE TITLE
Notifications -Core

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5579]
Accessibility: Notifications -Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:

[Notifications_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6662786/Notifications_Core_ARIBA.Controls.docx)

Application & Test Environment Details
Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/home
Web browser:	Google Chrome 91.0.4472.77
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2012.57.400

### Issue 1

Priority:	High
Checkpoint:	ACC-270

Within template as content notification header navigate to open notification button
Observed Behavior:
The ‘open notification’ button cannot be activated using keyboard.

Expected Behavior:
Ideally, all the UI elements should be accessible using keyboard.
Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/122226396-90effb80-ced3-11eb-8ef3-070ec6f3ea0f.png)

Case 2:
![image](https://user-images.githubusercontent.com/52071505/122226429-9a796380-ced3-11eb-908c-4b072bac9cf3.png)

### Issue 2

Priority:	High
Checkpoint:	ACC-264

Within notification group header, navigate to open notification group button and activate it. Navigate to the new messages
Observed Behavior:
On activating ‘open notification group’ button, information regarding the state of the button i.e. activated, pressed etc. is not read. i.e. on activating the button, the button gets activated and the list of elements is displayed below but the same information is not read.

Expected Behavior:
Ideally, the state on activating the button should be read by the screen reader. i.e. on activating the button either the focus should shift to the active section or the information ‘pressed’ or ‘activated’ should be read.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122226541-b4b34180-ced3-11eb-81be-8ef43949672b.png)

### Issue 3

Priority:	High
Checkpoint:	ACC-255

Navigate to the more menu.
Observed Behavior:
There is no tooltip or text alternative provided for the more menu.
The speech output is:
overflow Button  
To activate press spacebar.

Expected Behavior:
Ideally, a text alternative or tooltip should be provided for all the non textual elements and the same information should also be read by the screen reader on navigation.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122228351-60a95c80-ced5-11eb-80d1-3c907a23023d.png)

### Issue 4

Priority:	High
Checkpoint:	ACC-264

Navigate to the more menu.
Observed Behavior:
The element type for More menu is not read precise on navigation. It is read as a button being a menu.
The speech output is:
overflow Button  
To activate press spacebar.

Expected Behavior:
Ideally, the element type for all the Ui element should be read precise on navigation.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122228458-7cacfe00-ced5-11eb-9285-036aff3073e3.png)

### Issue 5
Medium
Priority:	
Checkpoint:	ACC-264

Navigate to the more menu and activate it. Navigate within the items available
Observed Behavior:
The item count for the items available within the More menu is not read on navigating within the items.
The speech output is:
Approve 
To move through items press up or down arrow.
Reject 
Forward

Expected Behavior:
Ideally, the item count for the items available within the menu should be read on navigation.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122228583-9e0dea00-ced5-11eb-96ff-5faa44ca082f.png)

### Issue 6

Priority:	High
Checkpoint:	ACC-264

Navigate to accept button within new messages (2) header
Observed Behavior:
On navigating to the buttons ‘accept all’, ‘close’, ‘accept’ etc., the group header and information regarding the related notification is not read. i.e. the related information about the notification is not read. Therefore, the group header and the related information is not associated to the buttons.
The speech output is:
Accept All Button  
To activate press spacebar.
close Button  
To activate press spacebar.
Accept Button  
To activate press spacebar.
close Button  
To activate press spacebar.
Accept Button  
To activate press spacebar.
close Button  
To activate press spacebar.

Expected Behavior:
Ideally, on navigating to the buttons, the group header should be read. Therefore, the group header should be associated to the buttons.
Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/122228707-be3da900-ced5-11eb-9c27-7e6799080dd3.png)

Case2:

![image](https://user-images.githubusercontent.com/52071505/122228751-c8f83e00-ced5-11eb-9b48-e1d03e2dfdc9.png)

### Issue 7

Priority:	Medium
Checkpoint:	ACC-260.4

Observed Behavior:
When resizing the screen to ‘Responsive Design’ (320) pixels, the horizontal scroll bar is available
Expected Behavior:
Ideally, the horizontal scroll bar must be removed to the user.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122228840-e0372b80-ced5-11eb-8bff-ffc37794eb68.png)

### Issue 8

Priority:	Medium
Checkpoint:	ACC-282.1

Observed Behavior:
When resizing the screen to ‘Responsive Design’ (320) pixels, the texts are out of the card layout.
Expected Behavior:
Ideally, the text must be adapted to the responsive design and should be within the card without loss of content.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122228937-f7761900-ced5-11eb-8c44-871a7b68ca74.png)

Priority:	High
Checkpoint:	ACC-270.1

Observed Behavior:
On activating the ‘Open Notification’ ad ‘Open Notification Group’  and ‘Open from Component’ button, the dialog appears and there is no keyboard support provided for the ‘Open’ and ‘Close’ button, Once the keyboard support is provided the information about the dialog should be read.
Expected Behavior:
Ideally, all the associated functionality of an UI must be invokable using keyboard and mouse. Also, application shall be designed so end users can work with the keyboard alone, without requiring to use a mouse or a touch device.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122229217-3015f280-ced6-11eb-8469-6449edf35f94.png)

### Issue 9

Priority:	High
Checkpoint:	ACC-270.1

Observed Behavior:
On activating the ‘Open Notification’ ad ‘Open Notification Group’  and ‘Open from Component’ button, the dialog appears and there is no keyboard support provided for the ‘Open’ and ‘Close’ button, Once the keyboard support is provided the information about the dialog should be read.
Expected Behavior:
Ideally, all the associated functionality of an UI must be invokable using keyboard and mouse. Also, application shall be designed so end users can work with the keyboard alone, without requiring to use a mouse or a touch device.

Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122229370-4ae86700-ced6-11eb-841a-d0a6159df7d5.png)

### Issue 10

Priority:	High
Checkpoint:	ACC-264.1

Observed Behavior:
On accessing the ‘Close’ button, of the message strip information and its Type and UI information is not read for the user.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122229452-618ebe00-ced6-11eb-9ecd-39dfa182e5b1.png)

### Issue 11

Priority:	Medium
Checkpoint:	ACC-264.1

Observed Behavior:
On activating the ‘More’ menu button, the list item such as ‘Accept’ and Forward’ is activated, the toast message information is not conveyed to the user.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122229547-78cdab80-ced6-11eb-8994-bc4f4ba40aca.png)

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122229634-8daa3f00-ced6-11eb-8f15-2b6aa5f5e1bd.png)

### Issue 12

Priority:	Medium
Checkpoint:	ACC-264.1

Observed Behavior:
On activating the ‘Open Notification Group’ button, the tab such as ‘BY date’, ’By Type’ and ‘By Priority’ tab section additional information is read such as ‘To switch pages, press Control+PageDown.
Expected Behavior:
Ideally, all such additional information should be removed.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122229770-a7e41d00-ced6-11eb-821c-93132301244c.png)

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122229817-b29eb200-ced6-11eb-80fe-dd23b6a7548d.png)

### Issue 13

Priority:	Medium
Checkpoint:	ACC-270.5

Observed Behavior:
On activating the ‘Open Notification Group’ button, the tab such as ‘BY date’, ’By Type’ tab section, additional tab stop is provided to reach the selected tab section.
Expected Behavior:
Ideally, all such additional tab should be removed, On selecting the tab the focus should land on the respective selected details region.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122229915-ca763600-ced6-11eb-940a-75038e9895af.png)

### Issue 14

Priority:	Medium
Checkpoint:	ACC-264.1

Observed Behavior:
On activating ‘Open Notification Group’ button,  the dialog has ‘Expand and Collapse’ button, its associated label such as ‘New Messages(2)’ and ‘Today(2) is not read to the user.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122230019-e1b52380-ced6-11eb-97bc-bc070afb0c3e.png)

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122230061-ebd72200-ced6-11eb-86ab-4ea8ccddde64.png)

### Issue 15

Priority:	Medium
Checkpoint:	ACC-264.1

Ensure ARIA roles, states, and properties are valid
 
Code Snippet:
<div aria-expanded="false" aria-controls="fdp-search-field-menu-14" class="fdp-search-field__input-group fd-input-group" aria-haspopup="true"><span class="fd-input-group__addon fd-input-group__addon--button ng-star-inserted"><button class="fdp-search-field__category-button fd-input-group__button fd-button fd-button--menu" aria-haspopup="true"><span class="fdp-search-field__category-label ng-star-inserted">Category</span></button></span><input id="fdp-search-field-input-12" placeholder="Search" class="fdp-search-field__input fd-input fd-input-group__input ng-untouched ng-pristine ng-valid" type="search"><span class="fd-input-group__addon fd-input-group__addon--button ng-star-inserted"><button id="fdp-search-field-submit-13" class="fdp-search-field__submit fd-input-group__button fd-button fd-button--transparent" title="Submit"><div class="sap-icon--search" glyph="search" role="presentation"></div></button></span></div>
Observed Behavior:
The aria-expanded attribute is not allowed on this DIV
Expected Behavior:
Developers must use valid markup and follow the rules of the ARIA specification.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122230176-06a99680-ced7-11eb-96ea-4acc853a1b6f.png)

**Comment by manjunathanagaraj** [comment]
updated attachment details into description

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Isue4:
Observed Behavior:
The element type for More menu is not read precise on navigation. It is read as a button being a menu.
The speech output is:
overflow Button
To activate press spacebar.

Expected Behavior:
Ideally, the element type for all the Ui element should be read precise on navigation.
screenshot;
![image](https://user-images.githubusercontent.com/37998745/151792746-f7d9af8a-130e-43ec-b7f1-679f6472c98d.png)

issue5:
Observed behavior: On traversing through the list, the list items are not read.
Expected behavior: The list count information should be read to the user.
screenshot:
![image](https://user-images.githubusercontent.com/37998745/151793187-2566c46e-26c5-4555-a1c6-a3c214869ae8.png)

issue8:
Observed Behavior:
On activating the ‘Open Notification’ ad ‘Open Notification Group’ and ‘Open from Component’ button, the dialog appears and there is no keyboard support provided for the ‘Open’ and ‘Close’ button, Once the keyboard support is provided the information about the dialog should be read.
Expected Behavior:
Ideally, all the associated functionality of an UI must be invokable using keyboard and mouse. Also, application shall be designed so end users can work with the keyboard alone, without requiring to use a mouse or a touch device.
Screenshot:
![image](https://user-images.githubusercontent.com/37998745/151793370-e860a7cf-21c3-4ada-94cf-ba1db8e3c17a.png)

Issue9: Fixed.

Issue10:
Observed Behavior:
On accessing the ‘Close’ button, of the message strip information and its Type and UI information is not read for the user.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read
screenshot:
![image](https://user-images.githubusercontent.com/37998745/151793858-58923e4f-35df-4131-81f0-f735508f1057.png)

Regards,
Karthikeyan.c

**Comment by dmitry-stepanenko** [comment]
@Veerakarthick you are using invalid URL to test. Please use links from deployed preview for each pull request. For example, to see these changes, you should use https://deploy-preview-7330--fundamental-ngx.netlify.app/ 

Each PR has a comment with a link for deploy preview https://github.com/SAP/fundamental-ngx/pull/7330#issuecomment-988026854
![image](https://user-images.githubusercontent.com/33101123/152559466-078fcb84-d107-4ed3-a606-6b8e06d1183d.png)


Also it might be more efficient to leave review comments on the PRs with actual changes, not on issues

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the updates.

Issue4: Fixed
Issue5:
Observed behavior: 
Observed Behavior:
The item count for the items available within the More menu is not read on navigating within the items.
The speech output is:
Approve 
To move through items press up or down arrow.
Reject 
Forward

Expected Behavior:
Ideally, the item count for the items available within the menu should be read on navigation.



screenshot:
![image](https://user-images.githubusercontent.com/37998745/155259558-5d274042-9bd9-4679-81ad-02a1f6a7e1c9.png)

Issue8:
Observed Behavior:
When resizing the screen to ‘Responsive Design’ (320) pixels, the texts within the card are truncate no alternative provided.
Expected Behavior:
Ideally, the text must be adapted to the responsive design and should be within the card without loss of content.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/155259343-f66d4b6e-da0d-450d-95ee-44ee37c3c17e.png)


Issue10:(Partially fixed)
 Observed Behavior:
On accessing the ‘Close’ button,  the message strip information  is not read for the user.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read

screenshot:
![image](https://user-images.githubusercontent.com/37998745/155259061-cadc07e6-d919-4095-8b70-b74b02367c19.png)

Retest Environment:
URL: https://fundamental-ngx-gh--pr7330-ds-5579-notification-sy1123d8.web.app/
Screen Reader: Jaws 2021.2111.13ILM
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)


Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello colleague,

Retest has been taken with the below environment and the results are below.

Issue 1: Fixed.
Issue 2: Fixed.
Issue 3: Fixed.
Issue 4: Fixed.
Issue5: Still reproducible

Observed behavior:
when activating the more button the item count for the list item is not read out.
screen shot:
![image](https://user-images.githubusercontent.com/105037808/167567777-fa4c5262-9537-4d67-b4cf-529cbbf5068f.png)


Expected behavior:
When the list item is accessed the item count should be read out.

issue 6 : Fixed
Issue 7: Fixed
Issue8:  Partially fixed.

Observed behavior: 
 when the application is switched into 320 CSS pixel, the text within the groups are truncated not alternative provided for the truncated text.
screen shot:
![image](https://user-images.githubusercontent.com/105037808/167568118-07327f24-81fe-4718-865a-3f111cfd907a.png)


Expected behavior:
When the application is switched into 320CSS pixel, all the content within the application should be visible clear and accessible.

Issue 9: Fixed.

Issue10: Partially Fixed.

Observed behavior:
when the close button within the message strip is accessed all the content within the group is read out.

Screenshot:
![image](https://user-images.githubusercontent.com/105037808/167568487-e71e80d9-12c8-4941-9c34-63cf735bd688.png)

Expected behavior:
When the close button within the message strip is accessed only the information within the message strip should read out.

Retest Environment:
https://deploy-preview-7330--fundamental-ngx.netlify.app/#/core/notification
Browser:Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20ILM

Regards,
Karthikeyan.c
