### ISSUE TITLE
bug(docs): playground broken accessibility for the comboboxes

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#5691]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

The list count in the combo, when accessed is not conveyed to the user, highlighted in red.

![image](https://user-images.githubusercontent.com/20265336/122269700-2bf1d100-cee6-11eb-8616-474370c4b2d4.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest.

#### If this is a bug, please provide steps for reproducing it.

Go to https://sap.github.io/fundamental-ngx/#/platform/table
Scroll down to the playground section.
Use JAWS to go over the comboboxes.

**Comment by puru-hk** [comment]
Issue is not fixed 
The position of the items in the combo box such as [1 of 4, 2of 4 and so on] must be read. On accessing the list item the list count is not read

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/32538291/128342283-30254428-39a0-4b0e-b141-8b1b40e2a606.png)

Expected behaviour:  The position of the items in the combo box such as [1 of 4, 2of 4 and so on] must be read.
