### ISSUE TITLE
Using FdDate and fd-date-picker sends to the server a date different from the date displayed in fd-date-picker

### ISSUE THREAD

**Issue by osherkramersap** [SAP/fundamental-ngx#5696]
I'm using FdDate and fd-date-picker in our app and I found an issue on them.
I found that displayed time is the same in any computer (not related where the computer located) but when the app sent the date to our servers it take the displayed time as local time and convert it to UTC (related to where the computer located - if the current displayed date is 6/14/2021 and my computer in Israel it will send it as 6/13/2021 at 21:00 and if my computer in US it will send it as 6/14/2021 at 04:00).
We want to display the current date and send the same date at 00:00 or another time from any location. Can you help me to find solution for that?

**Comment by aberikashvili** [comment]
Hi @osherkramersap, I checked this issue and figured out that component work properly, the problem you've described is related to timezone. When Date is converted to UTC and you get the difference. 

Here we have 2 solutions:
1. Use `.toDateString()` method instead of `.toDate()`, which will give the date without time in a particular format, for example:
```
@Component({
  selector: 'app-issue-5696',
  template: `
  <label fd-form-label for="datePicker">Date Picker</label>
  <fd-date-picker type="single" inputId="datePicker" [(ngModel)]="date"></fd-date-picker>
  <br/>
  <div>Selected Date: {{ date?.toDateString() || 'null' }}</div>
  <br/>
  <button fd-button (click)="sendRequest()">Send Request .toDateString()</button>
  `,
})
export class Issue5696Component {
  date = FdDate.getNow();

  constructor(private http: HttpClient) {}

  sendRequest(): void {
   const dateString = this.date.toDateString();
    this.http.post('/', {
      bday: dateString,
    }).subscribe(data => {
      // handle response
    });
  }
}
```
2. In case if your backend required specific formatting, you can use `moment.js`:
Install moment using `npm install --save moment`. Import into your component `import * as moment from 'moment';` and format date before sending to the backend:
```
sendRequest(): void {
    const customFormatPlaceholder = 'DD-MM-YYYY';
    const dateString = this.date.toDateString();
    const formattedDateString = moment(dateString).format(customFormatPlaceholder);

    this.http.post('/', {
      bday: formattedDateString,
    }).subscribe(data => {
        // handle response
    });
  }
```
