### ISSUE TITLE
bug: core, platform - unit tests are failing if ivy is disabled

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#5742]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
If diaable ivy in tsconfig.spec.json, then majority of the tests will fail with different errors like `Type ApprovalFlowAddNodeComponent is part of the declarations of 2 modules`, etc. https://gist.github.com/N1XUS/19c6e242f5eb7bab762dc2d655120e01
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.31
#### If this is a bug, please provide steps for reproducing it.
1. open libs/platform/tsconfig.spec.ts
2. add ```    "angularCompilerOptions": {
      "enableIvy": false
    }``` to the config
3. Run `ng test platform`

**Comment by kavya-b** [comment]
several tests are failing in both core and platform and will need to be worked on by both teams. Since these are unit tests and probably won't happen on end-user apps, is it a release blocker or can it be picked later, @droshev ?
<img width="918" alt="Screenshot 2021-07-20 at 3 05 11 PM" src="https://user-images.githubusercontent.com/53509521/126299251-c0dc9bbc-61fd-4fd4-8c25-ba1846f062f4.png">
<img width="1059" alt="Screenshot 2021-07-20 at 3 04 57 PM" src="https://user-images.githubusercontent.com/53509521/126299269-5d56d273-ac0e-497b-b086-2934c7c27935.png">

cc: @manjunathanagaraj

**Comment by olshansky** [comment]
A lot of test failing in core and platform with `"angularCompilerOptions": { "enableIvy": false }` in v0.31.0-rc.140
I've started working on fixing it but need to switch.
If someone would like to pick it up and continue fixing tests, could continue in the [fix/tests-for-ivy](https://github.com/SAP/fundamental-ngx/tree/fix/tests-for-ivy) branch
