### ISSUE TITLE
Bug: (core) Time-picker: for formatting example time value in the input should 00:00:00 instead 24:00:00

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5750]
#### Is this a bug, enhancement, or feature request?
Bug
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/timePicker
2. Scroll to Time parsing/formatting example
3. In the input set value '12:00 AM'
4. Press Enter
Expected result: in the input value is '00:00:00', Selected time under input is the same
Actual result: in the input value is '24:00:00', Selected time under input is '00:00:00'
![Запись_экрана_2021-06-23_в_16 44 24](https://user-images.githubusercontent.com/83698366/123107765-80470480-d442-11eb-8e47-dae2a9e9f51a.gif)

**Comment by kavya-b** [comment]
This is a known issue with the Intl.DateTimeFormat class. This example uses the option `hour12:false` :
![image](https://user-images.githubusercontent.com/53509521/125029810-cee1d900-e0a7-11eb-8825-d3f221353a37.png)

This option returns strange results at times, please take a look at this issue: [link](https://stackoverflow.com/questions/65604554/intl-datetimeformat-returns-an-hour-over-24)
The suggested solution to use the `hourCycle` option instead fixes this issue.

**Comment by puru-hk** [comment]
Tested in this url https://deploy-preview-5913--fundamental-ngx.netlify.app/#/core/timePicker it is working as expected.

**Comment by dimamarksman** [comment]
@puru-hk does this fix work in IE11?

The spec says that `hourCycle` is not supported by IE11

**Comment by kavya-b** [comment]
> @puru-hk does this fix work in IE11?
> 
> The spec says that `hourCycle` is not supported by IE11

@dimamarksman  ah, yes, I just checked and you're right that it doesn't look exactly the same. It shows `12:00:00 PM` initially(vs `12:00:00` in other browsers) and if we enter `12:00:00 AM`, it retains `12:00:00 AM` and shows `0h 0m 0s` in the selected time below:
![2021-07-15_09-39-32 (1)](https://user-images.githubusercontent.com/53509521/125727845-f2d6f352-c2d8-4eea-98a2-dfcf1402cb2b.gif)

However, with `hour12`, only IE works fine(no issue of showing `24:00:00`) but other browsers fail. `hourCycle` no longer shows `24:00:00` in any browser, and perhaps IE's handling logic ignoring `hourCycle` may be sufficient as it still shows `12:00:00 AM` at the least? If not, could you suggest what else can be done? Since `displayFormat` is specified by the end-app-user, I don't know if the ngx library logic can change anything. Maybe the end-app-user should use Moment to fix this?
