### ISSUE TITLE
Accessibility Testing_Core_Grid List

### ISSUE THREAD

**Issue by fanjum-acc** [SAP/fundamental-ngx#5774]
Hello Colleagues,

Please find attached issue document for control: Core_Grid List

[Grid List_Core_ARIBA_Controls_Part-1.docx](https://github.com/SAP/fundamental-ngx/files/6709129/Grid.List_Core_ARIBA_Controls_Part-1.docx)

[Grid List_Core_ARIBA_Controls_Part-2.docx](https://github.com/SAP/fundamental-ngx/files/6709134/Grid.List_Core_ARIBA_Controls_Part-2.docx)

[Grid List_Core_ARIBA_Controls_Part-3.docx](https://github.com/SAP/fundamental-ngx/files/6709143/Grid.List_Core_ARIBA_Controls_Part-3.docx)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken results are below.


Issue1:
Observed Behavior:

Text alternative is missing from images present within ‘None Mode’, ‘Single Select Mode’, ‘Single Select Left Mode’, ‘Single Select Right Mode’, ‘Multi Select Mode’, ‘Delete Mode’, ‘States’, ‘Status’, ‘More Button’, ‘Footer’, ‘Drag & Drop’ & ‘Layout’ sections and human icon present under ‘State: Locked’ group area within ‘State’ section

Expected Behavior:

Ideally, all the non-textual UI element and images should have clear and meaningful text alternative in the form of tooltip which will provide the necessary information to the user.


Screenshot:
Single Select Mode:
![image](https://user-images.githubusercontent.com/37998745/152106886-e6e67e96-4ad6-46f1-8fc3-a212c02eda9e.png)

Single Select Left Mode:
![image](https://user-images.githubusercontent.com/37998745/152106978-29062edd-cc16-4a24-b1ea-bc9b44c7a507.png)

Single Select Right Mode:
![image](https://user-images.githubusercontent.com/37998745/152106990-2fb4b092-278c-413e-a779-f4e4a85f9506.png)

Multi Select Mode:
![image](https://user-images.githubusercontent.com/37998745/152107020-eb16eafe-9f5f-4c3d-84f5-68d4919591ce.png)

Delete Mode:
![image](https://user-images.githubusercontent.com/37998745/152107095-f0b20a44-a92a-4dab-ab8b-a0c731ca6181.png)

Group:
![image](https://user-images.githubusercontent.com/37998745/152107160-50310bb3-3797-437c-a831-0c5c417efa92.png)

States:
![image](https://user-images.githubusercontent.com/37998745/152107233-312874d2-4b70-4044-a622-0a432b677fdf.png)

State Locked,State Draft:
![image](https://user-images.githubusercontent.com/37998745/152107272-ccd76e27-f63e-4eb5-8c77-3d8bb7443984.png)

Status:
![image](https://user-
images.githubusercontent.com/37998745/152107291-27c4cdfc-9e41-462a-b66b-c2e9e915c0ed.png)

More:
![image](https://user-images.githubusercontent.com/37998745/152107321-b8c7dfee-00e4-4061-b875-5a90ad4c2b80.png)

Footer:
![image](https://user-images.githubusercontent.com/37998745/152107344-d1d9a1c3-9bab-48d2-9266-69c62e23592d.png)

Drag and Drop:
![image](https://user-images.githubusercontent.com/37998745/152107369-ca02bb5d-7b95-407e-a259-d2deb6b6a11b.png)

Layout:
![image](https://user-images.githubusercontent.com/37998745/152107403-b7d952a9-a03b-4832-8dee-8f6d1dedfc26.png)

Focusing item Programmatically:
![image](https://user-images.githubusercontent.com/37998745/152107489-dcd0e8cf-2b10-4f80-ba7f-8f51f95f0503.png)

Case2:Automation issue: Fixed.

Issue2:

Screenshot:

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken with the below environment test results are below:

Issue1: Fixed.
Issue2: Fixed.
Issue3: Fixed.
Issue4: Partially fixed.

Observed behavior: 
Associated label has been provided but the label information is not read out by the screen reader.

Screen shot:
Single select left mode:
![image](https://user-images.githubusercontent.com/105037808/167800593-d114fb2d-65f8-4592-a893-740e2887cdda.png)

Single select right mode:
![image](https://user-images.githubusercontent.com/105037808/167800222-5c3dd8ac-31a9-41c3-820a-60c7cdd9a74b.png)

Multi select mode:
![image](https://user-images.githubusercontent.com/105037808/167800405-606c53ef-8ae8-40c0-ba1f-581df7384129.png)


Expected behavior:
When accessing the radio button, check box associated label should read out.

Issue5: Not Reproducible

Issue6: Fixed.

Issue7: Fixed.

Issue8: Still reproducible:

Observed behavior:
The list item within the groups are not accessible via Arrow key. only accessible via tab key.

Screenshot: 
![image](https://user-images.githubusercontent.com/105037808/167801584-62bd5132-38bf-4769-bbda-934a6c715da1.png)

Expected behavior: 
The list item within the group should be accessible via arrow keys.

issue9: Fixed.

Issue10: Fixed.

Issue11: Fixed.

Issue12: Fixed.


Retest Environment:

URL:https://deploy-preview-6568--fundamental-ngx.netlify.app/#/core/grid-list
Browser: Chrome Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS2022.2204.20ILM

Regards,
Karthikeyan.,c
