### ISSUE TITLE
avatar group bug in RTL

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5784]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Avatar group RTL - missing margin between text and icon in popover

![Screen Shot 2021-06-24 at 12 34 36 PM](https://user-images.githubusercontent.com/4380815/123300544-af17b600-d4e8-11eb-9f9e-d14e8e12bcd3.png)
![Screen Shot 2021-06-24 at 12 34 30 PM](https://user-images.githubusercontent.com/4380815/123300547-afb04c80-d4e8-11eb-897b-56ccb611ff74.png)

**Comment by Lokanathan-k** [comment]
hi @droshev, 

On analysis of the issue found that in the netlify URL the issue is not reproducible and the view of the avatar group has been Updated to the latest spec.


please find the attached screen shot.
<img width="1263" alt="Screenshot 2021-06-28 at 8 36 31 PM" src="https://user-images.githubusercontent.com/53534379/123659917-cc35e700-d850-11eb-94ed-debf8b683122.png">

**Comment by puru-hk** [comment]
As per Lok comment in the recent ngx version avatar group has been Updated to the latest spec. Hence closed
