### ISSUE TITLE
Alert icon in RTL

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5790]
#### Briefly describe your proposal.
- [ ] Alert icons disappearing when RTL is on

**RTL off**
![image](https://user-images.githubusercontent.com/3863691/118865529-15aa2280-b8f2-11eb-8c26-244f41633869.png)

**RTL on**
![image](https://user-images.githubusercontent.com/3863691/118865562-1f338a80-b8f2-11eb-9288-97929aeca5c8.png)

Icons are replaced with **.A**

**Comment by mikerodonnell89** [comment]
The issue with the ".A" isn't unique to our library
<img width="971" alt="Screen Shot 2021-07-16 at 3 57 45 PM" src="https://user-images.githubusercontent.com/2471874/126002195-65a04ced-d100-474a-8175-e081ca8362a0.png">

Icon is missing because ::after psuedo element is not present.  Works fine locally

**Comment by Betrozov** [comment]
can not reproduce
please recheck this issue

**Comment by maxym-valor** [comment]
Not reproducible anymore
![image](https://user-images.githubusercontent.com/83698366/132009065-63206d16-532b-4602-8a66-23c4e832dfdf.png)
