### ISSUE TITLE
Facets in RTL

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5793]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
RTL for counter looks odd 
![image](https://user-images.githubusercontent.com/6586561/118946085-bcc4a380-b95e-11eb-8a17-96068708473b.png)

**Comment by kavya-b** [comment]
@droshev please look at the comments on similar issues raised in Card component https://github.com/SAP/fundamental-ngx/issues/3418.
This should handled by the end-users since handling this at the lib/styles level will [mess up the RTL reading in RTL languages like Arabic](https://github.com/SAP/fundamental-ngx/issues/3418#issuecomment-700573734).
