### ISSUE TITLE
Accessibility Testing_Core_Toolbar

### ISSUE THREAD

**Issue by surbhi175** [SAP/fundamental-ngx#5806]
Hi Team,

Please find the error document attached for Core_Toolbar.
[Toolbar_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6713726/Toolbar_Core_ARIBA.Controls.docx)

Control Name: Core - Toolbar

1.1 Message Details
Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/toolbar
Technology:	Angular 11
Web browser:	Google Chrome 91.0.4472.77
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2012.57.400

 
Issue 1

Priority:	High
Checkpoint:	ACC-253

(253.1)
Observed Behavior:
Within ‘Tool bar Overflow’ header, there is no in placed label provided for ‘date time’ date and time picker. i.e. there is no in placed label regarding the format of the date for e.g. dd/mm/yyyy provided.

Expected Behavior:
Ideally, an in placed label regarding the format of the date and time input should be provided for the date and time picker field. i.e. the date format for e.g. dd/mm/yyyy should be provided.
Screenshot:
 
![image](https://user-images.githubusercontent.com/52071505/123941765-1b4a5c00-d9b8-11eb-8ae4-763358375e0b.png)

 
Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
Within Date time picker, on activating ‘select month’ or ‘select year’ buttons within the calendar, the information regarding the state of the button is not read. i.e. the information ‘pressed’ or ‘selected’ etc. is not read. Therefore, in both the cases when the button is activated or not the information read is the same. Also, the focus remains on the same button due to which the information that the button has been activated is not conveyed to the screen reader user.
The speech output is:
Select month Button  
To activate press spacebar.
Select year Button  
To activate press spacebar.

Expected Behavior:
Ideally, on activating the buttons the information ‘pressed’ or ‘selected’ should be read or the focus should move to the list available after activating ‘select month’ or ‘select year’ button.

Screenshot:
 
![image](https://user-images.githubusercontent.com/52071505/123941830-2ac9a500-d9b8-11eb-989a-2b8bf4a415fc.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On navigating within the calendar within date/time picker, on navigating to the date list the information regarding few days is read same. i.e. for Saturday and Sunday the same information ‘s’ is read, similarly for Tuesday and Thursday the same information ‘t’ is read which can be very confusing for a screen reader user.
The speech output is:
23
S
column 7 row 6
June 6, 2020 Contains Controls  
Select month
23
S
column 1 row 1
May 31, 2020 Contains Controls  
Previous monthSelect monthSelect yearNext month
M
June 1, 2020 Contains Controls  
T
June 2, 2020 Contains Controls  
W
June 3, 2020 Contains Controls  
T
June 4, 2020 Contains Controls 

Expected Behavior:
Ideally, a distinct and clear name for each day should be read by the screen reader on navigating within different days. i.e. a distinct name for e.g. sun for Sunday, mon for Monday, tue for Tuesday etc. should be read to avoid confusion.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/123941877-361cd080-d9b8-11eb-9e0e-0ffdb5fdd560.png)
 

 
Issue 4

Priority:	High
Checkpoint:	ACC-264
(264.1)

Observed Behavior:
Within the calendar, on navigating to the time field no information is read by the screen reader. Therefore, the time field is not accessible with assistive technology.

Expected Behavior:
Ideally, the information regarding the time field should be read by the screen reader on navigating to the time field.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/123941903-3fa63880-d9b8-11eb-9776-9161a3fbc171.png)
 

 
Issue 5

Priority:	High
Checkpoint:	ACC-270
(270.6)

Observed Behavior:
Within ‘toolbar overflow’ header, on activating ‘more’ menu, the items available within the menu cannot be accessed using keyboard. Therefore, the list is not accessible using keyboard.

Expected Behavior:
Ideally, all the UI elements should be accessible using keyboard. i.e. the user should be able to navigate within the ‘more’ menu list using keyboard.
Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/123941935-492fa080-d9b8-11eb-9b62-94cf71a5ff5d.png)

 
Case 2
![image](https://user-images.githubusercontent.com/52071505/123941970-50ef4500-d9b8-11eb-8477-23d2db954f2d.png)

 
Case 3
 
![image](https://user-images.githubusercontent.com/52071505/123941987-55b3f900-d9b8-11eb-8815-af08d442cd57.png)

 
Issue 6

Priority:	High
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
Within ‘toolbar overflow’ header, on activating ‘more’ menu, the state ‘expanded’ is not read. Therefore, the information that the menu has been expanded is not read by the screen reader.
The speech output is:
More button menu  
Press space to activate the menu, then navigate with arrow keys

Expected Behavior:
Ideally, on activating ‘more’ menu, the information ‘expanded’ should be read. i.e. the state regarding the UI element on activating the menu should be read by the screen reader.

Screenshot:
Case 1
 
![image](https://user-images.githubusercontent.com/52071505/123942022-5ea4ca80-d9b8-11eb-918e-d76d1a3b15aa.png)

Case 2
![image](https://user-images.githubusercontent.com/52071505/123942043-649aab80-d9b8-11eb-9eff-d6646008ad9d.png)
 

Case 3
 
![image](https://user-images.githubusercontent.com/52071505/123942070-69f7f600-d9b8-11eb-8ac2-f58b6d67f880.png)

 
Issue 7

Priority:	High
Checkpoint:	ACC-255
ACC-255.1

Observed Behavior:

Text alternative is missing from ‘Date-Time’ button and ‘Previous’, ‘Next’, ‘Up’ & ‘Down’ arrow buttons present under calendar field within ‘Toolbar Overflow’ section.
Expected Behavior:

Ideally, all the non-textual UI elements should have meaningful text alternative in the form of tooltip which provides information to the user.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/123942098-70866d80-d9b8-11eb-9cdd-5d8c119d563b.png)

 
 

Issue 8:

Priority:	High
Checkpoint:	ACC-271
ACC-271.1

Observed Behavior:

Dual focus is appearing within ‘Date & Time’ input field present within ‘Toolbar Overflow’ section.
Expected Behavior:

Ideally, all the UI should have single focus provided within screen. No UI should display dual focus in any of the element present within screen.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/123942353-ad526480-d9b8-11eb-8dd8-4024de4dea64.png)

 

Issue 9:

Priority:	High
Checkpoint:	ACC-273
ACC-273.2

Observed Behavior:

When user selects ‘2102-2121’ year range then selected year range appear, but visible focus lost. By 1-tab found on different UI element present within calendar field under ‘Toolbar Overflow’ section.
Expected Behavior:

Ideally, visible focus should retain on last opened Ui element and it should never switch to any other UI element present within screen.

Screenshot:
 
![image](https://user-images.githubusercontent.com/52071505/123942401-b9d6bd00-d9b8-11eb-99fb-62f6e18359e5.png)

Focus lost:
 
![image](https://user-images.githubusercontent.com/52071505/123942423-c0fdcb00-d9b8-11eb-839f-7269023a7261.png)

By 1-tab:
 
![image](https://user-images.githubusercontent.com/52071505/123942448-c5c27f00-d9b8-11eb-83e8-312f9504222c.png)

Issue 10:

Priority:	High
Checkpoint:	ACC-271
ACC-271.2

Observed Behavior:

Focus is not clear and not visible in the ‘Hours’, ‘Minutes’ & ‘Period’ input fields present within calendar field under ‘Toolbar Overflow’ section.
Expected Behavior:

Ideally, a strong four-sided visible focus should be available on all the UI elements present within screen.

Screenshot:
 
![image](https://user-images.githubusercontent.com/52071505/123942505-d2df6e00-d9b8-11eb-9fe3-f3652cc77fd3.png)

Issue 11:

Priority:	High
Checkpoint:	ACC-282
ACC-282.1

Observed Behavior:

“text” text present within ‘Toolbar Spacer’ sections displayed outside the visible area when screen is re-size to mobile responsive design i.e. 320 CSS Pixels.
Expected Behavior:

Ideally, all the UI element should present within the visible area when screen is re-size to mobile responsive design i.e. 320 CSS Pixels.

Screenshot:

100% screen:
 
![image](https://user-images.githubusercontent.com/52071505/123942557-e12d8a00-d9b8-11eb-99ed-fac46edccf12.png)

Responsive view:
 
![image](https://user-images.githubusercontent.com/52071505/123942582-e5f23e00-d9b8-11eb-8537-2ac441076958.png)

Issue 12:

Priority:	High
Checkpoint:	ACC-261
ACC-261.2

Observed Behavior:

“Info Active” text present within ‘Toolbar Types’ section does not satisfy minimum contrast ratio of at least 3:1 in default theme.
Expected Behavior:

Ideally, all the text present within screen should satisfy minimum contrast ratio of at least 3:1 in default theme.

Screenshot:
 
![image](https://user-images.githubusercontent.com/52071505/123942596-ebe81f00-d9b8-11eb-8512-305d1305fcc6.png)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

issue1:
Observed Behavior:
Within ‘Tool bar Overflow’ header, there is no in placed label provided for ‘date time’ date and time picker. i.e. there is no in placed label regarding the format of the date for e.g. dd/mm/yyyy provided.

Expected Behavior:
Ideally, an in placed label regarding the format of the date and time input should be provided for the date and time picker field. i.e. the date format for e.g. dd/mm/yyyy should be provided.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151789282-55f3a447-f79c-43ea-9a6b-6c11759427f1.png)

issue2:
Observed Behavior:
Within Date time picker, on activating ‘select month’ or ‘select year’ buttons within the calendar, the information regarding the state of the button is not read. i.e. the information ‘pressed’ or ‘selected’ etc. is not read. Therefore, in both the cases when the button is activated or not the information read is the same. Also, the focus remains on the same button due to which the information that the button has been activated is not conveyed to the screen reader user.
The speech output is:
Select month Button  
To activate press spacebar.
Select year Button  
To activate press spacebar.

Expected Behavior:
Ideally, on activating the buttons the information ‘pressed’ or ‘selected’ should be read or the focus should move to the list available after activating ‘select month’ or ‘select year’ button.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151789488-ca88246c-f455-4191-8ad8-a3f778294795.png)

issue3:fixed
issue4:fixed
Issue5:
Observed Behavior:
Within ‘toolbar overflow’ header, on activating ‘more’ menu, the items available within the menu cannot be accessed using keyboard. Therefore, the list is not accessible using keyboard.

Expected Behavior:
Ideally, all the UI elements should be accessible using keyboard. i.e. the user should be able to navigate within the ‘more’ menu list using keyboard.


screenshot:
![image](https://user-images.githubusercontent.com/37998745/151789889-4809a1f1-fce8-4abc-9825-8782881d6c15.png)

issue6:
Observed Behavior:
Within ‘toolbar overflow’ header, on activating ‘more’ menu, the state ‘expanded’ is not read. Therefore, the information that the menu has been expanded is not read by the screen reader.
The speech output is:
More button menu  
Press space to activate the menu, then navigate with arrow keys

Expected Behavior:
Ideally, on activating ‘more’ menu, the information ‘expanded’ should be read. i.e. the state regarding the UI element on activating the menu should be read by the screen reader.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151790063-e8498011-53ec-445e-8dd3-76e6d22dfc02.png)

issue7: Fixed
Issue8: Fixed
issue9: Fixed
Issue10:
Observed Behavior:

Focus is not clear and not visible in the ‘Hours’, ‘Minutes’ & ‘Period’ input fields present within calendar field under ‘Toolbar Overflow’ section.
Expected Behavior:

Ideally, a strong four-sided visible focus should be available on all the UI elements present within screen.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151790542-593f0fbb-3a69-471f-a187-350fb5110891.png)

issue11:
Observed Behavior:

“text” text present within ‘Toolbar Spacer’ sections displayed outside the visible area when screen is re-size to mobile responsive design i.e. 320 CSS Pixels.
Expected Behavior:

Ideally, all the UI element should present within the visible area when screen is re-size to mobile responsive design i.e. 320 CSS Pixels.


screenshot:
![image](https://user-images.githubusercontent.com/37998745/151790761-c49fe4bb-e465-499c-b4c0-41f67de33e94.png)


issue12:Fixed.

Regards,
Karthikeyan.c

**Comment by Veerakarthick** [comment]
Hello   Colleague,  
Retest has been taken below are   the details.   

issue1: fixed   
issue2:fixed   
issue3:fixed   
issue4:fixed   
Issue5:   Observed Behavior:   Within ‘toolbar overflow’ header, on activating ‘more’ menu, the items   available within the menu cannot be accessed using keyboard. Therefore, the   list is not accessible using keyboard.   Expected Behavior:   Ideally, all the UI elements should be accessible using keyboard. i.e. the   user should be able to navigate within the ‘more’ menu list using keyboard.   screenshot:     

issue6:   Observed Behavior:   Within ‘toolbar overflow’ header, on activating ‘more’ menu, the state   ‘expanded’ is not read. Therefore, the information that the menu has been   expanded is not read by the screen reader.   The speech output is:   More button menu   Press space to activate the menu, then navigate with arrow keys   Expected Behavior:   Ideally, on activating ‘more’ menu, the information ‘expanded’ should be   read. i.e. the state regarding the UI element on activating the menu should   be read by the screen reader.   screenshot:     

 issue7: Fixed   
Issue8: Fixed  
 issue9: Fixed   
Issue10:  
Observed Behavior:   Focus is not clear and not   visible in the ‘Hours’, ‘Minutes’ & ‘Period’ input fields present within   calendar field under ‘Toolbar Overflow’ section.   Expected Behavior:   Ideally, a strong four-sided   visible focus should be available on all the UI elements present within   screen.   screenshot:    

  issue11:Fixed.        
 issue12:Fixed.  

 Regards,  
 Karthikeyan.c




<div style='mso-element:para-border-div;border:none;border-bottom:solid windowtext 1.0pt;
mso-border-bottom-alt:solid windowtext .75pt;padding:0cm 0cm 1.0pt 0cm'>

<p class=MsoNormal align=center style='margin-bottom:0cm;text-align:center;
line-height:normal;border:none;mso-border-bottom-alt:solid windowtext .75pt;
padding:0cm;mso-padding-alt:0cm 0cm 1.0pt 0cm'><span style='font-size:8.0pt;
font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
display:none;mso-hide:all;mso-fareast-language:EN-IN'>Top of Form<o:p></o:p></span></p>

</div>

<div style='mso-element:para-border-div;border:none;border-top:solid windowtext 1.0pt;
mso-border-top-alt:solid windowtext .75pt;padding:1.0pt 0cm 0cm 0cm'>

<p class=MsoNormal align=center style='margin-bottom:0cm;text-align:center;
line-height:normal;border:none;mso-border-top-alt:solid windowtext .75pt;
padding:0cm;mso-padding-alt:1.0pt 0cm 0cm 0cm'><span style='font-size:8.0pt;
font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
display:none;mso-hide:all;mso-fareast-language:EN-IN'>Bottom of Form<o:p></o:p></span></p>

</div>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>

**Comment by Karthickc1994** [comment]
Hello Colleague,
Retest has been taken below are the details.
issue1: fixed
issue2:fixed
issue3:fixed
issue4:fixed
Issue5: Observed Behavior: Within ‘toolbar overflow’ header, on activating ‘more’ menu, the items available within the menu cannot be accessed using keyboard. Therefore, the list is not accessible using keyboard. Expected Behavior: Ideally, all the UI elements should be accessible using keyboard. i.e. the user should be able to navigate within the ‘more’ menu list using keyboard. 
screenshot:
 
![image](https://user-images.githubusercontent.com/105037808/167399732-5aca5eef-7a3d-4c6a-8e47-6044a324c201.png)
![image](https://user-images.githubusercontent.com/105037808/167399746-068fe026-c03b-4e7e-b3a3-dc34efd8a94f.png)


 

issue6: Fixed
issue7: Fixed
Issue8: Fixed
issue9: Fixed
Issue10:
Observed Behavior: Focus is not clear and not visible in the ‘Hours’, ‘Minutes’ & ‘Period’ input fields present within calendar field under ‘Toolbar Overflow’ section. Expected Behavior: Ideally, a strong four-sided visible focus should be available on all the UI elements present within screen. screenshot:
 
![image](https://user-images.githubusercontent.com/105037808/167399776-cbe458ed-7876-4a0f-b4c7-9b9ed820780c.png)

issue11:Fixed.
issue12:Fixed.

Retest Environment:
URL: https://deploy-preview-7373--fundamental-ngx.netlify.app/
Browser:  Version 101.0.4951.54 (Official Build) (64-bit)
screen Reader; JAWS 2022.2204.20ILM


Regards,
Karthikeyan.c
