### ISSUE TITLE
bug (core): selected value should not empty for 'blank value' option

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5955]
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/split-menu-button
2. Scroll to the last example
2. Click on pre-last split menu
3. Choose first poin 'Option 1 with blank value'
Expected result: only icon and arrow button on split menu button, selected value - 'Option 1 with blank value'
Actual result: only icon and arrow button on split menu button, selected value - empty
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/125442915-ed48f755-f131-4f51-9e83-f94d64f95c32.png)
![image](https://user-images.githubusercontent.com/83698366/125442959-6159a34d-8359-4182-aa1f-2b0140c7a338.png)

**Comment by kavya-b** [comment]
@maxym-valor the example is trying to showcase an item selection with a blank value, that is why the `selected value` is coming blank. It is intentional. If you click on `Show code`, you will see that to illustrate this example, a blank value was specifically passed to `onItemSelect3('')`: 
![image](https://user-images.githubusercontent.com/53509521/125930449-12194f8e-3b61-4627-a7e2-3ac61329f1c8.png)
