### ISSUE TITLE
Bug: Accessibility Testing_Action_Bar_Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6092]
Accessibility: Action-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Action.docx](https://github.com/SAP/fundamental-ngx/files/6875405/Action.docx)

Issue 1

Priority:	High
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On accessing the ‘Save’ button, its associated texts are not read.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/126930246-4fac9032-69e8-471b-9063-fda6b395500e.png)
Case 2:
![image](https://user-images.githubusercontent.com/78714518/126930272-491f1faa-3da1-4473-9161-029bf71a5355.png)
Case 3:
![image](https://user-images.githubusercontent.com/78714518/126930284-5da7bcf2-384d-4397-bd75-41274d32459b.png)
Case 4:
![image](https://user-images.githubusercontent.com/78714518/126930299-b7a3d39c-67cd-45c9-b588-bcbfa72910e8.png)
Case 5:
![image](https://user-images.githubusercontent.com/78714518/126930320-25015eb9-b8d2-41ce-a096-9705b4e870e9.png)
Note: This issue persists throughout the control

  Issue 2

Priority:	Medium
Checkpoint:	ACC-255
(255.1)

Observed Behavior:
The text alternative or tooltip for the ‘More’ button, is not provided.
Expected Behavior:
Ideally, a text alternative for element should be given which fulfills the purpose of the content

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/126930419-27b545c4-5945-4318-af59-c05857752dec.png)

Issue 3

Priority:	High
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On accessing the ‘More’ button, its UI name ‘More’ is not read.
Expected Behavior:
Ideally, the name of the UI should be communicated to the user when accessed.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/126930464-9c6d35e9-18e0-4515-ad06-587dca805f01.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-283

(283.1)

Observed Behavior:
On resizing the screen to 320CSS pixels, the texts are truncated and Horizontal scroll is available.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/126930559-60e008c8-e7fe-48f5-b14e-c84dc4abd331.png)

Issue 5

Priority:	Medium
Checkpoint:	ACC-260

(260.4)

Observed Behavior:
On resizing the screen to 200% zoom, the horizontal scroll bar is available.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.

Screenshot:
In 200% zoom
![image](https://user-images.githubusercontent.com/78714518/126930617-d09050a7-eeca-4e33-bc8c-6fcb08ba10ac.png)
In 100% zoom
![image](https://user-images.githubusercontent.com/78714518/126930641-10255a96-8d69-49ff-9e16-2e9e905394cc.png)

**Comment by manu-kr** [comment]
There are total 5 issue adding estimate of 3 days

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Issue1:
Observed Behavior:
On accessing the ‘Save’ button, its associated texts are not read.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read.
screenshot:
![image](https://user-images.githubusercontent.com/37998745/151906584-b55b6397-8cf7-444a-8753-48543d4e4b26.png)

issue2:
Observed Behavior:
The text alternative or tooltip for the ‘More’ button, is not provided.
Expected Behavior:
Ideally, a text alternative for element should be given which fulfills the purpose of the content
Screenshot:
![image](https://user-images.githubusercontent.com/37998745/151906694-41f5e3a4-198a-4814-a9a9-f732eff54be5.png)

issue3:
Observed Behavior:
On accessing the ‘More’ button, its UI name ‘More’ is not read.
Expected Behavior:
Ideally, the name of the UI should be communicated to the user when accessed.
Screen shot:
![image](https://user-images.githubusercontent.com/37998745/151906796-9a1a10bd-285c-4dc5-b56c-a195ef935daa.png)

issue4:
Observed Behavior:
On resizing the screen to 320CSS pixels, the texts are truncated and Horizontal scroll is available.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.
screenshot:
![image](https://user-images.githubusercontent.com/37998745/151906863-1f9b7368-a0b9-4c30-9b49-6edd1d876089.png)

issue5: Partially fixed
Observed Behavior:
On resizing the screen to 200% zoom, text are truncated no alternative provided for the truncated text.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.

Screenshot:
![image](https://user-images.githubusercontent.com/37998745/151907004-c749db58-a700-40d0-94e8-d9b8031257c9.png)


Retest Environment:
URL:https://deploy-preview-7413--fundamental-ngx.netlify.app
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen reader: JAWS2021.2111.13 ILM




Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken with the below environment the test result's are below:

issue1: Fixed.
issue2: 
Observed behavior:
No text alternative provided for the 'More' button.

Expected behavior:
the icon button 'More' should have text alternative.

Screen shot:
![image](https://user-images.githubusercontent.com/105037808/167401832-612469d9-312c-4945-aff2-18894c22e27d.png)

issue3:
observed behavior:
When accessing the icon button 'More' name of the button is not read out.

expected behavior:
 When accessing the 'More' button name of the button should read out clearly.

Screenshot:
![image](https://user-images.githubusercontent.com/105037808/167401982-53fc8369-fc1a-48af-8344-3a5ec305b14d.png)


Issue4: Partially fixed.

Observed behavior; 
When the application is switched into 320 CSS pixel, the text is truncated.

Expected behavior: 
when  the application is switched into 320 CSS pixel, all the content within the application should be visible celar to the user.

Screen shot:

![image](https://user-images.githubusercontent.com/105037808/167402091-569c025d-3be3-44f4-b635-26e13e381ddd.png)
Issue 5: Fixed.

Retest Environment:
URL:https://deploy-preview-7413--fundamental-ngx.netlify.app/
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen reader: JAWS 2022.2204.20 ILM

Regards,
Karthikeyan.c

**Comment by genereg1** [comment]
Hello, @Karthickc1994 

- Seems like you reviewed the Action Bar component in the Core implementation. The PR fixes the issues in Platform implementation where issues 2 and 3 are fixed. Please make sure you choose the right component. We can create an issue related to the Action Bar Core accessibility issues and It will be fixed in a separate PR 
- Regarding Issue 4. I don't think we can somehow provide the expected behavior. The current solution provides string truncation if it doesn't fit on the screen well and it got a tooltip on hover which shows the user the whole string. We could let the string be fully visible, but it will be flattened by a narrow screen and break the component
