### ISSUE TITLE
Bug: Accessibility Testing_Core_Pagination

### ISSUE THREAD

**Issue by Aswathy94** [SAP/fundamental-ngx#6096]
Accessibility: Pagination-Core Component (There are couple of accessibility issues found while testing, so I have attached error document for you reference.)
[Pagination_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6877053/Pagination_Core_Ariba.Controls.docx)

Pagination- Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/pagination

Technology:	Angular 11
Version: 	V 0.31.0-rc.125
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Pagination’ from the left panel

Observed Behavior:

When the ‘page number’ is selected, the selected information ‘page 4 is selected’ not conveyed.
Expected Behavior:
The state ‘selected’ information should be conveyed when a page number is selected.
Screenshot:
![image](https://user-images.githubusercontent.com/87646619/126965642-8bf2c029-7320-4b85-b6be-a478fcaeb84e.png)

 

Note: The above reported issue persists with JAWS 2019 as well.

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Pagination’ from the left panel

Observed Behavior:

When the user is on the last page and upon accessing ‘next’ button in virtual pc mode, still the tutor message ‘To activate press spacebar’ is conveyed.
Expected Behavior:
When the user is on the last page and upon accessing ‘next’ button in virtual pc mode, the tutor message ‘To activate press spacebar’ is not required to be announced.

Screenshot:
![image](https://user-images.githubusercontent.com/87646619/126965691-4843f446-2c3c-4fe4-a558-5d1555e2a116.png)

 
Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Pagination’ from the left panel

Observed Behavior:

The information regarding the pages ‘Showing 1-15 of 50’, ‘showing 49-50 of 50’… are read out twice in virtual pc mode.
Expected Behavior:
The information regarding the pages ‘Showing 1-15 of 50’, ‘showing 49-50 of 50’… should read out only once in virtual pc mode.

Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126965725-3173eaff-d495-4b6e-8036-4ad65d88f812.png)

**Comment by kavya-b** [comment]
@Aswathy94 
issue 2: the same behaviour is also in UI5 https://sapui5.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button for the disabled button. Please check.  
This is a native behaviour of the button and cannot be fixed: 
![image](https://user-images.githubusercontent.com/53509521/127457049-b870d15a-c9b0-4d4d-a570-464f1b499f15.png)

issue 3: the second `Showing 1-15 of 50` is read along with `navigation region` because that is the label associated with the pagination(from left arrow `<` button) . The pagination is supposed to be associated to the label, so this is expected behaviour.

cc: @puru-hk @Sanjay-1312

**Comment by Aswathy94** [comment]
Hi Kavya,

As per the above reply the issue 2 and issue 3 are expected behavior. I will consider those issues as confirmed. Is there any update regarding the issue 1 here? Could you please check and let me know so that I can change the status accordingly.

Thanks & Regards,
Aswathy

**Comment by kavya-b** [comment]
Hi Aswathy,
Thanks for your quick reply. The first issue as i understand is that when we select, for example, page 2, it should say 'Page 2 selected' but is currently only announcing 'Page 2', right? 
I will work to fix this.

**Comment by Aswathy94** [comment]
Hi Kavya,

Yes you are correct. The state 'Selected' is not announced when any of the page is selected.

**Comment by kavya-b** [comment]
Hi Aswathy, 
Following the [w3 page](https://www.w3.org/TR/wai-aria-1.1/#aria-current), we use`aria-current` that is supposed to be added to navigation/pagination elements and not `aria-selected`(which announces 'Selected'). We are also using the `<nav>` element which [does not support `aria-selected`](https://www.w3.org/TR/wai-aria-1.2/#navigation): 

Would it be okay if it said `page 2, current page` rather than `page 2 selected`?

**Comment by Aswathy94** [comment]
Hi Kavya,

As per above reply **Page 2, current page** announcement is fine when a page is selected.

Regards,
Aswathy
