### ISSUE TITLE
Bug: Accessibility Testing_Core_Product Switch

### ISSUE THREAD

**Issue by Aswathy94** [SAP/fundamental-ngx#6098]
Accessibility: Product switch-Core Component (There are couple of accessibility issues found while testing, so I have attached error document for you reference.)
[Product switch_Core_Ariba controls.docx](https://github.com/SAP/fundamental-ngx/files/6877136/Product.switch_Core_Ariba.controls.docx)

Product switch- Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/product-switch
Technology:	Angular 11
Version: 	V 0.31.0-rc.125
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Product switch’ from the left panel

Observed Behavior:

On accessing the lists in virtual pc mode of the screen reader, there is an additional navigation is made with no speech.

Expected Behavior:
The additional navigation should be removed when the lists are accessed in virtual pc mode.

Screenshot 1:

 
![image](https://user-images.githubusercontent.com/87646619/126967054-7d99e870-2617-49bc-8c8f-b7442c6551c2.png)

 Screenshot 2:

![image](https://user-images.githubusercontent.com/87646619/126967126-8a6e205b-e5ee-4558-9b7a-a802846aaa84.png)

**Comment by dmitry-stepanenko** [comment]
This issue is not reproducible 

I can grab the text output only in russian, but JAWS pronounces everything correctly without any pauses or attempts to read blank items
![image](https://user-images.githubusercontent.com/33101123/144233186-4199c11a-d89f-469e-9514-150020dfa25d.png)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken reported issue still persis the same please check and do the needful.
Observed Behavior:

On accessing the lists in virtual pc mode of the screen reader, there is an additional navigation is made with no speech.

Expected Behavior:
The additional navigation should be removed when the lists are accessed in virtual pc mode


Screensot:
![image](https://user-images.githubusercontent.com/37998745/151913827-a69c11be-ccde-49d9-a98d-a4d29fb857f7.png)

Retest Environment:
URL:https://deploy-preview-7413--fundamental-ngx.netlify.app/#/core/product-switch
Browser:Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen Reader: JAWS2021.2111.13 ILM

Regards,
Karthikeyan.c
