### ISSUE TITLE
 Accessibility Testing_Platform_Step_Input

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6140]
Accessibility: Step_Input-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) 
Screenshot:
[Step_Input.docx](https://github.com/SAP/fundamental-ngx/files/6905141/Step_Input.docx)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

issue1:
Observed Behavior:
On accessing the ‘Default Number Step input’ input field, increasing and decreasing values are not read.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read.


screenshot:
![image](https://user-images.githubusercontent.com/37998745/151788005-cfdaa212-ea45-452a-b9f9-0f45e862f877.png)
issue2:
Observed Behavior:
On accessing the ‘Help’ button, information read out as 'this is tooltip to help' which is not given clear information to the user.
Expected Behavior:
when accessing the icon button clear valid information should read out,

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151788287-4ace020b-3a13-4905-a34a-ae1020b65858.png)
issue3: Fixed
Issue4:
Observed Behavior:
On accessing the ‘Help’ button, the focus doesn’t cover all four sides of the button.
Expected Behavior:
Ideally, a strong focus indication covering all 4 sides must be provided for all the UI elements so that end user can easily identify the place of focus on the screen.

screen shot:
![image](https://user-images.githubusercontent.com/37998745/151788683-a6037929-7884-413c-b263-d0c27d24246d.png)

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken the results are below:

All the issues are fixed with the below environment: 

QA approved.

Retest Environment:
URL: https://deploy-preview-7116--fundamental-ngx.netlify.app/
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20 ILM

Regards,
Karthikeyan.c
