### ISSUE TITLE
Accessibility_Testing_Menu_Button_Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6151]
Accessibility: Menu_Button -Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
 Screenshot:

[Menu_Button.docx](https://github.com/SAP/fundamental-ngx/files/6907129/Menu_Button.docx)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken status are below.

Issue1: Fixed
Issue2:
Observed Behavior:
On accessing the ‘Emphasized button, the same information about button is read twice.
Expected Behavior:
Ideally, every accessed UI and its associated information must be read only once.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151916808-fc37fd39-956c-4555-b9b3-78298bbba6b0.png)

issue3:Fixed
issue4: Still persist the same.
Observed Behavior:
On accessing the ‘Default button menu with long text’ button, additional information is read.
Expected Behavior:
Ideally, only relevant and visible information about the UI should be read out and such extra information should be removed.



screenshot:
![image](https://user-images.githubusercontent.com/37998745/151917150-95e3740a-aaec-4834-9724-2b60bdda1d67.png)

Retest Environment:
URL:https://deploy-preview-7413--fundamental-ngx.netlify.app/#/platform/menu-button
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen Reader: JAWS2021.2111.13 ILM

Regards,
Karthikeyan.c
