### ISSUE TITLE
Accessibility Testing - Core - Side Navigation

### ISSUE THREAD

**Issue by george861** [SAP/fundamental-ngx#6179]
Accessibility: Side Navigation -Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)

[Side Navigation_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6913209/Side.Navigation_Core_Ariba.Controls.docx)

Side Navigation - Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/panel

Technology:	Angular 11
Web browser:	Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Side Navigation’ from the left panel

Observed Behavior:
On accessing the list items such as links within the side navigation, the item count information is not conveyed. 

Expected Behavior:
On accessing the list items such as links within the side navigation, the item count information should be conveyed.
For example:
‘Link 1’ link 1 of 4 

‘Link 2’ link 2 of 4
Screenshot:
 
![image](https://user-images.githubusercontent.com/88019003/127782142-0e4cac79-fe3a-449d-886c-42acd90d6aec.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Side Navigation’ from the left panel

Observed Behavior:
On accessing list item such as ‘Link 1’within the ‘Header1’, the title ’Header1’ is not associated with the list item.
Speech:
NavigationRegion  
list  
with 5 items
Link 1 Link 

Expected Behavior:
On accessing list item such as ‘Link 1’within the ‘Header1’ for the first time, the title ’Header1’ should be associated with the accessed list item.

Screenshot:
![image](https://user-images.githubusercontent.com/88019003/127782147-c99d2041-d24e-40ff-b56e-90d23d84af7b.png)

 
Case 2
![image](https://user-images.githubusercontent.com/88019003/127782149-db0e8013-a0bb-479a-8141-0ff25c670ea4.png)
 

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Side Navigation’ from the left panel

Observed Behavior:
On accessing the list items within the side navigation, the state of the link is not conveyed as links such as ‘Link1’, ‘Link 3’ are disabled can’t be activated and on accessing the link ‘Link 2’ which is in state ‘Selected’, no information is conveyed about the state. 
Speech:
NavigationRegion  
list  
with 4 items
Link 1 Link  
Link 2 Link  
Link 3 Link 

Expected Behavior:
On accessing the list items within the side navigation, the state of the link should be conveyed as links such as ‘Link1’, ‘Link 3’ are disabled can’t be activated and on accessing the link ‘Link 2’ which is in state ‘Selectable’, the information should be conveyed about the state ‘selected’. 

NOTE: the issues persists in all similar Side Navigation UI elements

Screenshot:
![image](https://user-images.githubusercontent.com/88019003/127782182-e67430bf-75d9-445f-9742-9b650b92d15a.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Side Navigation’ from the left panel

Observed Behavior:
Case 1
On accessing the list item such as ‘Link 3’, No information is conveyed as the item can be expanded and upon using side arrow key, the list item ‘Link 3’ can be opened. 

Case 2
The state of the element such as the ‘expanded’ or ‘collapsed’ in which state it is that is not announced and also when navigated to next level of items for example ‘Link 2’, the level information should be given. 

Speech:
Link 3 
list  
with 4 items
Link 2 Link 

Expected Behavior:
The state of the element such as the ‘expanded’ or ‘collapsed’ should be conveyed and when navigated to next level of items, the level information should be conveyed along with the count on accessing the sub list item such as ‘Link 2’ within ‘Link 3’. 

For example:
NavigationRegion  
Navigation List Tree   
Tree Item 1 of 2 Item 1 Navigation List Tree Item closed    
To move through or expand items use the Arrow keys.
Tree Item 1 of 2 Item 1
open    
level 1
Tree Item 1 of 4 Sub Item 1
 

NOTE: the issues persists in all similar Side Navigation UI elements
For Example: Screenshot
 
![image](https://user-images.githubusercontent.com/88019003/127782196-72d4d5ab-6f09-4808-8512-1776a940f4ad.png)

Screenshot:
case 1
![image](https://user-images.githubusercontent.com/88019003/127782199-d2bcf06a-2eda-4678-afca-937e696bd54d.png)
case 2
![image](https://user-images.githubusercontent.com/88019003/127782205-20a9b964-6a37-42b0-91d7-4412e3fdebee.png)

 

 
Issue 5

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Side Navigation’ from the left panel
Observed Behavior:
On accessing the list item within the condensed side navigation, the name of the list item is not announced.

Speech:
NavigationRegion  
list  
with 4 items
Link 
Expected Behavior:    
On accessing any list item within the condensed side navigation, the name of the list item should be announced.
Screenshot 1 
 
![image](https://user-images.githubusercontent.com/88019003/127782237-a82509aa-9759-4cdf-9b99-b4f53e184a43.png)

Issue 6

Priority:	Medium
Checkpoint:	ACC-255

(255.1)

•	Search ‘Side Navigation’ from the left panel
Observed behavior:
No tooltip or text alternative is provided for the list items within the Condensed Side Navigation 
Expected Behavior:  
Appropriate tooltip or text alternative should be provided for the list items within the Condensed Side Navigation 

Screenshot 1 
 
![image](https://user-images.githubusercontent.com/88019003/127782239-27e89bca-5ff0-4cd3-ae95-f1b6e78d9d60.png)

Case 2
 
![image](https://user-images.githubusercontent.com/88019003/127782241-4837084f-a3ad-421c-85d2-7b9113141a3d.png)

Issue 7

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Side Navigation’ from the left panel
Observed behavior:
On accessing the list items within the Condensed Side Navigation, an additional link information is announced. 
Speech:
NavigationRegion  
list  
with 4 items
Link  
https://fundamental-ngx.netlify.app/#/core/side-navigation
Link  
https://fundamental-ngx.netlify.app/#/core/side-navigation

Expected Behavior:    
On accessing the list items within the any Side Navigation, No additional information should be announced. 
Screenshot 1 

![image](https://user-images.githubusercontent.com/88019003/127782247-f97b93ab-61f2-4677-991e-276a1697d748.png)

 

Issue 8

Priority:	High
Checkpoint:	ACC-264, ACC-270

(264.1) (270.3)

•	Search ‘Side Navigation’ from the left panel
Observed behavior:
On accessing the list item ‘Settings’, no information is conveyed and the list item ‘Settings’ can be expanded via pressing enter key but the items such as ‘Link 3’, ‘Link 1’ within the list box are not accessible via keyboard and no information about list opened is conveyed to the user.
Expected Behavior:    
On accessing the any list item, the information about the accessed item should be conveyed and the state information should also be conveyed as it can be opened or closed via keyboard 
the items from the list such as ‘Link 3’, ‘Link 1’ within the ‘Settings’ list box should be accessible via keyboard.
Screenshot 1 

![image](https://user-images.githubusercontent.com/88019003/127782251-d9ca5995-96e2-4d68-8336-4242cd64177a.png)

![image](https://user-images.githubusercontent.com/88019003/127782256-1d3d1c76-a3d3-4e8e-a85f-ac3dd57a5f62.png)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Issue1:
Observed Behavior:
On accessing the list items such as links within the side navigation, the item count information is not conveyed. 

Expected Behavior:
On accessing the list items such as links within the side navigation, the item count information should be conveyed.
For example:
‘Link 1’ link 1 of 4 

‘Link 2’ link 2 of 4

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151908799-2885580f-be2f-4eac-8659-812f0da08f1f.png)

Issue2:
Observed Behavior:
On accessing list item such as ‘Link 1’within the ‘Header1’, the title ’Header1’ is not associated with the list item.
Speech:
NavigationRegion  
list  
with 5 items
Link 1 Link 

Expected Behavior:
On accessing list item such as ‘Link 1’within the ‘Header1’ for the first time, the title ’Header1’ should be associated with the accessed list item.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151908874-0799abd6-1160-47d8-9a24-f40b56d981b0.png)

issue3:
Observed Behavior:
On accessing the list items within the side navigation, the state of the link is not conveyed as links such as ‘Link1’, ‘Link 3’ are disabled can’t be activated and on accessing the link ‘Link 2’ which is in state ‘Selected’, no information is conveyed about the state. 
Speech:
NavigationRegion  
list  
with 4 items
Link 1 Link  
Link 2 Link  
Link 3 Link 

Expected Behavior:
On accessing the list items within the side navigation, the state of the link should be conveyed as links such as ‘Link1’, ‘Link 3’ are disabled can’t be activated and on accessing the link ‘Link 2’ which is in state ‘Selectable’, the information should be conveyed about the state ‘selected’. 


screenshot:
![image](https://user-images.githubusercontent.com/37998745/151909376-b745247a-d24b-47a0-9021-80ae7877940c.png)

issue4:
Observed Behavior:
Case 1
On accessing the list item such as ‘Link 3’, No information is conveyed as the item can be expanded and upon using side arrow key, the list item ‘Link 3’ can be opened. 

Case 2
The state of the element such as the ‘expanded’ or ‘collapsed’ in which state it is that is not announced and also when navigated to next level of items for example ‘Link 2’, the level information should be given. 

Speech:
Link 3 
list  
with 4 items
Link 2 Link 

Expected Behavior:
The state of the element such as the ‘expanded’ or ‘collapsed’ should be conveyed and when navigated to next level of items, the level information should be conveyed along with the count on accessing the sub list item such as ‘Link 2’ within ‘Link 3’. 

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151910070-7b3b5800-b12a-44e9-9479-f4243393bd31.png)

issue5:
Observed Behavior:
On accessing the list item within the condensed side navigation, the name of the list item is not announced.

Speech:
NavigationRegion  
list  
with 4 items
Link 
Expected Behavior:    
On accessing any list item within the condensed side navigation, the name of the list item should be announced.

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151910315-6e490be8-f585-4ab7-a153-8d5d21e4b4d6.png)

Issue6:
Observed behavior:
No tooltip or text alternative is provided for the list items within the Condensed Side Navigation 
Expected Behavior:  
Appropriate tooltip or text alternative should be provided for the list items within the Condensed Side Navigation 


screenshot:
![image](https://user-images.githubusercontent.com/37998745/151910629-9eeda708-4dcb-42cd-adb8-43e912033f83.png)

Issue7: Fixed

Issue8:
OB: The 'Setting' icon button is not activatable using keyboard using 'Enter or space bar'.

Expected behavior: 
The icon button within the list item should be accessible via keyboard.

screen shot:
![image](https://user-images.githubusercontent.com/37998745/151911278-238fdb79-ed85-468f-83fa-162d4fc1d5e7.png)

Retest Environment:
URL"https://deploy-preview-7413--fundamental-ngx.netlify.app/#/core/side-navigation'
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen reader: JAWS2021.2111.13 ILM

Regards,
Karthikeyan.c

**Comment by Veerakarthick** [comment]
Hello Colleague,
Retest has been taken below are the details.
Issue1: Fixed
Issue2: Fixed
issue3:Fixed


issue4: Fixed

issue5:Partially fixed
Observed Behavior:
On accessing the list item within the condensed side navigation, the name of the list item read out thrise.
Speech:
 NavigationRegion  
Navigation List Menu Bar 
Tree Item Link 1 1 of 4 
Tree Item Link 1 1 of 4 
Tree Item Link 1 1 of 4 
To move through items press up or down arrow.
Tree Item Link 2 2 of 4

Expected Behavior:
On accessing any list item within the condensed side navigation, the name of the list item should be announced.
screenshot:
 
Issue6: Fixed

Issue7: Fixed

Retest Environment:
URL" https://deploy-preview-7341--fundamental-ngx.netlify.app/
Browser: Chrome Version 99.0.4844.84 (Official Build) (64-bit)
Screen reader: JAWS2021.2111.13 ILM
Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken  with the below environment status are below:

Issue1: Fixed.
Issue2: Fixed.
Issue3: Fixed.
Issue4: Fixed.
Issue5: Fixed.
Issue6: Fixed.
Issue7: Fixed.
Issue8: Fixed.

Retest Environment:
URL: https://github.com/SAP/fundamental-ngx/issues/6179
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20ILM

Regards,
Karthikeyan.c
