### ISSUE TITLE
Accessibility_Testing_Button_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6206]
Accessibility: Button-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:
[Button_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6920577/Button_Core_ARIBA.Controls.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-271

Observed Behavior:
No focus indication provided when Disabled State Button is accessed. 

The speech output is:
Disabled State Button  Unavailable  
To activate press spacebar.

Expected Behavior:
Ideally, clear dotted focus indication should be provided for each & every UI when accessed.  

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127947100-7b22e118-d378-4835-8c55-8a174fc1b425.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Color information about buttons is not read out when buttons are accessed. 

The speech output is:
Filter Button  
To activate press spacebar.
Filter Button  
To activate press spacebar.
Filter Button  
To activate press spacebar.
Filter Button  
To activate press spacebar.

Expected Behavior:
Ideally, color information such as success, warning, error, etc. should be conveyed when buttons are accessed. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127947129-1e83b40f-0f74-42ca-abe5-3a083a07170c.png)

Issue 3

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
Button looks emphasized. This ‘emphasized’ information about button is not read out when accessed. 

The speech output is:
Add to Cart Button  
To activate press spacebar.

Expected Behavior:
Ideally, the emphasized information about the UI should be conveyed.
 
Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127947175-87b530cb-3272-43bc-ac10-0ef9fa71324f.png)

Issue 4

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:

UI type menu button is not read out when menu buttons are accessed. 

The speech output is:
Add to Cart Button  
To activate press spacebar.
Add to Cart Button  
To activate press spacebar.
Add to Cart Button  
To activate press spacebar.
Filter Button  
To activate press spacebar.
Filter Button  
To activate press spacebar.
Filter Button  
To activate press spacebar.
Filter Button  
To activate press spacebar.
cart Button  
To activate press spacebar.
cart Button  
To activate press spacebar.
accept Button  
To activate press spacebar.
filter Button  
To activate press spacebar.
filter Button  
To activate press spacebar.
menu2 Button  
To activate press spacebar.

Expected Behavior:
Ideally, each & every UI should be read out based upon its type when accessed. 
Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127947219-a13e21d2-73e4-4d23-953a-4f1f0068011e.png)

Issue 5

Priority:	High
Checkpoint:	ACC-262

Observed Behavior:
Color indication provided for buttons is not visible in high contrast black and high contrast white theme. 

Expected Behavior:
Ideally, color indication should be adaptable to high contrast black and high contrast white themes. 

Screenshot 1:
![image](https://user-images.githubusercontent.com/88035260/127947246-1c3fd35d-4b9c-4e83-9a9c-b46f6d61c2af.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/88035260/127947261-290c0a5b-0ae7-4dfc-9bdd-2e22b8230e4c.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/88035260/127947276-5d8f7782-f57c-4c9d-9290-67ed63c62dcc.png)

Screenshot 4:
![image](https://user-images.githubusercontent.com/88035260/127947285-6a96ed30-8443-42c6-bc97-b46470463dcb.png)

Screenshot 5:
![image](https://user-images.githubusercontent.com/88035260/127947296-5db4b539-70ef-45e2-9aed-69017be0f660.png)

**Comment by InnaAtanasova** [comment]
@Wemitha1234 please provide more info regarding this:

"Expected Behavior:
Ideally, clear dotted focus indication should be provided for each & every UI when accessed."

We should not focus or access disabled elements. Please refer to the following:


As per MDN web docs "[The Boolean disabled attribute, when present, makes the element not mutable, focusable, or even submitted with the form. The user can neither edit nor focus on the control, nor its form control descendants. If the disabled attribute is specified on a form control, the element and its form control descendants do not participate in constraint validation. Often browsers grey out such controls and it won't receive any browsing events, like mouse clicks or focus-related ones.](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)", which is exactly what our example is doing. 

As for aria-disabled, this is what w3 says: "[Disabled elements might not receive focus from the tab order. For some disabled elements, applications might choose not to support navigation to descendants. In addition to setting the aria-disabled attribute, authors SHOULD change the appearance (grayed out, etc.) to indicate that the item has been disabled.](https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-disabled)"

`aria-disabled` is used for elements that do not natively support disabled. Button component supports natively disabled and should use is. img tag needs to use aria-disabled and be styled properly.

**Comment by Wemitha1234** [comment]
Hi Inna,

Yes that's correct, we should not focus or access disabled elements.
But in this case, the issue here is that, the 'Disabled state' button is focusable while tabbing when accessed in PC mode.
The disabled buttons should not be included in Tab chain. 
Kindly check.

Thanks & Regards,
Wemitha

**Comment by droshev** [comment]
Hi @Wemitha1234, what we tried to do is to show 2 options for the button: one where the focus can go and the user can understand that the button is there but disabled as it may depend on some data that is not filled in and another disabled button where the focus doesn't go. This are just documentation examples.

**Comment by droshev** [comment]
@Wemitha1234, regarding the Issue 5, this is implemented per design. The idea is that in HCB/HCW the semantic meaning should come from the labeling and not from the colors as the theme is design for ppl with issues recognizing the colors.
