### ISSUE TITLE
Accessibility_Testing_Menu_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6210]
Accessibility: Menu-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[Menu_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6920876/Menu_Core_ARIBA.Controls.docx)

Issue 1

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
Item count is not read when menu items are accessed. 
Also, information about icons within menu items is not read out. 

The speech output is:
Menu with icons button menu  
To activate press spacebar.
menu  
Option 1 
To move through items press up or down arrow.
Option 2 
Option 3

Expected Behavior:
Ideally, item count should be read out when menu items are accessed.  

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127954569-66f4c082-27dd-440d-a27d-a2f6fce451d2.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
For sub menu items item count is read out.
For main menu items, item count is not read. 

The speech output is:
Menu with submenu button menu  
To activate press spacebar.
menu  
Fruits sub menu  
To move through items press up or down arrow.
Vegetables sub menu  
Milk products sub menu  
Cheese sub menu  
1 of 2
Yogurts sub menu  
2 of 2
Greek 
1 of 2
Natural 
2 of 2

Expected Behavior:
Ideally, for sub menu items also, item count should be read out. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127954664-543081eb-3019-4c29-8b0b-006b21859a6d.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-270

Observed Behavior:
List items are not accessible via arrow keys. 

Tutor msg is read as To move through items press up or down arrow.
But menu items are accessible only via Tab key. 
Also, on opening the dialog, dialog header is not read out. 

The speech output is:
Open Mobile Menu button menu  
To activate press spacebar.
menu  
Fruits sub menu  
To move through items press up or down arrow.
Vegetables sub menu  
Milk products sub menu 

Expected Behavior:
Ideally, menu items should be accessible via arrow keys.  

Screenshot 1:
![image](https://user-images.githubusercontent.com/88035260/127954688-ba420e97-a927-4d51-978c-9a0ef8d531b5.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/88035260/127954697-45c602d7-43c0-4a30-a7b6-f9d8c0fb384d.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-270

Observed Behavior:
Dialog cannot be closed using escape key. 

Expected Behavior:
Ideally, dialog should be closable using escape key. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127954724-61970098-4729-4382-9dff-700bff961e25.png)

Issue 5

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for close button. 

The speech output is:
Leaving menus
BannerRegion  
close Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for non-text UI element. 

Screenshot:

![image](https://user-images.githubusercontent.com/88035260/127954742-481342e4-9b48-468b-be00-9ebba57caa93.png)

Issue 6

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for Back button. 

The speech output is:
Go to previous menu level: Vegetables Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for non-text UI element. 

Screenshot:

![image](https://user-images.githubusercontent.com/88035260/127954761-4c75365e-9cf0-418e-89e2-1579f86e51fa.png)

Issue 7

Priority:	Medium
Checkpoint:	https://wiki.wdf.sap.corp/wiki/display/Acc/ACC-283+Details

Observed Behavior:
Menu button names are truncated when text spacing is enabled.  

Expected Behavior:
Ideally, UI names should not be truncated when text spacing is applied.  

Screenshot 1:
![image](https://user-images.githubusercontent.com/88035260/127954795-f90f0985-f2ec-40cc-abdb-1291134af8db.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/88035260/127954803-bdc8815f-d1d3-42d1-a111-44c0bacb981b.png)

**Comment by dimamarksman** [comment]
Hi @Wemitha1234 !
Didn't get this statement `Menu button names are truncated when text spacing is enabled.`.
What does `text spacing is enabled` mean?

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Issue1: Fixed.
Issue2: Fixed.
Issue3: still reproducible.
Observed Behavior:
List items are not accessible via arrow keys. 
Tutor msg is read as To move through items press up or down arrow.
But menu items are accessible only via Tab key. 
Also, on opening the dialog, dialog header is not read out. 
Expected Behavior:
Ideally, menu items should be accessible via arrow keys.  

Screenshot:
![image](https://user-images.githubusercontent.com/37998745/151908039-6597c801-6694-46bf-88db-c1b5a1dd8e33.png)

issue4:
Observed Behavior:
Dialog cannot be closed using escape key. 

Expected Behavior:
Ideally, dialog should be closable using escape key. 

screenshot:
![image](https://user-images.githubusercontent.com/37998745/151908113-506f068c-988c-435f-8957-d7a60497f0bc.png)

Issue5:
Observed Behavior:
Text alternative defining the purpose of UI is not provided for close button. 

The speech output is:
Leaving menus
BannerRegion  
close Button  
To activate press spacebar.
Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for non-text UI element. 

![image](https://user-images.githubusercontent.com/37998745/151908162-c481619a-b9a3-4380-a70c-82d3274783c7.png)

issue6:Not reproducible.

Issue7:
Observed Behavior:
Menu button names are truncated when text spacing is enabled.  


Expected Behavior:
Ideally, UI names should not be truncated when text spacing is applied.  

Screenshot:
![image](https://user-images.githubusercontent.com/37998745/151908434-c9a2a396-e158-41fa-9dc3-a5eb170475bf.png)

Regards,
Karthikeyan.c

**Comment by Veerakarthick** [comment]
Hello   Colleague,  

Retest has been taken below are   the details.  

Issue1: Fixed. 
Issue2: Fixed.  
Issue3: fixed   
issue4: fixed      
Issue5: fixed         
issue6:Not reproducible.   
Issue7:   
Observed Behavior:   Menu button names are truncated when text spacing is enabled.  
Expected Behavior:   Ideally, UI names should not be truncated when text spacing is applied.   Screenshot:    

  Regards,  
 Karthikeyan.c
--




<div style='mso-element:para-border-div;border:none;border-bottom:solid windowtext 1.0pt;
mso-border-bottom-alt:solid windowtext .75pt;padding:0cm 0cm 1.0pt 0cm'>

<p class=MsoNormal align=center style='margin-bottom:0cm;text-align:center;
line-height:normal;border:none;mso-border-bottom-alt:solid windowtext .75pt;
padding:0cm;mso-padding-alt:0cm 0cm 1.0pt 0cm'><span style='font-size:8.0pt;
font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
display:none;mso-hide:all;mso-fareast-language:EN-IN'>Top of Form<o:p></o:p></span></p>

</div>

<div style='mso-element:para-border-div;border:none;border-top:solid windowtext 1.0pt;
mso-border-top-alt:solid windowtext .75pt;padding:1.0pt 0cm 0cm 0cm'>

<p class=MsoNormal align=center style='margin-bottom:0cm;text-align:center;
line-height:normal;border:none;mso-border-top-alt:solid windowtext .75pt;
padding:0cm;mso-padding-alt:1.0pt 0cm 0cm 0cm'><span style='font-size:8.0pt;
font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
display:none;mso-hide:all;mso-fareast-language:EN-IN'>Bottom of Form<o:p></o:p></span></p>

</div>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>
