### ISSUE TITLE
Accessibility_Testing_Standard List_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6222]
Accessibility: Standard List-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[Standard List_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6923001/Standard.List_Core_ARIBA.Controls.docx)

Issue 1

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
Selected state of the list item is not read immediately, also the selected state is not read while navigating between list items. 

Expected Behavior:
Ideally, the selected state should be read out when list items are accessed. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991441-294d8f2e-9d3d-4a15-93f0-238ac58fed70.png)

Issue 2

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
Information such as “has details” is not read out when list items are accessed. 
Also, blue color information about second list item is not read when accessed. 

Speech output is:
list  
with 4 items
Link List item 1   
1 of 4
To move to an item press the Arrow keys.
Link List item 2   
2 of 4
To move to an item press the Arrow keys.
List item 3   
3 of 4
To move to an item press the Arrow keys.
Link List item 4   
4 of 4
To move to an item press the Arrow keys.

Expected Behavior:
Ideally, the has details information about the list item should be read out and color information about list item should be read out. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991459-d1f0badb-1794-4313-bdb5-61529937c578.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Item count is read for group header also within list. 

Speech output is:
list  
with 8 items
List Item 1   
2 of 8
To move to an item press the Arrow keys.
List Item 2   
3 of 8
To move to an item press the Arrow keys.
List Item 3   
4 of 8
To move to an item press the Arrow keys.
List Item 2   
3 of 8
To move to an item press the Arrow keys.
List Item 1   
2 of 8
To move to an item press the Arrow keys.
List Group Header   
1 of 8
To move to an item press the Arrow keys.

Expected Behavior:
Ideally, item count should not be read for group headers.  

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991494-9cac884f-2fce-419f-8dfa-10caeb1b7116.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-271

Observed Behavior:
Focus indication is not provided when group header is accessed. 

Expected Behavior:
Ideally, focus indication should be provided for each & every UI when accessed. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991545-39ce40b0-ccb9-4ce5-8f55-5caff1fd91d3.png)

Issue 5

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Two-tab stops are provided when show more button is accessed. 

Speech output is:
Loading Show More   
7 of 8
To move to an item press the Arrow keys.
Loading Show More Button  
To activate press spacebar.

Expected Behavior:
Ideally, such extra tab stops should not be provided. 
Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991576-324f2794-ecf9-4da0-9431-ed3893ec484f.png)

Issue 6

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for buttons highlighted in red.  

Speech output is:
Button  
To activate press spacebar.
Button  
To activate press spacebar. 

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI. 

Screenshot:

![image](https://user-images.githubusercontent.com/88035260/127991607-80496e32-7b1a-4ec5-b477-4461c2f6d54e.png)

Issue 7

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
After pressing the buttons, information such as ascending/descending is not read. 

Speech output is:
Button  
To activate press spacebar.
Button 
To activate press spacebar. 

Expected Behavior:
Ideally, information such as ascending/descending should be conveyed. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991660-f27e42bb-4872-4aee-8685-219ac47ad95d.png)

Issue 8

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for decline Button. 

Speech output is:
decline Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991713-04aecf0c-e6b8-4c17-b837-18f4e2a7d5f4.png)

Issue 9

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for Buttons within the list. 

Speech output is:
list  
with 5 items
Apple   
1 of 5
To move to an item press the Arrow keys.
Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI. 

Screenshot:

![image](https://user-images.githubusercontent.com/88035260/127991789-960f0f10-871b-495e-9025-1a169bde3b1b.png)

Issue 10

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Group headers are not read out when list items are accessed. 

Speech output is:
list  
with 11 items
List item 1   
2 of 11
To move to an item press the Arrow keys.
List item 2   
3 of 11
To move to an item press the Arrow keys.
List item 3   
4 of 11
To move to an item press the Arrow keys.
List item 4   
5 of 11
To move to an item press the Arrow keys.
List item 5   
7 of 11
To move to an item press the Arrow keys.
List item 6   
8 of 11
To move to an item press the Arrow keys.
List item 7   
9 of 11
To move to an item press the Arrow keys.
List item 8   
10 of 11
To move to an item press the Arrow keys.

Expected Behavior:
Ideally, corresponding group headers should be read out. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991839-242cd51a-114f-4073-980d-d38bf63221c4.png)

Issue 11

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Loading information about Infinite scroll list is not read. 

Expected Behavior:
Ideally, loading information should be conveyed. 
Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127991882-0c34259a-7ece-476d-9013-49e3f7270a25.png)

Issue 12

Priority:	High
Checkpoint:	ACC-270

Observed Behavior:
Not possible to drag and drop list items via keyboard. 

Expected Behavior:
Ideally, it should be possible to drag and drop list items using keyboard. 

Screenshot:

![image](https://user-images.githubusercontent.com/88035260/127991931-357858fe-532b-49bd-8c4c-c9d151edb160.png)

**Comment by Veerakarthick** [comment]
Hi Colleague,

Retest has been taken status are below:

issue1:Partally fixed
Observed Behavior:
When accessing the list items state selected is read out but the user is not able to select the list item using 'Space bar (or) Enter key.

Expected Behavior:
Ideally, the user should be able to select the list item using the keyboard keys.
screenshot:
![image](https://user-images.githubusercontent.com/37998745/152917494-fb890070-1dd4-4de1-9a20-29e1407d6abf.png)

Issue2: Not Reproducible

Issue3:
Observed Behavior:
Item count is read for group header also within list.

Expected Behavior:
Ideally, item count should not be read for group headers.
Screenshot:
![image](https://user-images.githubusercontent.com/37998745/152920238-cc66c2c2-37ba-4013-b9e9-395bbb26e630.png)

Issue4: Fixed.

Issue5: Fixed.

Issue6:
Observed Behavior:
Text alternative defining the purpose of UI is not provided for buttons highlighted in red.

Speech output is:
Button
To activate press spacebar.
Button
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI.
Screenshot:
![image](https://user-images.githubusercontent.com/37998745/152920608-cad2839b-8e67-427d-88ad-d3b5585249b9.png)

Issue7:
Observed Behavior:
After pressing the buttons, information such as ascending/descending is not read.

Speech output is:
Button
To activate press spacebar.
Button
To activate press spacebar.

Expected Behavior:
Ideally, information such as ascending/descending should be conveyed.

Screenshot:
![image](https://user-images.githubusercontent.com/37998745/152921344-e0a2c6d8-b85b-4918-8381-b1305ad74333.png)


Issue8: Fixed.

Issue9:
Observed Behavior:
Text alternative defining the purpose of UI is not provided for Buttons within the list.

Speech output is:
list
with 5 items
Apple
1 of 5
To move to an item press the Arrow keys.
Button
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI.

Screenshot:
![image](https://user-images.githubusercontent.com/37998745/152921618-50aba22b-2ffd-45d0-ac00-368c824b304d.png)

issue10:
Observed Behavior:
Group headers are not read out when list items are accessed.

Speech output is:
list
with 11 items
List item 1
2 of 11
To move to an item press the Arrow keys.
List item 2
3 of 11
To move to an item press the Arrow keys.
List item 3
4 of 11
To move to an item press the Arrow keys.
List item 4
5 of 11
To move to an item press the Arrow keys.
List item 5
7 of 11
To move to an item press the Arrow keys.
List item 6
8 of 11
To move to an item press the Arrow keys.
List item 7
9 of 11
To move to an item press the Arrow keys.
List item 8
10 of 11
To move to an item press the Arrow keys.

Expected Behavior:
Ideally, corresponding group headers should be read out.

Screenshot:
![image](https://user-images.githubusercontent.com/37998745/152922148-a8adbd02-d9cf-4f3d-9387-204aeb18762e.png)

Issue11: Fixed.

Issue12:
Observed Behavior:
Not possible to drag and drop list items via keyboard.

Expected Behavior:
Ideally, it should be possible to drag and drop list items using keyboard.
screenshot:
![image](https://user-images.githubusercontent.com/37998745/152922514-de48edc2-99f6-4e9c-a0e3-6ee8506d6ffb.png)


Retest Environment:
URL: https://deploy-preview-7308--fundamental-ngx.netlify.app/
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen Reader: JAWS 2021.2111.13 ILM

Regards,
Karthikeyan.c

**Comment by Veerakarthick** [comment]
Hello Colleague,

The component is belong to 'Core' component and the results are below:

issue1: Fixed
Issue2: Not Reproducible
Issue3:
Observed Behavior:
Item count is read for group header also within list.
Expected Behavior:
Ideally, item count should not be read for group headers.
Screenshot:
 
Issue4: Fixed.
Issue5: Fixed.
Issue6:
Observed Behavior:
Text alternative defining the purpose of UI is not provided for buttons highlighted in red.
Speech output is:
Button
To activate press spacebar.
Button
To activate press spacebar.
Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI.
Screenshot:
 
Issue7:
Observed Behavior:
After pressing the buttons, information such as ascending/descending is not read.
Speech output is:
Button
To activate press spacebar.
Button
To activate press spacebar.
Expected Behavior:
Ideally, information such as ascending/descending should be conveyed.
Screenshot:
 
Issue8: Fixed.
Issue9:
Observed Behavior:
Text alternative defining the purpose of UI is not provided for Buttons within the list.
Speech output is:
list
with 5 items
Apple
1 of 5
To move to an item press the Arrow keys.
Button
To activate press spacebar.
Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI.
Screenshot:
 
issue10: Fixed

Issue11: Fixed.
Issue12:
Observed Behavior:
Not possible to drag and drop list items via keyboard.
Expected Behavior:
Ideally, it should be possible to drag and drop list items using keyboard.
screenshot:
 
Retest Environment:
URL: https://fundamental-ngx-gh--pr7308-ds-6222-standard-lis-n5r0ii9f.web.app/
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen Reader: JAWS 2021.2111.13 ILM

Regards,
Karthikeyan.c

**Comment by Veerakarthick** [comment]
Hello Colleague,
Retest has been taken status are below:

issue1: Fixed
Issue2: Not Reproducible
Issue3:
Observed Behaviour:
Item count is read for group header also within list.
 
Expected Behaviour:
Ideally, item count should not be read for group headers.
Screenshot:
Issue4: Fixed.
Issue5: Fixed.
Issue6: partially fixed
Observed Behaviour:
Text alternative defining the purpose of UI is not provided for buttons highlighted in red.
Speech output is:
Sort ascending  Button  
To activate press spacebar.
Sort descending  Button  
To activate press spacebar..
 
Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI.
Screenshot:
Issue7:
Observed Behavior:
After pressing the buttons, information such as ascending/descending is not read.
Speech output is:
Sort ascending  Button  
To activate press spacebar.
Sort descending  Button  
To activate press spacebar.

 
Expected Behavior:
Ideally, information such as ascending/descending should be conveyed.
Screenshot:
Issue8: Fixed.
Issue9: Partially fixed
Observed Behavior:
Text alternative defining the purpose of UI is not provided for Buttons within the list.
Speech output is:.
Remove  Button  
To activate press spacebar.
Remove  Button  
To activate press spacebar.
 
Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI.
Screenshot:
issue10: Fixed
Issue11: 
Observed Behavior:
Not possible to drag and drop list items via keyboard.
Expected Behavior:
Ideally, it should be possible to drag and drop list items using keyboard.
screenshot:
Retest Environment:
Browse the preview: https://deploy-preview-7308--fundamental-ngx.netlify.app/
Browser: Chrome Version Version 100.0.4896.75 (Official Build) (64-bit)
Screen Reader: JAWS 2021.2111.13 ILM
Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken within the below environment test results are below:

issue1: Fixed,
issue2: Fixed.
Issue3: Still reproducible (Need input from PO)
Group headers are added in the list item count.
Reading made as : list
with 8 items
List Group Header
1 of 8
To move to an item press the Arrow keys.
Screen shot:

![image](https://user-images.githubusercontent.com/105037808/167367371-d2091258-671e-4ef4-a36d-4e9a91bf985a.png)


issue4: Fixed.
Issue5: Fixed.
Issue6: Fixed.
Issue7: Fixed.
Issue8: Fixed.
Issue9: Fixed.
Issue10: Fixed.
Issue11: Fixed.
Issue 12: Still reproducible (Need input from PO)
Observed Behavior:
Not possible to drag and drop list items via keyboard.

Retest Environment:

URL: https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
Browser: Version 101.0.4951.54 (Official Build) (64-bit)
Screen reader: JAWS 2022.2204. 20ILM

Thanks and Regards,
Karthikeyan.c
