### ISSUE TITLE
Platform - fdp-form-group in fd-dialog has several bugs

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#6226]
EDIT: possibly fixed by https://github.com/SAP/fundamental-ngx/pull/6062

When using the `fdp-form-group` inside an `fd-dialog` we have several issues.  As you can see in this screenshot there is too much padding and the textarea is very small, not occupying the width of the whole dialog.  When the user attempts to resize the textarea, the entire dialog gets bigger with it (which may be fine, if the textarea correctly fills the dialog)

<img width="670" alt="Screen Shot 2021-08-03 at 10 51 55 AM" src="https://user-images.githubusercontent.com/2471874/128036938-1d7bd4ea-8f52-4e7f-b800-cc6e1d4322fd.png">

Related fundamental-styles issue: https://github.com/SAP/fundamental-styles/issues/2612

**Comment by OleksiyDrozdov** [comment]
In order to test this task:
1. add new vertion fundamental-styles '0.20.0-rc.11' manually
![image.png](https://images.zenhubusercontent.com/60492e1f104385ee3fc0608a/7706d47f-651c-41a7-9d2c-f975871d9605)
2. and run 'npm install'
3. add attribute [compact]="true" into fdp-form-group or change on the page Home, Contebt Density to Compact
![image.png](https://images.zenhubusercontent.com/60492e1f104385ee3fc0608a/662f0fe1-d062-4257-825f-c5ca3d0e6034)
And you can see that padding disappears
Second issue with textarea I can not reproduce.
