### ISSUE TITLE
enhancement(platform): add option to show the footer in Wizard generator default mode

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#6444]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Add to Wizard generator (platform) the possibility to show the footer in default mode like it's done for wizard in dialog.
This scenario will be used in many types of entities in DXP so having this enhancement will avoid the code repetiotion.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### Time estimate
TBD

#### Sprint
TBD

**Comment by N1XUS** [comment]
@InnaAtanasova Since implementing such behavior in wizard generator itself might bring more issues (e.g. bar component needs to be floating in dialog, and static otherwise) with styling the bar itself, we provide an ability to externally control the wizard's navigation: https://fundamental-ngx.netlify.app/#/platform/wizard-generator#external-navigation-buttons
I think this way we will preserve the flexibility of the wizard yet keeping it as generic as possible to fit majority of usage scenarios
