### ISSUE TITLE
Concatenation issue with string "Item selected"

### ISSUE THREAD

**Issue by I835291** [SAP/fundamental-ngx#6972]
#### See screen shot
![concatenation_issue_1_item_selected](https://user-images.githubusercontent.com/86618211/138207431-839f9f72-3dab-403a-b7f9-8ce02649cad2.png)

**Comment by droshev** [comment]
@manjunathanagaraj can you follow up on this issue?

**Comment by skaquib123** [comment]
Hi @I835291 , Can you please describe the steps to reproduce the issue?

**Comment by skaquib123** [comment]
Hi @I835291,  as we have discussed since the issue is working as expected I am closing the issue. I have attached the screenshot showing the translation is working as expected.
![approvalflow_conacatenation](https://user-images.githubusercontent.com/110972289/206636216-5dd33157-9efc-48a5-a162-14051af9645a.png)
