### ISSUE TITLE
platform table column freeze bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7068]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Platform Table column freeze feature has issues when the text if a cell is longer:
<img width="851" alt="Screen Shot 2021-11-01 at 09 18 56" src="https://user-images.githubusercontent.com/4380815/139678072-10d8a778-33ba-43aa-89cb-73c2e8a704a7.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by platon-rov** [comment]
Here is the situation.

Regular cell, "connected" to the row: on height change row's height will change respectively.

![image](https://user-images.githubusercontent.com/20265336/140096352-ef58a19a-2e2e-45b8-86c9-590dcc6f044c.png)

Fixed cell, "disconnected" from the row: on row's height change cell's height won't be changed, on cell's height change row's height won't be changed also.

![image](https://user-images.githubusercontent.com/20265336/140096629-c22cff40-56b9-4982-9654-a72329d68a8b.png)

Solutions

a) Track height of every row and cell. If the row's height changes then update fixed cells height. If fixed cells height changes then change row's height.

b) Refactor table component using `position: sticky` for fixed cells.

@dmitry-stepanenko @dimamarksman maybe you guys have any other ideas or I missed something?

**Comment by dmitry-stepanenko** [comment]
@platon-rov  I totally agree with you and would prefer having "position: sticky" instead, because at this point we have to track too much:
- track "semantic hightlight" cells' height according to https://github.com/SAP/fundamental-ngx/issues/7067
- track "selection" cell's height according to https://github.com/SAP/fundamental-ngx/issues/7070
- track freezable cells according to this PR

This will introduce really a lot of unnecessary computations with big performance impact. 

As we discussed with you earlier, migration to "sticky" will be covered by https://github.com/SAP/fundamental-ngx/issues/7067

**Comment by mikerodonnell89** [comment]
Closing as this has apparently been fixed
