### ISSUE TITLE
Angular 13 migration

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7119]
prepare the repo to run with Angular 13:
- [ ] core
- [ ] platform
- [ ] schematics
depends on #7221

**Comment by platon-rov** [comment]
Hey there, nx plan to start supporting angular 13 from nx 13.2 release ([post #1](https://github.com/nrwl/nx/issues/7613#issuecomment-961397821), [post #2](https://issueexplorer.com/issue/nrwl/nx/7549)). Currently, it's 13.1.3. 

If we want to update asap it might or not bring new issues since angular 13 is not officially supported yet. Are we hurrying with updates?

I think it's okay to wait until nx 13.2 will be released and then process update.

**Comment by droshev** [comment]
I guess we can use https://nx.dev/l/n/core-concepts/updating-nx 
 
NX already released a version with angular 13

**Comment by droshev** [comment]
blocked with https://github.com/nrwl/nx/issues/7974
