### ISSUE TITLE
feat(pagination): improvements

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#7376]
#### Is this a bug, enhancement, or feature request?

Enhancement.

#### Briefly describe your proposal.

1. Emit event when itemsPerPage change.
2. Improve filtering of the itemsPerPageOptions.
  * Do not filter option that equals totalItems.
  * If totalItems changes update the available options.
3. improve the visual part following the figma [link](https://www.figma.com/file/YWGZcfjnGy2vLslsghEHXY/Pagination-Pattern?node-id=1%3A6)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.33.0-rc.214

**Comment by g-cheishvili** [comment]
> #### Is this a bug, enhancement, or feature request?
> Enhancement.
> 
> #### Briefly describe your proposal.
> 1. Emit event when itemsPerPage change.
> 2. Improve filtering of the itemsPerPageOptions.
> 
> * Do not filter option that equals totalItems.
> * If totalItems changes update the available options.
> 
> #### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
> 0.33.0-rc.214

Do you propose [(itemsPerPage)] support?
If totalItems number changes from outside, then what we should do with available options? Filter again? What happens if it changes again and becomes more than initial? What to do with previously filtered values? should we save it ? Would not it be better if we made visible items per page options calculated on the go?
