### ISSUE TITLE
Toggle component not working if id is present

### ISSUE THREAD

**Issue by hisabimbola** [SAP/fundamental-ngx#743]
#### Is this a bug, enhancement, or feature request?
Bug
#### If this is a bug, please provide steps for reproducing it.
Add `id` attribute on a toggle component
#### Please provide relevant source code if applicable.
Reproduced [here](https://stackblitz.com/edit/angular-u4jscm)

**Comment by MattL75** [comment]
I did some investigating on this. It works if you set the id using square brackets through `[id]`.

This happens because, when setting the id without the brackets, it's interpreted as setting an id on the toggle element itself. This behaviour isn't wrong, but we don't handle it properly inside the component. Our htmlFor points to the id provided, which in the case of using `id` without the square bracket, can be one of two elements: the input, or the toggle itself.

I think the best solution would be for us to append something like '-input' to the end of of both the htmlFor and the inner input id, and this for generated and provided ids.
