### ISSUE TITLE
Unable to trigger Date Picker's disableFunction post initialization

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#744]
#### Is this a bug, enhancement, or feature request?

Bug/enchancement

#### Briefly describe your proposal.

`disableFunction` is fired on component initialization and on nexMonth() prevMonth() but is not fired upon popover open

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

1) log the `disablefunction`
2) open calendar
3) see that fn is not called
4) unable to call it programatically

#### Please provide relevant source code if applicable.

n/a

#### Is there anything else we should know?

I find it inconsistent that `disableFunction` is being checked upon switching months/years, but is not being fired upon calendar (popover) opening.

More generic solution would be to allow triggering event programatically

**Comment by mikerodonnell89** [comment]
@konradkukier2  Dates are set to be enabled or disabled when the calendar day grid is constructed internally.  This happens when the calendar first loads, and again when a new year or month is selected.  Would it suffice to also check the disableFunction when the disableFunction input changes? I don't think it would be necessary to run the calendar construction logic every time the calendar is opened or closed.  Also I think if the calendar is automatically constructed whenever the disableFunction changes, it will not be necessary to need a way to call it programatically.
