### ISSUE TITLE
Remove style encapsulation

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#754]
In my opinion, it makes sense for a component library to remove style encapsulation. Most of our styles are coming from Fiori Fundamentals anyways, so there should be no worry of conflicting styles.

Users could benefit from easier css overrides if we did this.

@InnaAtanasova @droshev @mikerodonnell89

**Comment by droshev** [comment]
I would suggest we start with that and do it for all the components

**Comment by phr0st** [comment]
Hi, I have a question regarding this change. Right now I´m implementing an angular elements application, which lives in an different SAP application (SAP CPQ) in a shadow dom. Some of the SAP CPQ styles are using the same CSS classes (e.g. sap-icon) and as soon as fundamental-ngx styles are loaded it breaks the host application (icons are missing etc). 
Is there a workaround I can try to get my application working? I already set my root component to ViewEncapsulation.ShadowDom but its just for my styles and not for fundamental-ngx as they are using ViewEncapsulation.None since this change.

Best regards
Anton
