### ISSUE TITLE
Write documentation for fnDisabled/fnReadonly directives

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#7789]
In this PR https://github.com/SAP/fundamental-ngx/pull/7767 Giorgi implemented two new directives, fnDisabled and fnReadonly that allow us, our the developers using our library, to quickly and easily disable components or make them readonly. We should add some documentation for these directives under the "utilities" section.

**Comment by g-cheishvili** [comment]
Not only that, but also there is fnFocusable directive, which gives you ability to give focus feature to the elements, that would otherwise be non-focusable(div, section, span or anything). That other directive also respects above mentioned directives, so much so, it both are applied focusability is not applied
