### ISSUE TITLE
Table/Card toggle component?

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8204]
The goal (sprint 0):
- [ ] review the requirement and design from dxp. Any gap?
- [ ] explore how other libraries have it
- [ ] think about a possible solution in NGX(possible platform one) and impact for NGX
- [ ] present it at scrum
- [ ] evaluate whether NGX the right place for this feature?

1w 
dxp/ngx-dxp/issues/114

**Comment by platon-rov** [comment]
I'm against having this on our side and that's why

There is a components set (visual core, btp) where each of the components is a (very) basic building block. Complex components may be achieved by combining this small elementary components. In case we will be combining them by ourselves our codebase will grow significantly and it will take us a lot of time to maintain it. There might be hundreds of requests for the custom complex components because of the size of the SAP and we, for sure, could help teams with combining that basic components, but not adding them to our library.

**Comment by droshev** [comment]
We decided to do that internally for now.
