### ISSUE TITLE
Defect Hunting: Overflow layout improvements

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8429]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
- [x] Overflow layout
An item from the overflow menu should go outside of the menu if selected. 
Here's the UI5 behaviour:
1. 12 items visible, the rest in overflow menu
<img width="981" alt="Screen Shot 2022-07-11 at 3 59 15 PM" src="https://user-images.githubusercontent.com/39598672/178348252-80b72f57-52b9-47cd-ac6c-42aca1ccad96.png">

2. Select Tab 26
<img width="978" alt="Screen Shot 2022-07-11 at 3 59 23 PM" src="https://user-images.githubusercontent.com/39598672/178348309-85389a39-c103-45c8-b0fa-4cbef6b9fd1d.png">

3. Tab 26 is not the last of the "visible" items
<img width="981" alt="Screen Shot 2022-07-11 at 3 59 29 PM" src="https://user-images.githubusercontent.com/39598672/178348418-345cd249-2eea-4fa2-9643-0aafce7e792f.png">

- [ ] Overflow Layout Complex example
If we use the example of Avatar Group the overflow button should be following the same pattern
<img width="1221" alt="Screen Shot 2022-07-11 at 4 05 24 PM" src="https://user-images.githubusercontent.com/39598672/178348824-4438330d-ab1f-4b32-8168-d18e8d24df59.png">

@N1XUS: Overflow layout with avatar example uses such layout just to show that we can also calculate complex layouts. This example wasn't designed to be exactly as with avatar group

**Comment by N1XUS** [comment]
First item:
it is done for this example: https://fundamental-ngx.netlify.app/#/core/overflow-layout#forced-visibility.

Reason why it's disabled by default: Since Overflow Layout will be used for different components such as Avatar group, breadcrumbs, tabs, etc, it should contain common behaviour.

Let's take for the example Avatar group: when user clicks on the item in popover, it does not go to the visible section, instead user should implement it's own logic for the click.
Breadcrumbs: if user clicks on the item from the dropdown menu, it should redirect user to the breadcrumb's url.

The only components what are implementing the behaviour described in the issue are tabs.

So on my opinion, this option should be disabled by default. Developers have all necessary functionality to implement such logic in easy and convenient way.
