### ISSUE TITLE
Theming Bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8457]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

- [ ] SAP Icons are not loaded.

1. create a new angular app
2. add `@fundamental-ngx/core`
3. import `ButtonModule`
4. add a button with an icon
```
<button fd-button fdType="transparent" glyph="menu2" ariaLabel="Menu Transparent" title="Menu Transparent"></button>
```
The icons are not rendered

- [ ] Another issue which could be related to that is: changing the theme from Fiori 3 to Horizon doesn't change the icon file.

- [ ] Can we add an example how to set a (random) theme by default in an application (not through `ng add` schematics but through the API)?

**Comment by N1XUS** [comment]
1. Icons are not loaded since they are loaded with ThemingService (from ThemingModule), which we aren't importing to the user's application, this needs to be done by the user manually. Added info message during schematics execution.
2. Depends on which theming provider they are using (deprecated one, or a new one). Old one will not import sap icons since this feature is a new one, and the service is deprecated now.
3. We have everything documented here for a manual process https://sap.github.io/fundamental-ngx/#/core/theming
