### ISSUE TITLE
bug: FDP Dynamic Page / FD Tab List: wrong initial `tabChange` event

### ISSUE THREAD

**Issue by MalteBellmann** [SAP/fundamental-ngx#8605]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
When an FDP Dynamic Page / FD Tab List is loaded initially, a  `tabChange` event is always triggered for the first tab. While this might be expected, this event is also triggered for the first tab even if the selected tab was changed programmatically before with `setSelectedTab`.
Therefore, we first get an event for the new tab, then an event for the first tab, which is wrong.
Additionally, the tab is not switched correctly to the new tab.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 14.0.2, Fundamentals 0.36.0-rc.35

#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-e3989p?devToolsHeight=33&file=src/app/platform-dynamic-page-tabbed-example.component.ts

See the log in the console, first the correct event for the new tab is shown, then an event for the first tab. 
Additionally, the tab is not switched correctly to the second tab.

**Comment by mikerodonnell89** [comment]
related to #8050

**Comment by mikerodonnell89** [comment]
@MalteBellmann please try updating to the latest RC, 0.36.0-rc.40

See this fork: https://angular-e3989p-dfaa2s.stackblitz.io

In the console.log you will see the tab 1 log thrown before the tab 2, which I believe is the correct way this event should be working (since the tab list is initialized before the setSelectedTab function from dynamic page is called)

**Comment by MalteBellmann** [comment]
Yes, with 0.36.0-rc.40 it is working, thanks
