### ISSUE TITLE
bug(platform): no list item component that accepts any content

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#8657]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

In core we have `fd-list-item` directive which allows any content to be inside `li` elements to which is being applied. 

In platform we have various list item components although no one accepts random content, every component has predefined template and inputs.

So, to have list item with any content inside of it we have to use both - platform list and core list item, what's actually the wrong approach.

```html
<fdp-list <!-- Platform Comp -->
  <li fd-list-item *fdpItemDef <!-- Core Comp, Platform Directive -->
```

**Comment by platon-rov** [comment]
Hm, implementing `fdp-list-item` component probably does not make much sense because it will only copy the `fd-list-item` implementation and in case of changes we have to update both. Even if we simply extend core list item we still have to keep in sync templates and metadata of the decorators for both.

Important to say that we should have attribute selectors for any list item components, because otherwise the resulting dom won't be valid as there will be a layer between `ul` and `li`. That's actually the bug in current implementatitons of platform list item components.

```html
<ul
  <fdp-standart-list-item <!-- Having this layer actually html validity -->
    <li
```

Continue thinking on this one...

**Comment by ivzhelev** [comment]
Thanks, @N1XUS, the fix is working as expected. 
Just one general consulting question: 
with ```<fdp-standard-list-item titleIcon="sap-icon sap-icon--account">```
we see the icon being correctly displayed:  
![image](https://user-images.githubusercontent.com/8601332/207625607-19ade72a-d0e0-4fbe-b072-4ea0afd98ae0.png)


but is it possible for us to adjust the color like this: 

![image](https://user-images.githubusercontent.com/8601332/207625468-38fc2f78-0391-4898-a583-1e4921801034.png)

the icon spec is: 
![image](https://user-images.githubusercontent.com/8601332/207625728-add6a2e2-d999-4919-9558-507346a12d42.png)

Thanks in advance!

**Comment by DimitarVoynov** [comment]
Hi @N1XUS and happy new year! :)

Did you have a chance to check the last question about the icon from @ivzhelev ? 

Thanks, 
Dimitar

**Comment by DimitarVoynov** [comment]
Hi @g-cheishvili , as we are not sure if @N1XUS is available, can you please have a look at the above question about the notification icon? 

Thanks in advance!
Dimitar
