### ISSUE TITLE
WC Investigations and PoC directive generation

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#8838]
- [x] prepare a wrapping generation [example](https://github.com/g-cheishvili/ui5-angular) (waiting for WC to update the project related to form)
- [x] adapt feature
  - [x] RTL
  - [x] Icons
  - [x] Localization
  - [x] Theming
  - [x] Fonts
  - [x] Content Density
- [x] explore auto-generating the documentation from ui5wc - not needed if we keep the package in ui5 WebC repo
- [x] Open Questions
  - [x] shall we publish the auto-generation in a separate package
  - [x] where will that package reside - it will better to be in ui5 WebC repo
  - [x] do we need to match the version between ui5 wc and the generated package ( Marcus brought an argument against - in case the generator has issues to be fixed and this will lead to bump the version independently)

- [x] investigate JSX usage as an alternative to handlebar and present the findings @g-cheishvili

**Comment by g-cheishvili** [comment]
I have thought about "adapt feature" section and concluded that those things should remain outside of the angular world because there is zero benefits for their adaptation. Except for the content density and RTL. In the case of the theming, fonts, icons and localization, provided approaches from @ui5/webcomponents satisfy needs and are not that different from angular ways of doing things. Functions for setting theme and etc can be called from main.ts and adequately used.
CC: @InnaAtanasova @droshev
