### ISSUE TITLE
[sourcing] `<fdp-checkbox>`'s `[value]` binding not work as expected, but legacy `[checked]` work well.

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#8963]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
`[value]` binding does not work as expected, but legacy `[checked]` works well.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
@fundamental-ngx/core 0.36.0
@fundamental-ngx/i18n 0.36.0
@fundamental-ngx/platform 0.36.0
@angular/core 14.0.2
```
#### If this is a bug, please provide steps for reproducing it.
Check online demo: 
https://stackblitz.com/edit/angular-v5xgwz?file=src/app/platform-binary-checkbox.component.html

#### Please provide relevant source code if applicable.
Notice that even though both are set to `true`, only the first one is checked.
![Oscar ScreenShot 2022-11-15 at 13 31 29@2x](https://user-images.githubusercontent.com/7035787/202029480-9806ba70-c254-49cb-b744-e395aa378a05.png)

**Comment by N1XUS** [comment]
Hello @oscargong.
Let me explain the difference between `value` and `checked` input properties.

`value` is a deprecated property (see `values` property) which used to set value for checked or unchecked state (e.g. when checkbox is checked, instead of `true`, developers can define own value, such as `Yes`) which will be later reflected in the model or form group.

`checked` on the other hand is used to set the state of the checkbox itself (as property states, checked true/false).
