### ISSUE TITLE
bug(platform): smart filter bar double loading

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#9063]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

If there is delay before data comes to table, this delay doubled for filter fields above the table. Also, there is delay when we open dialog for certain filter field that has options. 

*Videos been taken from skeleton feature branch but this issue existed before it and not related to skeleton itself*

https://user-images.githubusercontent.com/20265336/206716479-2f8303b2-116c-4103-bdfe-c8f25a499d24.mp4

https://user-images.githubusercontent.com/20265336/206716732-bed2cf0d-1eee-4d13-8b19-2f4a3c8c4f38.mp4

**Comment by N1XUS** [comment]
After speaking with @platon-rov we came to such conclusion:
* Smart Filter Bar uses the same DataSource as the table does, but with different parameters for fetch. This is done in order to ignore pagination, columns visibility, etc. Because even though some column might be hidden in table, it still can be used in filtering. Same goes to pagination. If we have 10 entries with the same data for column that supports autocompletion, and second page (which is not fetched) includes more data, autocomplete doesn't make sense.
* Case @platon-rov provided in the ticket is simulation of the http request to the backend to retrieve data, so it's more likely that developers already have custom datasource, and the correct way of handling such behaviour is to implement caching mechanizm of the data based on the fetch parameters.

For now I'm closing the issue @droshev
