### ISSUE TITLE
feat: investigate NgOptimizedImage module

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#9090]
Since we have components that uses images, we should investigate the benefits of https://angular.io/api/common/NgOptimizedImage

**Comment by g-cheishvili** [comment]
We use `img` only in the platform thumbnail module. [NgOptimizedImage](https://angular.io/api/common/NgOptimizedImage) has the necessity for width and height, which we do not have in that components. If you remove that requirement with `fill`, then the effect is different. So I think that this module would be more suitable for applications, rather than libraries. But I might be wrong
