### ISSUE TITLE
Type enhancements for form-generator form items

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/fundamental-ngx#9349]
#### Is this a bug, enhancement, or feature request?
Enhancement and a feature request

#### Briefly describe your proposal.
First of all [these things](https://github.com/SAP/fundamental-ngx/blob/b959835f95d2da26cbb406187a602b158401f55b/libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-item.ts#L231-L239) do not belong here, because that interface should contain only the common things, that are applicable to every form control which we provide.
The need for adding these lines came from limited capabilities of configuring form elements in form-generator, to enhance the form generator in a way that it supports more features from supported out-of-the-box controls, we need to enhance our typings for [DynamicFormFieldItem](https://github.com/SAP/fundamental-ngx/blob/b959835f95d2da26cbb406187a602b158401f55b/libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-item.ts#L71).

My proposal is that instead of having `type: string` we make a generic base interface, then write down type-specific interfaces, like for this example `type: 'select' | 'list'` would contain those properties mentioned above and many others, which are specific to select component. This way we would support more functionality and also it would be better typed.

**Comment by g-cheishvili** [comment]
This is issue mentions only `select`, but actually other controls should be taken care of as well

**Comment by g-cheishvili** [comment]
In general, this should be revisited, bunch of the properties might not belong here if we think through them

**Comment by littleamigo** [comment]
I'm fine with this proposal as long as we get a chance to use the full capabilities of the listed components at https://sap.github.io/fundamental-ngx/#/platform/wizard-generator > Wizard Generator Elements.

Note, that the documentation doesn't limit the features of e.g. select when used in the wizard. The same answer was given by @droshev in a recent call.

It's a little bit of a sad situation for us because we already got 90% of what we wanted with https://github.com/SAP/fundamental-ngx/pull/9252 and now, that I try to finish it up and adding a property that was missing in the first place due to lack of knowledge about the select-2-column-rendering peculiarities, we end up in a bigger story of refactoring. How log do you think it may take until we get a solution to fix our issue with the unsuitable default control body for 2-column-rendering?

**Comment by littleamigo** [comment]
@g-cheishvili What are the next steps?

**Comment by g-cheishvili** [comment]
> @g-cheishvili What are the next steps?

We think we can approve your update and in the near future do it differently

**Comment by g-cheishvili** [comment]
This issue has been addressed in #8927
