### ISSUE TITLE
Unable to disable drag-n-drop in fdp-table tree. 

### ISSUE THREAD

**Issue by ogobelbel** [SAP/fundamental-ngx#9383]
Question.

Are there any chanses to disable drag-n-drop feature in dp-table tree?

**Comment by N1XUS** [comment]
Hello @ogobelbel.
You can disable dnd feature by providing initial sorting.

**Comment by oscargong** [comment]
We can disable drag-n-drop on `<fdp-table />` by setting a trivial `[initialFilterBy]="initialFilterBy"`. But this will cause a style issue: even though the row cannot be dragged, the cursor style is still "grab"

**Comment by I543348** [comment]
This is high priority for Guided Sourcing as well.

**Comment by fkolar** [comment]
I think there should be some direct settings to unable or disable D&D, instead of setting additional properties, since there are internal connections between. those and D&D - this is not transparent. 

There should be something like: 

```html
<fdp-table enableColumnReordering =true enableRowReordering=true>

```

I believe by default this is more advanced functionality for the table and it should be disabled by default, this is why the bindings start `enable...`
