### ISSUE TITLE
[Sourcing] fdp-table multi selection is cleared after searching text and clearing 

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9455]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The table selection should not get cleared after searching and clearing the text

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
ng: 15
core/platform: 0.38.2

#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-1lhnxc?file=src/app/platform-table-multiple-row-selection-example.component.html 
Scenarios:Select the row and search for other row item.Select the row and search for the same row.Search and select the row then come back.The selection is not getting retained.

#### Please provide relevant source code if applicable.
pls refer to stackblitz link

#### Is there anything else we should know?
This is needed for guided sourcing customers

**Comment by mikerodonnell89** [comment]
You can use the `rowComparator` input, mentioned in this example: https://fundamental-ngx.netlify.app/#/platform/table#single-row-selection

It also works with multi-selection tables. However your search results must contain the selected item. If an item is selected and you perform a search that does not return your recently selected item, the item will display again as unselected when you clear the search input and search again. Is that functionality you would need as well?

**Comment by mikerodonnell89** [comment]
This can be achieved utilizing the `rowComparator` input from this example: https://fundamental-ngx.netlify.app/#/platform/table#single-row-selection

As well as the `selectedKey` input mentioned in this example: https://fundamental-ngx.netlify.app/#/platform/table#multiple-row-selection

However, note that if you select an item, and search for another item where the search results do not contain the newly selected item, when you search for the newly selected item it will appear unselected. This is because you haven't made any modifications to the datasource for whether or not that item should be selected.  In order to do that, you must catch the `TableRowSelectionChangeEvent`, match the corresponding item on your datasource and change the value of whatever you have chosen for `selectedKey`. This needs to happen outside of the ngx library because presumably REST calls will be made and you'll need to verify that these are successful on the backend.

**Comment by I543348** [comment]
The suggestion works fine thanks @mikerodonnell89
