### ISSUE TITLE
implement Split button 

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#949]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
Implement the split button that was released in `fundamental-styles` https://sap.github.io/fundamental-styles/components/button.html
<img width="433" alt="Screen Shot 2019-06-18 at 11 35 57 AM" src="https://user-images.githubusercontent.com/4380815/59698241-45f45e00-91bd-11e9-8b17-eafd8d0eb7d8.png">

**Comment by MattL75** [comment]
**Proposed Requirements**
* Follow accessibility guidelines for [listbox](https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox), including [roles, states and properties](https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_roles_states_props). We could also investigate using the role _menuitem_ for the inner options since some component libraries use that.
* Follow pattern set in the dropdown branch (not merged), which allows control over individual elements. Another option would be to make this component very opinionated and only allow users to pass in a list of strings.
* Customizable icon for the right-side dropdown button.
* Content for the left-side action button should be customizable either directly or by ng-template.
* isOpen input, along with an isOpenChange event to enable two-way binding. This controls the state of the popover.
* Provide function to programatically select an option.
* Ensure programmatic focus works as expected, and provide a function for it if needed.

**Comment by JKMarkowski** [comment]
Just FYI, I'm currently on it.

**Comment by MattL75** [comment]
@JKMarkowski Thanks. We're going to add some details to this issue in our grooming so keep your eyes peeled for updated information
