### ISSUE TITLE
[Sourcing][Reopen] fdp-table : Tooltip for column size shrink with lengthy name

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9533]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Upon column shrinking  resizing - if the column name is lengthy, a tooltip should be shown to the user.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 15
core / platform : 0.39.1-rc-5

#### If this is a bug, please provide steps for reproducing it.
This is replicable in https://sap.github.io/fundamental-ngx/#/platform/table#default

1) shrink the column
2) text is truncated with elipsis
3) hover on the column 
4) no tooltip displayed

#### Is there anything else we should know?

This is  blocker for guided sourcing.

**Comment by fkolar** [comment]
Solution could be to wrap this with span and provide a title

**Comment by fkolar** [comment]
PR created 9612, Still thinking about improvement

**Comment by rayansailani** [comment]
@fkolar - I'm checking the fundamental website and this fix isn't working. Is this not enabled by default ? Can you please take a look ? 
Thanks. 

<img width="1445" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/54993789/33514ba5-5925-4fba-8ff3-e59bc61734da">

**Comment by fkolar** [comment]
Reopening issue, we need to track this. After merging this to main branch together with another PR from @N1XUS _feat(platform): custom table popover renderer (#9659)_

1. We need to add following code into the `table-header-cell-content.component.html`
 what was in the table.component.html 

```html
<ng-template #tableHeaderCellContentTemplate let-column="column">
    <ng-container *ngIf="column?.headerCellTemplate; else defaultHeaderCellTemplate">
        <ng-template
            [ngTemplateOutlet]="column.headerCellTemplate"
            [ngTemplateOutletContext]="{ $implicit: column }"
        ></ng-template>
    </ng-container>

    <ng-template #defaultHeaderCellTemplate>
        <span
            [id]="id + '-header-cell-' + column.name"
            [attr.title]="column?.headerOverflows ? column.label : null"
            class="fd-table__cell--truncate-txt"
        >
            {{ column?.label }}
        </span>
    </ng-template>
</ng-template>
```

2. Add Id Input to the `table-header-cell-content.component.ts` so we can pass table id from the parent template

```html
<fdp-table-header-cell-content
                            [id]="id"
                            [column]="column"
                            [hasFilter]="_filterRulesMap.has(column.key)"
                            [hasSorting]="_sortRulesMap.has(column.key)"
                            [sorting]...
```

3. Update CSS styling or update `table-column-resize.service.ts` so the calc. works as before. 
```ts
 private _updateHeaderOverflowState(updatedWidth: number): void {
        const element = this._columnsCellMap
            .get(this._resizedColumn)
            ?.find((c) => c?.nativeElement.tagName === 'TH')?.nativeElement;
        const visibleColumn = this._tableRef.getVisibleTableColumns().find((c) => c.name === this._resizedColumn);
        const headerTextElem = element?.querySelector(`#${this._tableRef.id}-header-cell-${this._resizedColumn}`);

        if (!headerTextElem || !visibleColumn) {
            return;
        }
        visibleColumn.headerOverflows = headerTextElem.scrollWidth > updatedWidth;
    }
```

 * Since this new component that is inside TH has display:flex, it a bit complicates things. The width goes over the `TH `width, so the styling and calculation stopped working. 
 
<img width="184" alt="Screenshot 2023-05-18 at 11 55 38" src="https://github.com/SAP/fundamental-ngx/assets/17149942/b12eb05a-8322-49a6-870b-090d5f8bdc4c">
