### ISSUE TITLE
[Sourcing] stopPropagation on Tree Table on Drag Event

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9721]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
In AribaCoreUI table, when dragging on a clickable element, the click event doesn't get triggered after the drag event.

https://user-images.githubusercontent.com/7035787/233491042-57ef38dd-4406-497f-920e-f95d57fdeab6.mp4

But, this behavior is different on Fundamental-NGX Platform tree table. Click event does get triggered after the drag event.

https://user-images.githubusercontent.com/7035787/233492020-047e7ac4-73d9-4545-a903-0c401559612b.mp4

Could we have similar behavior on Fundamental-NGX?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

```
    "@fundamental-ngx/core": "0.40.2-rc.7",
    "@fundamental-ngx/platform": "0.40.2-rc.7"
```

#### If this is a bug, please provide steps for reproducing it.
Not a bug

**Comment by fkolar** [comment]
I see it's not that much feature but more bug. When we allow custom cell content with click events user should not be distracted by opening a dialogs and popups, or triggering some backend calls. I agree that during DRAG/DROP event we should skip propagation of this. - But not always !

But instead of implementing this directly inside table I would expose an event so I application can have their own behavior. There is already one output `rowsRearrange`, but this emits after all is finished. 

So the proposal is: 

1. extend this event for the state:

```ts

export class TableRowsRearrangeEvent<T> {
    /**
     * Table rows rearrange event
     * @param row Row that was rearranged
     * @param previousIndex Previous index of the row
     * @param newIndex New index of the row
     * @param rows All rows of the table
     */
    constructor(
        public row: T,     
        public dropRow: T,
        public previousIndex: number,
        public newIndex: number,
        public insertAt: 'before' | 'after' | null,
        public mode: FdDndDropEventMode,
        public rows: T[],
        public state: 'started | inprogress | finished'
    ) {}
}

```

2. Trigger this event when drag starts and application can decide if they want to skip the handling or or not. But we would have to check this so we dont run into some race condition. 


In table we do allow click events after some times but not during dragging so this is intentional. 
```ts
dragDropItemDrop(event: FdDropEvent<TableRow>): void {
        /** After timeout to make click event handled first */
        this._ngZone.runOutsideAngular(() => {
            setTimeout(() => (this._dragDropInProgress = false));
        });

```

**Comment by fkolar** [comment]
**Update:**

I think for situation where is popover and we have `this._renderer.listen`..., does not matter if you catch the even inside RowClick or Cell click as this even is already executed and popoever is shown. So for situation like this it better to handle it on the application level. 

```html
<fdp-table-cell *fdpCellDef="let node">
            <button fd-button [fdPopoverTrigger]="popover3"   (click)="onClick(table, $event)">Popover Trigger</button>
            <fd-popover #popover3>
        
```


```ts
onClick(table: TableComponent, event: MouseEvent) {
        if ((table as any)._dragDropInProgress) {
            console.log('onClick' + (table as any)._dragDropInProgress);
            event.stopImmediatePropagation();
```

**Comment by fkolar** [comment]
Closing with workaround and there is not such to do on the level of fundamentals.

**Comment by I543348** [comment]
@oscargong  pls evaluate the fix.
Thanks.

**Comment by oscargong** [comment]
workaround is working
