### ISSUE TITLE
[BUG] Dialog initial focus is no longer set

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-ngx#9766]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

According to the docs and behavior in previous versions:

> By default after opening the Dialog first focusable element will be focused.
https://sap.github.io/fundamental-ngx/#/core/dialog%23template-as-content

Now, nothing is in focus when opening the dialog.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.40

#### If this is a bug, please provide steps for reproducing it.
You can reproduce it in the [docs](https://sap.github.io/fundamental-ngx/#/core/dialog%23template-as-content) by opening the dialog in the first example. Nothing's in focus.

#### Is there anything else we should know?
Please either 
1. provide a fix for v0.40.1 as well or 
2. fix the bugs #9764 and https://github.com/SAP/fundamental-styles/issues/4482 so that we can upgrade our project to the current version.

**Comment by mikerodonnell89** [comment]
You can use the `fdInitialFocus` directive to focus an element when the dialog is loaded. This was used in previous versions of the documentation but was since removed for some reason (see this old version [here](https://deploy-preview-9008--fundamental-ngx.netlify.app/#/core/dialog#template-as-content)). The default dialog will handle this automatically (see [here](https://github.com/SAP/fundamental-ngx/blob/main/libs/core/src/lib/dialog/dialog-default/dialog-default.component.html#L25)) but if you are implementing your own confirmation/cancel buttons, as in the examples on the current documentation, you'll need to add the initial focus directive manually

**Comment by droshev** [comment]
@JenniferStamm the fixes will be/are part of version `0.40.4`

**Comment by JenniferStamm** [comment]
@droshev great, thank you!
